Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (1, 'NYSE', 'New York Stock Exchange', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (2, 'NASDAQ', 'NASDAQ Stock Market', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (3, 'CME', 'Chicago Mercantile Exchange', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (4, 'BIST', 'Borsa Istanbul', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (5, 'BINGX', 'BingX', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (6, 'BYBIT', 'Bybit', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (7, 'COINBASE', 'Coinbase', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (8, 'AMEX', 'American Stock Exchange', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (9, 'CBOE', 'Chicago Board Options Exchange', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (10, 'LSE', 'London Stock Exchange', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (11, 'HKEX', 'Hong Kong Stock Exchange', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (12, 'TSE', 'Tokyo Stock Exchange', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (13, 'SSE', 'Shanghai Stock Exchange', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (14, 'SZSE', 'Shenzhen Stock Exchange', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (15, 'ASX', 'Australian Securities Exchange', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (16, 'TSX', 'Toronto Stock Exchange', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (17, 'BSE', 'Bombay Stock Exchange', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (18, 'NSE', 'National Stock Exchange of India', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (19, 'KRX', 'Korea Exchange', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (20, 'BMV', 'Bolsa Mexicana de Valores', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DisplayOrder, IsActive) values (21, 'BINANCE', 'Binance', 1000, 1);