Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (1, 'NYSE', 'New York Stock Exchange', 'USD', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (2, 'NASDAQ', 'NASDAQ Stock Market', 'USD', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (3, 'CME', 'Chicago Mercantile Exchange', 'USD', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (4, 'BIST', 'Borsa Istanbul', 'TRY', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (5, 'BINGX', 'BingX', 'USDT', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (6, 'BYBIT', 'Bybit', 'USDT', 1000, 1);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (7, 'COINBASE', 'Coinbase', 'USD', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (8, 'AMEX', 'American Stock Exchange', 'USD', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (9, 'CBOE', 'Chicago Board Options Exchange', 'USD', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (10, 'LSE', 'London Stock Exchange', 'GBP', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (11, 'HKEX', 'Hong Kong Stock Exchange', 'HKD', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (12, 'TSE', 'Tokyo Stock Exchange', 'JPY', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (13, 'SSE', 'Shanghai Stock Exchange', 'CNY', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (14, 'SZSE', 'Shenzhen Stock Exchange', 'CNY', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (15, 'ASX', 'Australian Securities Exchange', 'AUD', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (16, 'TSX', 'Toronto Stock Exchange', 'CAD', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (17, 'BSE', 'Bombay Stock Exchange', 'INR', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (18, 'NSE', 'National Stock Exchange of India', 'INR', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (19, 'KRX', 'Korea Exchange', 'KRW', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (20, 'BMV', 'Bolsa Mexicana de Valores', 'MXN', 1000, 0);
Insert into Exchanges(Id, ExchangeCode, ExchangeName, DefaultCurrency, DisplayOrder, IsActive) values (21, 'BINANCE', 'Binance', 'USDT', 1000, 0);