//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using System.Globalization;
using Microsoft.Data.Sqlite;

namespace TD.SQLite.Extensions
{
    /// <summary>
    /// Extension methods for <see cref="SqliteCommand"/> to simplify adding parameters, especially nullable ones.
    /// </summary>
    public static class SqliteExtensions
    {
        /// <summary>
        /// Adds a nullable decimal parameter as a scaled integer (<see cref="SqliteType.Integer"/>) to the specified
        /// <see cref="SqliteCommand"/>.
        /// </summary>
        /// <remarks>
        /// The decimal value is multiplied by 10 raised to <paramref name="scale"/> before being assigned to the
        /// parameter. For example, with scale 4, 123.66 is stored as 1236600. Values less than 1 are treated as 1.
        /// </remarks>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added.</param>
        /// <param name="parameterName">The name of the parameter to add.</param>
        /// <param name="value">The nullable decimal value to convert and assign. If null, the parameter value is set to null.</param>
        /// <param name="scale">The base-10 scale used for decimal-to-integer conversion.</param>
        public static void AddDecimalToIntegerParameter(this SqliteCommand command, string parameterName, decimal? value, int scale)
        {
            if (scale < 1)
            {
                throw new ArgumentOutOfRangeException(nameof(scale), scale, "Scale must be greater than or equal to 1.");
            }

            var parameter = command.GetParameter(parameterName, SqliteType.Integer);
            parameter.Value = value.HasValue ? (long)(value.Value * (long)Math.Pow(10, scale)) : null;
            command.Parameters.Add(parameter);
        }

        /// <summary>
        /// Adds a nullable 64-bit integer parameter to the specified <see cref="SqliteCommand"/>.
        /// </summary>
        /// <remarks>This method simplifies adding parameters that may have null values to a SQLite
        /// command, ensuring that nulls are correctly represented as <see cref="DBNull.Value"/> in the
        /// database.</remarks>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Cannot be null or empty.</param>
        /// <param name="value">The nullable 64-bit integer value to assign to the parameter. If null, the parameter value is set to <see
        /// cref="DBNull.Value"/>.</param>
        public static void AddNullableParameter(this SqliteCommand command, string parameterName, long? value)
        {
            var parameter = command.GetParameter(parameterName, SqliteType.Integer);
            parameter.Value = value is null ? DBNull.Value : value;
            command.Parameters.Add(parameter);
        }

        /// <summary>
        /// Adds a nullable integer parameter to the specified <see cref="SqliteCommand"/>. If the value is null, the
        /// parameter is set to <see langword="DBNull.Value"/>; otherwise, the integer value is assigned.
        /// </summary>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added.</param>
        /// <param name="parameterName">The name of the parameter to add to the command.</param>
        /// <param name="value">The nullable integer value to assign to the parameter. If null, the parameter is set to <see
        /// langword="DBNull.Value"/>.</param>
        public static void AddNullableParameter(this SqliteCommand command, string parameterName, int? value)
        {
            AddNullableParameter(command, parameterName, (long?)value);
        }

        /// <summary>
        /// Adds a nullable decimal parameter to the specified <see cref="SqliteCommand"/>. If the value is null, the
        /// parameter is set to <see langword="DBNull.Value"/>; otherwise, the decimal value is assigned.
        /// </summary>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added.</param>
        /// <param name="parameterName">The name of the parameter to add to the command.</param>
        /// <param name="value">The nullable decimal value to assign to the parameter. If null, the parameter is set to <see
        /// langword="DBNull.Value"/>.</param>
        public static void AddNullableParameter(this SqliteCommand command, string parameterName, decimal? value)
        {
            var parameter = command.GetParameter(parameterName, SqliteType.Text);
            parameter.Value = value.HasValue
                ? value.Value.ToString(CultureInfo.InvariantCulture)
                : DBNull.Value;

            command.Parameters.Add(parameter);
        }

        /// <summary>
        /// Retrieves a nullable decimal value from the specified <see cref="SqliteDataReader"/> at the given ordinal.
        /// </summary>
        /// <param name="reader">The <see cref="SqliteDataReader"/> from which to retrieve the value.</param>
        /// <param name="ordinal">The zero-based column ordinal.</param>
        /// <returns>The nullable decimal value, or null if the column is DBNull.</returns>
        public static decimal? GetNullableDecimal(this SqliteDataReader reader, int ordinal)
        {
            if (reader.IsDBNull(ordinal))
            {
                return null;
            }
            var value = reader.GetString(ordinal);
            if (decimal.TryParse(value, NumberStyles.Any, CultureInfo.InvariantCulture, out decimal result))
            {
                return result;
            }
            throw new FormatException($"The value '{value}' at ordinal {ordinal} cannot be parsed as a decimal.");
        }

        /// <summary>
        /// Adds a nullable double parameter to the specified <see cref="SqliteCommand"/> as a parameter of type <see
        /// cref="SqliteType.Real"/>. If the value is null, the parameter is set to <see cref="DBNull.Value"/>.
        /// </summary>
        /// <remarks>This extension method simplifies adding parameters that may have null values to a
        /// SQLite command, ensuring correct handling of database nulls.</remarks>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Cannot be null or empty.</param>
        /// <param name="value">The nullable double value to assign to the parameter. If null, the parameter value is set to <see
        /// cref="DBNull.Value"/>.</param>
        public static void AddNullableParameter(this SqliteCommand command, string parameterName, double? value)
        {
            var parameter = command.GetParameter(parameterName, SqliteType.Real);
            parameter.Value = value is null ? DBNull.Value : value;
            command.Parameters.Add(parameter);
        }

        /// <summary>
        /// Adds a nullable text parameter to the specified <see cref="SqliteCommand"/>. If the value is null, the
        /// parameter is set to <see cref="DBNull.Value"/>; otherwise, it is set to the provided string value.
        /// </summary>
        /// <remarks>This method simplifies adding parameters that may have null values, ensuring correct
        /// handling of database NULLs in SQLite commands.</remarks>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Must not be null or empty.</param>
        /// <param name="value">The string value to assign to the parameter, or null to represent a database NULL.</param>
        public static void AddNullableParameter(this SqliteCommand command, string parameterName, string? value)
        {
            var parameter = command.GetParameter(parameterName, SqliteType.Text);
            parameter.Value = value is null ? DBNull.Value : value;
            command.Parameters.Add(parameter);
        }

        /// <summary>
        /// Creates a new <see cref="SqliteParameter"/> with the specified name and type for the given <see
        /// cref="SqliteCommand"/>.
        /// </summary>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added.</param>
        /// <param name="parameterName">The name to assign to the parameter.</param>
        /// <param name="paramType">The SQLite data type to assign to the parameter.</param>
        /// <returns>A new <see cref="SqliteParameter"/> instance with the specified name and type.</returns>
        public static SqliteParameter GetParameter(this SqliteCommand command, string parameterName, SqliteType paramType)
        {
            var parameter = command.CreateParameter();
            parameter.ParameterName = parameterName;
            parameter.SqliteType = paramType;

            return parameter;
        }
    }
}
