using TD.Helpers;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.AppInfra.ViewModels
{
    public partial class QueryParametersVM : AbstractViewModel
    {
        public QueryParametersVM() : this(new QueryParameters()) { }
        public QueryParametersVM(QueryParameters queryParam)
        {
            QueryParameters  = queryParam;
        }

        public QueryParameters QueryParameters { get; }
        
        public int PageCount => QueryParameters.PageCount;
        
        public int Page
        {
            get => QueryParameters.Page;
            set
            {
                QueryParameters.Page = value;
                RaisePropertyChanged(nameof(Page));
            }
        }
        
        public int PageSize
        {
            get => QueryParameters.PageSize;
            set
            {
                QueryParameters.PageSize = value;
                RaisePropertyChanged(nameof(PageSize));
            }
        }
        
        public string? SearchString
        {
            get => QueryParameters.SearchString;
            set
            {
                QueryParameters.SearchString = value;
                RaisePropertyChanged(nameof(SearchString));
            }
        }
        
        public long TotalCount
        {
            get => QueryParameters.TotalCount;
            set
            {
                QueryParameters.TotalCount = value;
                RaisePropertyChanged(nameof(TotalCount));
            }
        }
    }
}