//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TD.i18n.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Currency.
        /// </summary>
        public static string AddCurrency {
            get {
                return ResourceManager.GetString("AddCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Entry Order.
        /// </summary>
        public static string AddEntryOrder {
            get {
                return ResourceManager.GetString("AddEntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Exchange.
        /// </summary>
        public static string AddExchange {
            get {
                return ResourceManager.GetString("AddExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add IUpdated At.
        /// </summary>
        public static string AddIUpdatedAt {
            get {
                return ResourceManager.GetString("AddIUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Currency.
        /// </summary>
        public static string AddNewCurrency {
            get {
                return ResourceManager.GetString("AddNewCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Entry Order.
        /// </summary>
        public static string AddNewEntryOrder {
            get {
                return ResourceManager.GetString("AddNewEntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Exchange.
        /// </summary>
        public static string AddNewExchange {
            get {
                return ResourceManager.GetString("AddNewExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New IUpdated At.
        /// </summary>
        public static string AddNewIUpdatedAt {
            get {
                return ResourceManager.GetString("AddNewIUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Stop Loss Order.
        /// </summary>
        public static string AddNewStopLossOrder {
            get {
                return ResourceManager.GetString("AddNewStopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Symbol.
        /// </summary>
        public static string AddNewSymbol {
            get {
                return ResourceManager.GetString("AddNewSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Take Profit Order.
        /// </summary>
        public static string AddNewTakeProfitOrder {
            get {
                return ResourceManager.GetString("AddNewTakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Trade.
        /// </summary>
        public static string AddNewTrade {
            get {
                return ResourceManager.GetString("AddNewTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Trade Image.
        /// </summary>
        public static string AddNewTradeImage {
            get {
                return ResourceManager.GetString("AddNewTradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Trading Account.
        /// </summary>
        public static string AddNewTradingAccount {
            get {
                return ResourceManager.GetString("AddNewTradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Currency.
        /// </summary>
        public static string AddRemoveCurrency {
            get {
                return ResourceManager.GetString("AddRemoveCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Entry Order.
        /// </summary>
        public static string AddRemoveEntryOrder {
            get {
                return ResourceManager.GetString("AddRemoveEntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Exchange.
        /// </summary>
        public static string AddRemoveExchange {
            get {
                return ResourceManager.GetString("AddRemoveExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove IUpdated At.
        /// </summary>
        public static string AddRemoveIUpdatedAt {
            get {
                return ResourceManager.GetString("AddRemoveIUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Stop Loss Order.
        /// </summary>
        public static string AddRemoveStopLossOrder {
            get {
                return ResourceManager.GetString("AddRemoveStopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Symbol.
        /// </summary>
        public static string AddRemoveSymbol {
            get {
                return ResourceManager.GetString("AddRemoveSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Take Profit Order.
        /// </summary>
        public static string AddRemoveTakeProfitOrder {
            get {
                return ResourceManager.GetString("AddRemoveTakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Trade.
        /// </summary>
        public static string AddRemoveTrade {
            get {
                return ResourceManager.GetString("AddRemoveTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Trade Image.
        /// </summary>
        public static string AddRemoveTradeImage {
            get {
                return ResourceManager.GetString("AddRemoveTradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Trading Account.
        /// </summary>
        public static string AddRemoveTradingAccount {
            get {
                return ResourceManager.GetString("AddRemoveTradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Stop Loss Order.
        /// </summary>
        public static string AddStopLossOrder {
            get {
                return ResourceManager.GetString("AddStopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Symbol.
        /// </summary>
        public static string AddSymbol {
            get {
                return ResourceManager.GetString("AddSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Take Profit Order.
        /// </summary>
        public static string AddTakeProfitOrder {
            get {
                return ResourceManager.GetString("AddTakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trade.
        /// </summary>
        public static string AddTrade {
            get {
                return ResourceManager.GetString("AddTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trade Image.
        /// </summary>
        public static string AddTradeImage {
            get {
                return ResourceManager.GetString("AddTradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trading Account.
        /// </summary>
        public static string AddTradingAccount {
            get {
                return ResourceManager.GetString("AddTradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency.
        /// </summary>
        public static string BaseCurrency {
            get {
                return ResourceManager.GetString("BaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        public static string Boolean {
            get {
                return ResourceManager.GetString("Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity.
        /// </summary>
        public static string Commodity {
            get {
                return ResourceManager.GetString("Commodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Currency.
        /// </summary>
        public static string CreateCurrency {
            get {
                return ResourceManager.GetString("CreateCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Entry Order.
        /// </summary>
        public static string CreateEntryOrder {
            get {
                return ResourceManager.GetString("CreateEntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Exchange.
        /// </summary>
        public static string CreateExchange {
            get {
                return ResourceManager.GetString("CreateExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create IUpdated At.
        /// </summary>
        public static string CreateIUpdatedAt {
            get {
                return ResourceManager.GetString("CreateIUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Stop Loss Order.
        /// </summary>
        public static string CreateStopLossOrder {
            get {
                return ResourceManager.GetString("CreateStopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Symbol.
        /// </summary>
        public static string CreateSymbol {
            get {
                return ResourceManager.GetString("CreateSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Take Profit Order.
        /// </summary>
        public static string CreateTakeProfitOrder {
            get {
                return ResourceManager.GetString("CreateTakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Trade.
        /// </summary>
        public static string CreateTrade {
            get {
                return ResourceManager.GetString("CreateTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Trade Image.
        /// </summary>
        public static string CreateTradeImage {
            get {
                return ResourceManager.GetString("CreateTradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Trading Account.
        /// </summary>
        public static string CreateTradingAccount {
            get {
                return ResourceManager.GetString("CreateTradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto.
        /// </summary>
        public static string Crypto {
            get {
                return ResourceManager.GetString("Crypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto Perpetual.
        /// </summary>
        public static string CryptoPerpetual {
            get {
                return ResourceManager.GetString("CryptoPerpetual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies List.
        /// </summary>
        public static string CurrenciesList {
            get {
                return ResourceManager.GetString("CurrenciesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Ticker.
        /// </summary>
        public static string CurrencyTicker {
            get {
                return ResourceManager.GetString("CurrencyTicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Array.
        /// </summary>
        public static string DateArray {
            get {
                return ResourceManager.GetString("DateArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time Array.
        /// </summary>
        public static string DateTimeArray {
            get {
                return ResourceManager.GetString("DateTimeArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        public static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Array.
        /// </summary>
        public static string DecimalArray {
            get {
                return ResourceManager.GetString("DecimalArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Currency.
        /// </summary>
        public static string DefaultCurrency {
            get {
                return ResourceManager.GetString("DefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Currency.
        /// </summary>
        public static string DeleteCurrency {
            get {
                return ResourceManager.GetString("DeleteCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Entry Order.
        /// </summary>
        public static string DeleteEntryOrder {
            get {
                return ResourceManager.GetString("DeleteEntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Exchange.
        /// </summary>
        public static string DeleteExchange {
            get {
                return ResourceManager.GetString("DeleteExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete IUpdated At.
        /// </summary>
        public static string DeleteIUpdatedAt {
            get {
                return ResourceManager.GetString("DeleteIUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Stop Loss Order.
        /// </summary>
        public static string DeleteStopLossOrder {
            get {
                return ResourceManager.GetString("DeleteStopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Symbol.
        /// </summary>
        public static string DeleteSymbol {
            get {
                return ResourceManager.GetString("DeleteSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Take Profit Order.
        /// </summary>
        public static string DeleteTakeProfitOrder {
            get {
                return ResourceManager.GetString("DeleteTakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Trade.
        /// </summary>
        public static string DeleteTrade {
            get {
                return ResourceManager.GetString("DeleteTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Trade Image.
        /// </summary>
        public static string DeleteTradeImage {
            get {
                return ResourceManager.GetString("DeleteTradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Trading Account.
        /// </summary>
        public static string DeleteTradingAccount {
            get {
                return ResourceManager.GetString("DeleteTradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Currency.
        /// </summary>
        public static string EditCurrency {
            get {
                return ResourceManager.GetString("EditCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Entry Order.
        /// </summary>
        public static string EditEntryOrder {
            get {
                return ResourceManager.GetString("EditEntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Exchange.
        /// </summary>
        public static string EditExchange {
            get {
                return ResourceManager.GetString("EditExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit IUpdated At.
        /// </summary>
        public static string EditIUpdatedAt {
            get {
                return ResourceManager.GetString("EditIUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Stop Loss Order.
        /// </summary>
        public static string EditStopLossOrder {
            get {
                return ResourceManager.GetString("EditStopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Symbol.
        /// </summary>
        public static string EditSymbol {
            get {
                return ResourceManager.GetString("EditSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Take Profit Order.
        /// </summary>
        public static string EditTakeProfitOrder {
            get {
                return ResourceManager.GetString("EditTakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trade.
        /// </summary>
        public static string EditTrade {
            get {
                return ResourceManager.GetString("EditTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trade Image.
        /// </summary>
        public static string EditTradeImage {
            get {
                return ResourceManager.GetString("EditTradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trading Account.
        /// </summary>
        public static string EditTradingAccount {
            get {
                return ResourceManager.GetString("EditTradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Method.
        /// </summary>
        public static string EntryMethod {
            get {
                return ResourceManager.GetString("EntryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Order.
        /// </summary>
        public static string EntryOrder {
            get {
                return ResourceManager.GetString("EntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Orders.
        /// </summary>
        public static string EntryOrders {
            get {
                return ResourceManager.GetString("EntryOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Orders List.
        /// </summary>
        public static string EntryOrdersList {
            get {
                return ResourceManager.GetString("EntryOrdersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Time.
        /// </summary>
        public static string EntryTime {
            get {
                return ResourceManager.GetString("EntryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Code.
        /// </summary>
        public static string ExchangeCode {
            get {
                return ResourceManager.GetString("ExchangeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Id.
        /// </summary>
        public static string ExchangeId {
            get {
                return ResourceManager.GetString("ExchangeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Name.
        /// </summary>
        public static string ExchangeName {
            get {
                return ResourceManager.GetString("ExchangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchanges.
        /// </summary>
        public static string Exchanges {
            get {
                return ResourceManager.GetString("Exchanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchanges List.
        /// </summary>
        public static string ExchangesList {
            get {
                return ResourceManager.GetString("ExchangesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed Entry Price.
        /// </summary>
        public static string ExecutedEntryPrice {
            get {
                return ResourceManager.GetString("ExecutedEntryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed Position Value.
        /// </summary>
        public static string ExecutedPositionValue {
            get {
                return ResourceManager.GetString("ExecutedPositionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed SL.
        /// </summary>
        public static string ExecutedSL {
            get {
                return ResourceManager.GetString("ExecutedSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed TP.
        /// </summary>
        public static string ExecutedTP {
            get {
                return ResourceManager.GetString("ExecutedTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Time.
        /// </summary>
        public static string ExecuteTime {
            get {
                return ResourceManager.GetString("ExecuteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled Price.
        /// </summary>
        public static string FilledPrice {
            get {
                return ResourceManager.GetString("FilledPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled Quantity.
        /// </summary>
        public static string FilledQuantity {
            get {
                return ResourceManager.GetString("FilledQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled Value.
        /// </summary>
        public static string FilledValue {
            get {
                return ResourceManager.GetString("FilledValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forex.
        /// </summary>
        public static string Forex {
            get {
                return ResourceManager.GetString("Forex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fund.
        /// </summary>
        public static string Fund {
            get {
                return ResourceManager.GetString("Fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Futures.
        /// </summary>
        public static string Futures {
            get {
                return ResourceManager.GetString("Futures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Any Symbol.
        /// </summary>
        public static string HasAnySymbol {
            get {
                return ResourceManager.GetString("HasAnySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Nr.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image URL.
        /// </summary>
        public static string ImageURL {
            get {
                return ResourceManager.GetString("ImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        public static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer Array.
        /// </summary>
        public static string IntegerArray {
            get {
                return ResourceManager.GetString("IntegerArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Fully Closed.
        /// </summary>
        public static string IsFullyClosed {
            get {
                return ResourceManager.GetString("IsFullyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IUpdated At.
        /// </summary>
        public static string IUpdatedAt {
            get {
                return ResourceManager.GetString("IUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IUpdated Ats.
        /// </summary>
        public static string IUpdatedAts {
            get {
                return ResourceManager.GetString("IUpdatedAts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IUpdated Ats List.
        /// </summary>
        public static string IUpdatedAtsList {
            get {
                return ResourceManager.GetString("IUpdatedAtsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        public static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Type.
        /// </summary>
        public static string MarketType {
            get {
                return ResourceManager.GetString("MarketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Result.
        /// </summary>
        public static string NetResult {
            get {
                return ResourceManager.GetString("NetResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Price.
        /// </summary>
        public static string OrderPrice {
            get {
                return ResourceManager.GetString("OrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Quantity.
        /// </summary>
        public static string OrderQuantity {
            get {
                return ResourceManager.GetString("OrderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        public static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Value.
        /// </summary>
        public static string OrderValue {
            get {
                return ResourceManager.GetString("OrderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Entry Price.
        /// </summary>
        public static string PlannedEntryPrice {
            get {
                return ResourceManager.GetString("PlannedEntryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Position Value.
        /// </summary>
        public static string PlannedPositionValue {
            get {
                return ResourceManager.GetString("PlannedPositionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Profit Loss.
        /// </summary>
        public static string PlannedProfitLoss {
            get {
                return ResourceManager.GetString("PlannedProfitLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Risk Amount.
        /// </summary>
        public static string PlannedRiskAmount {
            get {
                return ResourceManager.GetString("PlannedRiskAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned SL.
        /// </summary>
        public static string PlannedSL {
            get {
                return ResourceManager.GetString("PlannedSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned TP.
        /// </summary>
        public static string PlannedTP {
            get {
                return ResourceManager.GetString("PlannedTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Currency.
        /// </summary>
        public static string PriceCurrency {
            get {
                return ResourceManager.GetString("PriceCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Currency Id.
        /// </summary>
        public static string PriceCurrencyId {
            get {
                return ResourceManager.GetString("PriceCurrencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realized Profit Loss.
        /// </summary>
        public static string RealizedProfitLoss {
            get {
                return ResourceManager.GetString("RealizedProfitLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Currency.
        /// </summary>
        public static string RemoveCurrency {
            get {
                return ResourceManager.GetString("RemoveCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Entry Order.
        /// </summary>
        public static string RemoveEntryOrder {
            get {
                return ResourceManager.GetString("RemoveEntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Exchange.
        /// </summary>
        public static string RemoveExchange {
            get {
                return ResourceManager.GetString("RemoveExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove IUpdated At.
        /// </summary>
        public static string RemoveIUpdatedAt {
            get {
                return ResourceManager.GetString("RemoveIUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Stop Loss Order.
        /// </summary>
        public static string RemoveStopLossOrder {
            get {
                return ResourceManager.GetString("RemoveStopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Symbol.
        /// </summary>
        public static string RemoveSymbol {
            get {
                return ResourceManager.GetString("RemoveSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Take Profit Order.
        /// </summary>
        public static string RemoveTakeProfitOrder {
            get {
                return ResourceManager.GetString("RemoveTakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Trade.
        /// </summary>
        public static string RemoveTrade {
            get {
                return ResourceManager.GetString("RemoveTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Trade Image.
        /// </summary>
        public static string RemoveTradeImage {
            get {
                return ResourceManager.GetString("RemoveTradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Trading Account.
        /// </summary>
        public static string RemoveTradingAccount {
            get {
                return ResourceManager.GetString("RemoveTradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Types.
        /// </summary>
        public static string ReportTypes {
            get {
                return ResourceManager.GetString("ReportTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Type.
        /// </summary>
        public static string SettingType {
            get {
                return ResourceManager.GetString("SettingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop All.
        /// </summary>
        public static string StopAll {
            get {
                return ResourceManager.GetString("StopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Loss.
        /// </summary>
        public static string StopLoss {
            get {
                return ResourceManager.GetString("StopLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Loss Order.
        /// </summary>
        public static string StopLossOrder {
            get {
                return ResourceManager.GetString("StopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Loss Orders.
        /// </summary>
        public static string StopLossOrders {
            get {
                return ResourceManager.GetString("StopLossOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Loss Orders List.
        /// </summary>
        public static string StopLossOrdersList {
            get {
                return ResourceManager.GetString("StopLossOrdersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Array.
        /// </summary>
        public static string StringArray {
            get {
                return ResourceManager.GetString("StringArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol Id.
        /// </summary>
        public static string SymbolId {
            get {
                return ResourceManager.GetString("SymbolId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        public static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols List.
        /// </summary>
        public static string SymbolsList {
            get {
                return ResourceManager.GetString("SymbolsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Profit.
        /// </summary>
        public static string TakeProfit {
            get {
                return ResourceManager.GetString("TakeProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Profit Order.
        /// </summary>
        public static string TakeProfitOrder {
            get {
                return ResourceManager.GetString("TakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Profit Orders.
        /// </summary>
        public static string TakeProfitOrders {
            get {
                return ResourceManager.GetString("TakeProfitOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Profit Orders List.
        /// </summary>
        public static string TakeProfitOrdersList {
            get {
                return ResourceManager.GetString("TakeProfitOrdersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker.
        /// </summary>
        public static string Ticker {
            get {
                return ResourceManager.GetString("Ticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker Full.
        /// </summary>
        public static string TickerFull {
            get {
                return ResourceManager.GetString("TickerFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        public static string Trade {
            get {
                return ResourceManager.GetString("Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Direction.
        /// </summary>
        public static string TradeDirection {
            get {
                return ResourceManager.GetString("TradeDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade History.
        /// </summary>
        public static string TradeHistory {
            get {
                return ResourceManager.GetString("TradeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Id.
        /// </summary>
        public static string TradeId {
            get {
                return ResourceManager.GetString("TradeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Image.
        /// </summary>
        public static string TradeImage {
            get {
                return ResourceManager.GetString("TradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Images.
        /// </summary>
        public static string TradeImages {
            get {
                return ResourceManager.GetString("TradeImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Images List.
        /// </summary>
        public static string TradeImagesList {
            get {
                return ResourceManager.GetString("TradeImagesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades.
        /// </summary>
        public static string Trades {
            get {
                return ResourceManager.GetString("Trades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades List.
        /// </summary>
        public static string TradesList {
            get {
                return ResourceManager.GetString("TradesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Account.
        /// </summary>
        public static string TradingAccount {
            get {
                return ResourceManager.GetString("TradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Account Id.
        /// </summary>
        public static string TradingAccountId {
            get {
                return ResourceManager.GetString("TradingAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Accounts.
        /// </summary>
        public static string TradingAccounts {
            get {
                return ResourceManager.GetString("TradingAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Accounts List.
        /// </summary>
        public static string TradingAccountsList {
            get {
                return ResourceManager.GetString("TradingAccountsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated At.
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
    }
}
