using System.Collections.ObjectModel;
using TD.AppInfra.Services;
using TD.AppInfra.ViewModels;
using TD.Extensions;
using TD.Helpers;
using TD.Models;
using TD.RepositoryContracts;
using TD.SQLite;
using TD.WPF.Commands.Trades;
using TD.WPF.Services;
using static TD.Extensions.EnumExtension;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.ViewModels.Trades
{
    public partial class TradeListVM : AbstractCollectionVM<Trade>
    {
        public TradeListVM(ITradeRepository tradeRepository, IWindowDialogService windowDialogService,
                           ISymbolLookupService symbolLookupService, ITradingAccountLookupService tradingAccountLookupService)
        {
            TradeRepository = tradeRepository;
            Trades = new ObservableCollection<Trade>();

            TradeCreateCommand = new TradeCreateCommand (this, windowDialogService, symbolLookupService, tradingAccountLookupService);
            TradeDeleteCommand = new TradeDeleteCommand (this);
            TradeEditCommand = new TradeEditCommand (this, windowDialogService);
        }

        public ITradeRepository TradeRepository { get; }
        public ObservableCollection<Trade> Trades { get; }

        public TradeCreateCommand TradeCreateCommand { get; }
        public TradeDeleteCommand TradeDeleteCommand { get; }
        public TradeEditCommand TradeEditCommand { get; }

        public TradeQueryParameters? LastQueryParams { get; private set; }

        public async Task LoadTradesAsync()
        {
            await LoadTradesAsync(LastQueryParams ?? new TradeQueryParameters());
        }

        public async Task LoadTradesAsync(TradeQueryParameters queryParams)
        {
            if (LoadTradesInProgress)
                return;
            LoadTradesInProgress = true;
            var items = await TradeRepository.GetPagedAsync(queryParams);
            LastQueryParams = queryParams;
            ReplaceCollection(Trades, items);
            LoadTradesInProgress = false;
            OnTradesLoaded();
        }
        public bool LoadTradesInProgress { get; private set; } = false;
        protected virtual void OnTradesLoaded() { /* For override in derived classes */ }
        

        public async Task SaveTradeAsync(Trade trade)
        {
            if (trade.Id <= 0)
                trade.Id = await TradeRepository.CreateAsync(trade);
            else
                await TradeRepository.UpdateAsync(trade);
        }

        public Trade? SelectedTrade
        {
            get { return SelectedItem; }
            set
            {
                SelectedItem = value;
                RaisePropertyChanged(nameof(SelectedTrade));
            }
        }
    }
}
