using System.Collections.ObjectModel;
using TD.AppInfra.Services;
using TD.AppInfra.ViewModels;
using TD.Extensions;
using TD.Models;
using static TD.Extensions.EnumExtension;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.ViewModels.Trades
{
    public partial class TradeCreateVM : AbstractCreateEditVM
    {
        private readonly ISymbolLookupService _symbolLookupService;
        private readonly ITradingAccountLookupService _tradingAccountLookupService;
        private Trade _trade;
        public Trade Trade => _trade;

        public TradeCreateVM(ISymbolLookupService symbolLookupService, ITradingAccountLookupService tradingAccountLookupService)
        {
            _symbolLookupService = symbolLookupService;
            Symbols = new ObservableCollection<Symbol>();

            _tradingAccountLookupService = tradingAccountLookupService;
            TradingAccounts = new ObservableCollection<TradingAccount>();

            EntryMethodValues = GetValues<EntryMethod>();

            TradeDirectionValues = GetValues<TradeDirection>();

            _trade = new Trade();
            OnInitialized();
        }
        partial void OnInitialized();

        public ObservableCollection<Symbol> Symbols { get; }

        public async Task LoadSymbolsAsync()
        {
            var items = await _symbolLookupService.GetSymbolsAsync(isActive: true);
            Symbols.Clear();
            foreach (var item in items)
            {
                Symbols.Add(item);
            }
        }

        public ObservableCollection<TradingAccount> TradingAccounts { get; }

        public async Task LoadTradingAccountsAsync()
        {
            var items = await _tradingAccountLookupService.GetTradingAccountsAsync(isActive: true);
            TradingAccounts.Clear();
            foreach (var item in items)
            {
                TradingAccounts.Add(item);
            }
        }

        /// <summary>
        /// Gets the collection of available EntryMethod enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<EntryMethod>> EntryMethodValues { get; }

        /// <summary>
        /// Gets the collection of available TradeDirection enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<TradeDirection>> TradeDirectionValues { get; }

        public int TradingAccountId
        {
            get { return _trade.TradingAccountId; }
            set
            {
                if (_trade.TradingAccountId != value)
                {
                    _trade.TradingAccountId = value;
                    RaisePropertyChanged(nameof(TradingAccountId));
                    ValidateProperty(_trade, nameof(TradingAccountId));
                }
            }
        }

        public TradingAccount TradingAccount
        {
            get { return _trade.TradingAccount; }
            set
            {
                if (_trade.TradingAccount != value)
                {
                    _trade.TradingAccount = value;
                    RaisePropertyChanged(nameof(TradingAccount));
                    ValidateProperty(_trade, nameof(TradingAccount));
                }
            }
        }

        public int SymbolId
        {
            get { return _trade.SymbolId; }
            set
            {
                if (_trade.SymbolId != value)
                {
                    _trade.SymbolId = value;
                    RaisePropertyChanged(nameof(SymbolId));
                    ValidateProperty(_trade, nameof(SymbolId));
                }
            }
        }

        public Symbol Symbol
        {
            get { return _trade.Symbol; }
            set
            {
                if (_trade.Symbol != value)
                {
                    _trade.Symbol = value;
                    RaisePropertyChanged(nameof(Symbol));
                    ValidateProperty(_trade, nameof(Symbol));
                }
            }
        }

        public DateTime? EntryTime
        {
            get { return _trade.EntryTime; }
            set
            {
                if (_trade.EntryTime != value)
                {
                    _trade.EntryTime = value;
                    RaisePropertyChanged(nameof(EntryTime));
                    ValidateProperty(_trade, nameof(EntryTime));
                }
            }
        }

        public EntryMethod EntryMethod
        {
            get { return _trade.EntryMethod; }
            set
            {
                if (_trade.EntryMethod != value)
                {
                    _trade.EntryMethod = value;
                    RaisePropertyChanged(nameof(EntryMethod));
                    ValidateProperty(_trade, nameof(EntryMethod));
                }
            }
        }

        public TradeDirection TradeDirection
        {
            get { return _trade.TradeDirection; }
            set
            {
                if (_trade.TradeDirection != value)
                {
                    _trade.TradeDirection = value;
                    RaisePropertyChanged(nameof(TradeDirection));
                    ValidateProperty(_trade, nameof(TradeDirection));
                }
            }
        }

        public bool IsFullyClosed
        {
            get { return _trade.IsFullyClosed; }
            set
            {
                if (_trade.IsFullyClosed != value)
                {
                    _trade.IsFullyClosed = value;
                    RaisePropertyChanged(nameof(IsFullyClosed));
                    ValidateProperty(_trade, nameof(IsFullyClosed));
                }
            }
        }

        public decimal? OrderQuantity
        {
            get { return _trade.OrderQuantity; }
            set
            {
                if (_trade.OrderQuantity != value)
                {
                    _trade.OrderQuantity = value;
                    RaisePropertyChanged(nameof(OrderQuantity));
                    ValidateProperty(_trade, nameof(OrderQuantity));
                }
            }
        }

        public decimal? FilledQuantity
        {
            get { return _trade.FilledQuantity; }
            set
            {
                if (_trade.FilledQuantity != value)
                {
                    _trade.FilledQuantity = value;
                    RaisePropertyChanged(nameof(FilledQuantity));
                    ValidateProperty(_trade, nameof(FilledQuantity));
                }
            }
        }

        public decimal? PlannedEntryPrice
        {
            get { return _trade.PlannedEntryPrice; }
            set
            {
                if (_trade.PlannedEntryPrice != value)
                {
                    _trade.PlannedEntryPrice = value;
                    RaisePropertyChanged(nameof(PlannedEntryPrice));
                    ValidateProperty(_trade, nameof(PlannedEntryPrice));
                }
            }
        }

        public decimal? ExecutedEntryPrice
        {
            get { return _trade.ExecutedEntryPrice; }
            set
            {
                if (_trade.ExecutedEntryPrice != value)
                {
                    _trade.ExecutedEntryPrice = value;
                    RaisePropertyChanged(nameof(ExecutedEntryPrice));
                    ValidateProperty(_trade, nameof(ExecutedEntryPrice));
                }
            }
        }

        public decimal? PlannedPositionValue
        {
            get { return _trade.PlannedPositionValue; }
            set
            {
                if (_trade.PlannedPositionValue != value)
                {
                    _trade.PlannedPositionValue = value;
                    RaisePropertyChanged(nameof(PlannedPositionValue));
                    ValidateProperty(_trade, nameof(PlannedPositionValue));
                }
            }
        }

        public decimal? ExecutedPositionValue
        {
            get { return _trade.ExecutedPositionValue; }
            set
            {
                if (_trade.ExecutedPositionValue != value)
                {
                    _trade.ExecutedPositionValue = value;
                    RaisePropertyChanged(nameof(ExecutedPositionValue));
                    ValidateProperty(_trade, nameof(ExecutedPositionValue));
                }
            }
        }

        public decimal? PlannedProfitLoss
        {
            get { return _trade.PlannedProfitLoss; }
            set
            {
                if (_trade.PlannedProfitLoss != value)
                {
                    _trade.PlannedProfitLoss = value;
                    RaisePropertyChanged(nameof(PlannedProfitLoss));
                    ValidateProperty(_trade, nameof(PlannedProfitLoss));
                }
            }
        }

        public decimal? RealizedProfitLoss
        {
            get { return _trade.RealizedProfitLoss; }
            set
            {
                if (_trade.RealizedProfitLoss != value)
                {
                    _trade.RealizedProfitLoss = value;
                    RaisePropertyChanged(nameof(RealizedProfitLoss));
                    ValidateProperty(_trade, nameof(RealizedProfitLoss));
                }
            }
        }

        public decimal? PlannedTP
        {
            get { return _trade.PlannedTP; }
            set
            {
                if (_trade.PlannedTP != value)
                {
                    _trade.PlannedTP = value;
                    RaisePropertyChanged(nameof(PlannedTP));
                    ValidateProperty(_trade, nameof(PlannedTP));
                }
            }
        }

        public decimal? ExecutedTP
        {
            get { return _trade.ExecutedTP; }
            set
            {
                if (_trade.ExecutedTP != value)
                {
                    _trade.ExecutedTP = value;
                    RaisePropertyChanged(nameof(ExecutedTP));
                    ValidateProperty(_trade, nameof(ExecutedTP));
                }
            }
        }

        public decimal? PlannedRiskAmount
        {
            get { return _trade.PlannedRiskAmount; }
            set
            {
                if (_trade.PlannedRiskAmount != value)
                {
                    _trade.PlannedRiskAmount = value;
                    RaisePropertyChanged(nameof(PlannedRiskAmount));
                    ValidateProperty(_trade, nameof(PlannedRiskAmount));
                }
            }
        }

        public decimal? PlannedSL
        {
            get { return _trade.PlannedSL; }
            set
            {
                if (_trade.PlannedSL != value)
                {
                    _trade.PlannedSL = value;
                    RaisePropertyChanged(nameof(PlannedSL));
                    ValidateProperty(_trade, nameof(PlannedSL));
                }
            }
        }

        public decimal? ExecutedSL
        {
            get { return _trade.ExecutedSL; }
            set
            {
                if (_trade.ExecutedSL != value)
                {
                    _trade.ExecutedSL = value;
                    RaisePropertyChanged(nameof(ExecutedSL));
                    ValidateProperty(_trade, nameof(ExecutedSL));
                }
            }
        }

        public DateTime UpdatedAt
        {
            get { return _trade.UpdatedAt; }
            set
            {
                if (_trade.UpdatedAt != value)
                {
                    _trade.UpdatedAt = value;
                    RaisePropertyChanged(nameof(UpdatedAt));
                    ValidateProperty(_trade, nameof(UpdatedAt));
                }
            }
        }

        public bool ValidateModel()
        {
            return ValidateModel(_trade);
        }
    }
}
