using TD.AppInfra.ViewModels;
using TD.Extensions;
using TD.Models;
using static TD.Extensions.EnumExtension;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.ViewModels.Trades
{
    public partial class TradeEditVM : AbstractCreateEditVM
    {
        private Trade _trade;
        public Trade Trade => _trade;

        public TradeEditVM(Trade trade)
        {
            _trade = trade;
            TradeDirectionValues = GetValues<TradeDirection>();
            EntryMethodValues = GetValues<EntryMethod>();
            MarketTypeValues = GetValues<MarketType>();
            OnInitialized();
        }
        partial void OnInitialized();

        /// <summary>
        /// Gets the collection of available TradeDirection enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<TradeDirection>> TradeDirectionValues { get; }

        /// <summary>
        /// Gets the collection of available EntryMethod enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<EntryMethod>> EntryMethodValues { get; }

        /// <summary>
        /// Gets the collection of available MarketType enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<MarketType>> MarketTypeValues { get; }

        public int TradingAccountId => _trade.TradingAccountId;

        public TradingAccount TradingAccount
        {
            get { return _trade.TradingAccount; }
            set
            {
                if (_trade.TradingAccount != value)
                {
                    _trade.TradingAccount = value;
                    RaisePropertyChanged(nameof(TradingAccount));
                    ValidateProperty(_trade, nameof(TradingAccount));
                }
            }
        }

        public int SymbolId => _trade.SymbolId;

        public Symbol Symbol => _trade.Symbol;

        public TradeDirection TradeDirection => _trade.TradeDirection;

        public EntryMethod EntryMethod
        {
            get { return _trade.EntryMethod; }
            set
            {
                if (_trade.EntryMethod != value)
                {
                    _trade.EntryMethod = value;
                    RaisePropertyChanged(nameof(EntryMethod));
                    ValidateProperty(_trade, nameof(EntryMethod));
                }
            }
        }

        public string? Tags
        {
            get { return _trade.Tags; }
            set
            {
                if (!string.IsNullOrWhiteSpace(value) && _trade.Tags != value)
                {
                    _trade.Tags = value;
                    RaisePropertyChanged(nameof(Tags));
                    ValidateProperty(_trade, nameof(Tags));
                }
                else if (string.IsNullOrWhiteSpace(value))
                {
                    _trade.Tags = null;
                    RaisePropertyChanged(nameof(Tags));
                    ValidateProperty(_trade, nameof(Tags));
                }
            }
        }

        public MarketType MarketType
        {
            get { return _trade.MarketType; }
            set
            {
                if (_trade.MarketType != value)
                {
                    _trade.MarketType = value;
                    RaisePropertyChanged(nameof(MarketType));
                    ValidateProperty(_trade, nameof(MarketType));
                }
            }
        }

        public DateTime? EntryTime
        {
            get { return _trade.EntryTime; }
            set
            {
                if (_trade.EntryTime != value)
                {
                    _trade.EntryTime = value;
                    RaisePropertyChanged(nameof(EntryTime));
                    ValidateProperty(_trade, nameof(EntryTime));
                }
            }
        }

        public DateTime? ExitTime
        {
            get { return _trade.ExitTime; }
            set
            {
                if (_trade.ExitTime != value)
                {
                    _trade.ExitTime = value;
                    RaisePropertyChanged(nameof(ExitTime));
                    ValidateProperty(_trade, nameof(ExitTime));
                }
            }
        }

        public decimal? PlannedPositionValue => _trade.PlannedPositionValue;

        public decimal? ExecutedPositionValue => _trade.ExecutedPositionValue;

        public decimal? PlannedEntryPrice
        {
            get { return _trade.PlannedEntryPrice; }
            set
            {
                if (_trade.PlannedEntryPrice != value)
                {
                    _trade.PlannedEntryPrice = value;
                    RaisePropertyChanged(nameof(PlannedEntryPrice));
                    ValidateProperty(_trade, nameof(PlannedEntryPrice));
                }
            }
        }

        public decimal? ExecutedEntryPrice
        {
            get { return _trade.ExecutedEntryPrice; }
            set
            {
                if (_trade.ExecutedEntryPrice != value)
                {
                    _trade.ExecutedEntryPrice = value;
                    RaisePropertyChanged(nameof(ExecutedEntryPrice));
                    ValidateProperty(_trade, nameof(ExecutedEntryPrice));
                }
            }
        }

        public decimal? OrderQuantity
        {
            get { return _trade.OrderQuantity; }
            set
            {
                if (_trade.OrderQuantity != value)
                {
                    _trade.OrderQuantity = value;
                    RaisePropertyChanged(nameof(OrderQuantity));
                    ValidateProperty(_trade, nameof(OrderQuantity));
                }
            }
        }

        public decimal? FilledQuantity
        {
            get { return _trade.FilledQuantity; }
            set
            {
                if (_trade.FilledQuantity != value)
                {
                    _trade.FilledQuantity = value;
                    RaisePropertyChanged(nameof(FilledQuantity));
                    ValidateProperty(_trade, nameof(FilledQuantity));
                }
            }
        }

        public decimal? RemainingPositionValue => _trade.RemainingPositionValue;

        public decimal? PlannedTP
        {
            get { return _trade.PlannedTP; }
            set
            {
                if (_trade.PlannedTP != value)
                {
                    _trade.PlannedTP = value;
                    RaisePropertyChanged(nameof(PlannedTP));
                    ValidateProperty(_trade, nameof(PlannedTP));
                }
            }
        }

        public decimal? ExecutedTP
        {
            get { return _trade.ExecutedTP; }
            set
            {
                if (_trade.ExecutedTP != value)
                {
                    _trade.ExecutedTP = value;
                    RaisePropertyChanged(nameof(ExecutedTP));
                    ValidateProperty(_trade, nameof(ExecutedTP));
                }
            }
        }

        public decimal? PlannedSL
        {
            get { return _trade.PlannedSL; }
            set
            {
                if (_trade.PlannedSL != value)
                {
                    _trade.PlannedSL = value;
                    RaisePropertyChanged(nameof(PlannedSL));
                    ValidateProperty(_trade, nameof(PlannedSL));
                }
            }
        }

        public decimal? ExecutedSL
        {
            get { return _trade.ExecutedSL; }
            set
            {
                if (_trade.ExecutedSL != value)
                {
                    _trade.ExecutedSL = value;
                    RaisePropertyChanged(nameof(ExecutedSL));
                    ValidateProperty(_trade, nameof(ExecutedSL));
                }
            }
        }

        public string? SetupNotes => _trade.SetupNotes;

        public bool ValidateModel()
        {
            return ValidateModel(_trade);
        }
    }
}
