//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency : IId, IDisplayOrder, IIsActive
    {
        public int Id { get; set; }
        public string CurrencyTicker { get; set; }
        public string Description { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        /// <summary>
        /// Clones all properties in a new Currency instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New Currency instance</returns>
        public Currency Clone()
        {
            var clone = new Currency();
            clone.CurrencyTicker = CurrencyTicker;
            clone.Description = Description;
            clone.DisplayOrder = DisplayOrder;
            clone.IsActive = IsActive;
    
            Cloning(clone);
    
            return clone;
        }
    
        // Use below function in a partial class file (eg. Currency.part.cs)
        // to add more complexity to clone
        partial void Cloning(Currency clone);
    }
    
    //Data Transfer Object type for Currency
    public partial class CurrencyDTO : IId, IDisplayOrder, IIsActive
    {
        public CurrencyDTO() { }
    
        public CurrencyDTO(Currency entity)
        {
            Id = entity.Id;
            CurrencyTicker = entity.CurrencyTicker;
            Description = entity.Description;
            DisplayOrder = entity.DisplayOrder;
            IsActive = entity.IsActive;
        
            Initilazing(entity);
        }
    
        partial void Initilazing(Currency entity);
        
        public virtual Currency ToCurrency()
        {
            var entity = new Currency();
            entity.Id = Id;
            entity.CurrencyTicker = CurrencyTicker;
            entity.Description = Description;
            entity.DisplayOrder = DisplayOrder;
            entity.IsActive = IsActive;
    
            Converting(entity);
    
            return entity;
        }
    
        partial void Converting(Currency entity);
      
        public int Id { get; set; }
        public string CurrencyTicker { get; set; }
        public string Description { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
    }
}
