
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD.Data
{
    using System;
    using System.Collections.Generic;
    
    
    public interface IId
    {
        int Id { get; set; }
    }
    
    public interface IDisplayOrder
    {
        int DisplayOrder { get; set; }
    }
    
    public interface IModifyDate
    {
        System.DateTime ModifyDate { get; set; }
    }
    
    public interface IIsActive
    {
        bool IsActive { get; set; }
    }
}
