//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange : IId, IDisplayOrder, IIsActive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exchange()
        {
            this.Symbols = new HashSet<Symbol>();
            this.TradingAccounts = new HashSet<TradingAccount>();
        }
    
        public int Id { get; set; }
        public string ExchangeName { get; set; }
        public string ExchangeCode { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Symbol> Symbols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradingAccount> TradingAccounts { get; set; }
        /// <summary>
        /// Clones all properties in a new Exchange instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New Exchange instance</returns>
        public Exchange Clone()
        {
            var clone = new Exchange();
            clone.ExchangeName = ExchangeName;
            clone.ExchangeCode = ExchangeCode;
            clone.DisplayOrder = DisplayOrder;
            clone.IsActive = IsActive;
    
            Cloning(clone);
    
            return clone;
        }
    
        // Use below function in a partial class file (eg. Exchange.part.cs)
        // to add more complexity to clone
        partial void Cloning(Exchange clone);
    }
    
    //Data Transfer Object type for Exchange
    public partial class ExchangeDTO : IId, IDisplayOrder, IIsActive
    {
        public ExchangeDTO() { }
    
        public ExchangeDTO(Exchange entity)
        {
            Id = entity.Id;
            ExchangeName = entity.ExchangeName;
            ExchangeCode = entity.ExchangeCode;
            DisplayOrder = entity.DisplayOrder;
            IsActive = entity.IsActive;
        
            Initilazing(entity);
        }
    
        partial void Initilazing(Exchange entity);
        
        public virtual Exchange ToExchange()
        {
            var entity = new Exchange();
            entity.Id = Id;
            entity.ExchangeName = ExchangeName;
            entity.ExchangeCode = ExchangeCode;
            entity.DisplayOrder = DisplayOrder;
            entity.IsActive = IsActive;
    
            Converting(entity);
    
            return entity;
        }
    
        partial void Converting(Exchange entity);
      
        public int Id { get; set; }
        public string ExchangeName { get; set; }
        public string ExchangeCode { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
    }
}
