//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symbol : IId, IDisplayOrder, IIsActive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Symbol()
        {
            this.Trades = new HashSet<Trade>();
        }
    
        public int Id { get; set; }
        public string Ticker { get; set; }
        public string TickerFull { get; set; }
        public string BaseCurrency { get; set; }
        public string PriceCurrency { get; set; }
        public string Description { get; set; }
        public int ExchangeId { get; set; }
        public int MarketType { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Exchange Exchanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trade> Trades { get; set; }
        /// <summary>
        /// Clones all properties in a new Symbol instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New Symbol instance</returns>
        public Symbol Clone()
        {
            var clone = new Symbol();
            clone.Ticker = Ticker;
            clone.TickerFull = TickerFull;
            clone.BaseCurrency = BaseCurrency;
            clone.PriceCurrency = PriceCurrency;
            clone.Description = Description;
            clone.ExchangeId = ExchangeId;
            clone.MarketType = MarketType;
            clone.DisplayOrder = DisplayOrder;
            clone.IsActive = IsActive;
    
            Cloning(clone);
    
            return clone;
        }
    
        // Use below function in a partial class file (eg. Symbol.part.cs)
        // to add more complexity to clone
        partial void Cloning(Symbol clone);
    }
    
    //Data Transfer Object type for Symbol
    public partial class SymbolDTO : IId, IDisplayOrder, IIsActive
    {
        public SymbolDTO() { }
    
        public SymbolDTO(Symbol entity)
        {
            Id = entity.Id;
            Ticker = entity.Ticker;
            TickerFull = entity.TickerFull;
            BaseCurrency = entity.BaseCurrency;
            PriceCurrency = entity.PriceCurrency;
            Description = entity.Description;
            ExchangeId = entity.ExchangeId;
            MarketType = entity.MarketType;
            DisplayOrder = entity.DisplayOrder;
            IsActive = entity.IsActive;
        
            Initilazing(entity);
        }
    
        partial void Initilazing(Symbol entity);
        
        public virtual Symbol ToSymbol()
        {
            var entity = new Symbol();
            entity.Id = Id;
            entity.Ticker = Ticker;
            entity.TickerFull = TickerFull;
            entity.BaseCurrency = BaseCurrency;
            entity.PriceCurrency = PriceCurrency;
            entity.Description = Description;
            entity.ExchangeId = ExchangeId;
            entity.MarketType = MarketType;
            entity.DisplayOrder = DisplayOrder;
            entity.IsActive = IsActive;
    
            Converting(entity);
    
            return entity;
        }
    
        partial void Converting(Symbol entity);
      
        public int Id { get; set; }
        public string Ticker { get; set; }
        public string TickerFull { get; set; }
        public string BaseCurrency { get; set; }
        public string PriceCurrency { get; set; }
        public string Description { get; set; }
        public int ExchangeId { get; set; }
        public int MarketType { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
    }
}
