//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakeProfitOrder : IId, IDisplayOrder
    {
        public int Id { get; set; }
        public int TradeId { get; set; }
        public Nullable<System.DateTime> ExecuteTime { get; set; }
        public decimal OrderPrice { get; set; }
        public Nullable<decimal> FilledPrice { get; set; }
        public Nullable<decimal> OrderQuantity { get; set; }
        public Nullable<decimal> FilledQuantity { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public Nullable<decimal> FilledAmount { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual Trade Trade { get; set; }
        /// <summary>
        /// Clones all properties in a new TakeProfitOrder instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New TakeProfitOrder instance</returns>
        public TakeProfitOrder Clone()
        {
            var clone = new TakeProfitOrder();
            clone.TradeId = TradeId;
            clone.ExecuteTime = ExecuteTime;
            clone.OrderPrice = OrderPrice;
            clone.FilledPrice = FilledPrice;
            clone.OrderQuantity = OrderQuantity;
            clone.FilledQuantity = FilledQuantity;
            clone.OrderAmount = OrderAmount;
            clone.FilledAmount = FilledAmount;
            clone.DisplayOrder = DisplayOrder;
    
            Cloning(clone);
    
            return clone;
        }
    
        // Use below function in a partial class file (eg. TakeProfitOrder.part.cs)
        // to add more complexity to clone
        partial void Cloning(TakeProfitOrder clone);
    }
    
    //Data Transfer Object type for TakeProfitOrder
    public partial class TakeProfitOrderDTO : IId, IDisplayOrder
    {
        public TakeProfitOrderDTO() { }
    
        public TakeProfitOrderDTO(TakeProfitOrder entity)
        {
            Id = entity.Id;
            TradeId = entity.TradeId;
            ExecuteTime = entity.ExecuteTime;
            OrderPrice = entity.OrderPrice;
            FilledPrice = entity.FilledPrice;
            OrderQuantity = entity.OrderQuantity;
            FilledQuantity = entity.FilledQuantity;
            OrderAmount = entity.OrderAmount;
            FilledAmount = entity.FilledAmount;
            DisplayOrder = entity.DisplayOrder;
        
            Initilazing(entity);
        }
    
        partial void Initilazing(TakeProfitOrder entity);
        
        public virtual TakeProfitOrder ToTakeProfitOrder()
        {
            var entity = new TakeProfitOrder();
            entity.Id = Id;
            entity.TradeId = TradeId;
            entity.ExecuteTime = ExecuteTime;
            entity.OrderPrice = OrderPrice;
            entity.FilledPrice = FilledPrice;
            entity.OrderQuantity = OrderQuantity;
            entity.FilledQuantity = FilledQuantity;
            entity.OrderAmount = OrderAmount;
            entity.FilledAmount = FilledAmount;
            entity.DisplayOrder = DisplayOrder;
    
            Converting(entity);
    
            return entity;
        }
    
        partial void Converting(TakeProfitOrder entity);
      
        public int Id { get; set; }
        public int TradeId { get; set; }
        public Nullable<System.DateTime> ExecuteTime { get; set; }
        public decimal OrderPrice { get; set; }
        public Nullable<decimal> FilledPrice { get; set; }
        public Nullable<decimal> OrderQuantity { get; set; }
        public Nullable<decimal> FilledQuantity { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public Nullable<decimal> FilledAmount { get; set; }
        public int DisplayOrder { get; set; }
    }
}
