//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade : IId, IModifyDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trade()
        {
            this.EntryOrders = new HashSet<EntryOrder>();
            this.StopLossOrders = new HashSet<StopLossOrder>();
            this.TakeProfitOrders = new HashSet<TakeProfitOrder>();
            this.TradePlans = new HashSet<TradePlan>();
        }
    
        public int Id { get; set; }
        public int TradingAccountId { get; set; }
        public int SymbolId { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public int EntryMethod { get; set; }
        public int TradeDirection { get; set; }
        public Nullable<decimal> PlannedEntry { get; set; }
        public Nullable<decimal> ExecutedEntry { get; set; }
        public Nullable<decimal> PlannedTP { get; set; }
        public Nullable<decimal> ExecutedTP { get; set; }
        public Nullable<decimal> PlannedSL { get; set; }
        public Nullable<decimal> ExecutedSL { get; set; }
        public System.DateTime ModifyDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntryOrder> EntryOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StopLossOrder> StopLossOrders { get; set; }
        public virtual Symbol Symbol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakeProfitOrder> TakeProfitOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradePlan> TradePlans { get; set; }
        public virtual TradingAccount TradingAccount { get; set; }
        /// <summary>
        /// Clones all properties in a new Trade instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New Trade instance</returns>
        public Trade Clone()
        {
            var clone = new Trade();
            clone.TradingAccountId = TradingAccountId;
            clone.SymbolId = SymbolId;
            clone.EntryTime = EntryTime;
            clone.EntryMethod = EntryMethod;
            clone.TradeDirection = TradeDirection;
            clone.PlannedEntry = PlannedEntry;
            clone.ExecutedEntry = ExecutedEntry;
            clone.PlannedTP = PlannedTP;
            clone.ExecutedTP = ExecutedTP;
            clone.PlannedSL = PlannedSL;
            clone.ExecutedSL = ExecutedSL;
            clone.ModifyDate = ModifyDate;
    
            Cloning(clone);
    
            return clone;
        }
    
        // Use below function in a partial class file (eg. Trade.part.cs)
        // to add more complexity to clone
        partial void Cloning(Trade clone);
    }
    
    //Data Transfer Object type for Trade
    public partial class TradeDTO : IId, IModifyDate
    {
        public TradeDTO() { }
    
        public TradeDTO(Trade entity)
        {
            Id = entity.Id;
            TradingAccountId = entity.TradingAccountId;
            SymbolId = entity.SymbolId;
            EntryTime = entity.EntryTime;
            EntryMethod = entity.EntryMethod;
            TradeDirection = entity.TradeDirection;
            PlannedEntry = entity.PlannedEntry;
            ExecutedEntry = entity.ExecutedEntry;
            PlannedTP = entity.PlannedTP;
            ExecutedTP = entity.ExecutedTP;
            PlannedSL = entity.PlannedSL;
            ExecutedSL = entity.ExecutedSL;
            ModifyDate = entity.ModifyDate;
        
            Initilazing(entity);
        }
    
        partial void Initilazing(Trade entity);
        
        public virtual Trade ToTrade()
        {
            var entity = new Trade();
            entity.Id = Id;
            entity.TradingAccountId = TradingAccountId;
            entity.SymbolId = SymbolId;
            entity.EntryTime = EntryTime;
            entity.EntryMethod = EntryMethod;
            entity.TradeDirection = TradeDirection;
            entity.PlannedEntry = PlannedEntry;
            entity.ExecutedEntry = ExecutedEntry;
            entity.PlannedTP = PlannedTP;
            entity.ExecutedTP = ExecutedTP;
            entity.PlannedSL = PlannedSL;
            entity.ExecutedSL = ExecutedSL;
            entity.ModifyDate = ModifyDate;
    
            Converting(entity);
    
            return entity;
        }
    
        partial void Converting(Trade entity);
      
        public int Id { get; set; }
        public int TradingAccountId { get; set; }
        public int SymbolId { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public int EntryMethod { get; set; }
        public int TradeDirection { get; set; }
        public Nullable<decimal> PlannedEntry { get; set; }
        public Nullable<decimal> ExecutedEntry { get; set; }
        public Nullable<decimal> PlannedTP { get; set; }
        public Nullable<decimal> ExecutedTP { get; set; }
        public Nullable<decimal> PlannedSL { get; set; }
        public Nullable<decimal> ExecutedSL { get; set; }
        public System.DateTime ModifyDate { get; set; }
    }
}
