//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradePlan : IId, IModifyDate
    {
        public int Id { get; set; }
        public int TradeId { get; set; }
        public string ImageURL { get; set; }
        public string Notes { get; set; }
        public System.DateTime ModifyDate { get; set; }
    
        public virtual Trade Trade { get; set; }
        /// <summary>
        /// Clones all properties in a new TradePlan instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New TradePlan instance</returns>
        public TradePlan Clone()
        {
            var clone = new TradePlan();
            clone.TradeId = TradeId;
            clone.ImageURL = ImageURL;
            clone.Notes = Notes;
            clone.ModifyDate = ModifyDate;
    
            Cloning(clone);
    
            return clone;
        }
    
        // Use below function in a partial class file (eg. TradePlan.part.cs)
        // to add more complexity to clone
        partial void Cloning(TradePlan clone);
    }
    
    //Data Transfer Object type for TradePlan
    public partial class TradePlanDTO : IId, IModifyDate
    {
        public TradePlanDTO() { }
    
        public TradePlanDTO(TradePlan entity)
        {
            Id = entity.Id;
            TradeId = entity.TradeId;
            ImageURL = entity.ImageURL;
            Notes = entity.Notes;
            ModifyDate = entity.ModifyDate;
        
            Initilazing(entity);
        }
    
        partial void Initilazing(TradePlan entity);
        
        public virtual TradePlan ToTradePlan()
        {
            var entity = new TradePlan();
            entity.Id = Id;
            entity.TradeId = TradeId;
            entity.ImageURL = ImageURL;
            entity.Notes = Notes;
            entity.ModifyDate = ModifyDate;
    
            Converting(entity);
    
            return entity;
        }
    
        partial void Converting(TradePlan entity);
      
        public int Id { get; set; }
        public int TradeId { get; set; }
        public string ImageURL { get; set; }
        public string Notes { get; set; }
        public System.DateTime ModifyDate { get; set; }
    }
}
