//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.Validation
{
	public partial class QueryParameters
	{
		public QueryParameters()
		{
			Page = 1;
			PageSize = 20;
		}

		public int Page { get; set; }
		public int PageSize { get; set; }
		public string? SearchString { get; set; }

		public int PageCount
		{
			get
			{
				return TotalCount > 0 ? (int)Math.Ceiling(TotalCount / (double)PageSize) : 0;
			}
		}

		public int Skip
		{
			get { return (Page - 1) * PageSize; }
		}

		public int TotalCount
		{
			get { return _totalCount; }
			set
			{
				_totalCount = value;
				if (Page < 1) Page = 1;
				if (Page > PageCount) Page = PageCount;
				int skip = (Page - 1) * PageSize;
			}
		}
		int _totalCount;
	}
}
