//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using TD.Models;

namespace TD.Helpers
{
    /// <summary>
    /// Represents the query parameters for the Trade entity.
    /// </summary>
    public partial class TradeQueryParameters : QueryParameters
    {
        public TradeQueryParameters() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="TradeQueryParameters"/> class based on the specified query parameters.
        /// </summary>
        /// <param name="queryParameters">The query parameters to copy values from.</param>
        public TradeQueryParameters(TradeQueryParameters queryParameters) : base(queryParameters)
        {
            if (queryParameters != null && queryParameters is TradeQueryParameters tradeQueryParams)
            {
                TradingAccountId = tradeQueryParams.TradingAccountId;
                SymbolId = tradeQueryParams.SymbolId;
                TradeDirection = tradeQueryParams.TradeDirection;
                EntryTimeMin = tradeQueryParams.EntryTimeMin;
                EntryTimeMax = tradeQueryParams.EntryTimeMax;
                PlannedPositionValueMin = tradeQueryParams.PlannedPositionValueMin;
                PlannedPositionValueMax = tradeQueryParams.PlannedPositionValueMax;
                ExecutedPositionValueMin = tradeQueryParams.ExecutedPositionValueMin;
                ExecutedPositionValueMax = tradeQueryParams.ExecutedPositionValueMax;
                PlannedProfitLossMin = tradeQueryParams.PlannedProfitLossMin;
                PlannedProfitLossMax = tradeQueryParams.PlannedProfitLossMax;
                RealizedProfitLossMin = tradeQueryParams.RealizedProfitLossMin;
                RealizedProfitLossMax = tradeQueryParams.RealizedProfitLossMax;
                PlannedRiskAmountMin = tradeQueryParams.PlannedRiskAmountMin;
                PlannedRiskAmountMax = tradeQueryParams.PlannedRiskAmountMax;
                UpdatedAtMin = tradeQueryParams.UpdatedAtMin;
                UpdatedAtMax = tradeQueryParams.UpdatedAtMax;
            }
        }

        public int? TradingAccountId { get; set; }
        public int? SymbolId { get; set; }
        public TradeDirection? TradeDirection { get; set; }
        public DateTime? EntryTimeMin { get; set; }
        public DateTime? EntryTimeMax { get; set; }
        public decimal? PlannedPositionValueMin { get; set; }
        public decimal? PlannedPositionValueMax { get; set; }
        public decimal? ExecutedPositionValueMin { get; set; }
        public decimal? ExecutedPositionValueMax { get; set; }
        public decimal? PlannedProfitLossMin { get; set; }
        public decimal? PlannedProfitLossMax { get; set; }
        public decimal? RealizedProfitLossMin { get; set; }
        public decimal? RealizedProfitLossMax { get; set; }
        public decimal? PlannedRiskAmountMin { get; set; }
        public decimal? PlannedRiskAmountMax { get; set; }
        public DateTime? UpdatedAtMin { get; set; }
        public DateTime? UpdatedAtMax { get; set; }

        public override bool HasAnySearchCriteria()
        {
            _hasAnySearchCriteria = base.HasAnySearchCriteria();        
            if (_hasAnySearchCriteria) return true;

            _hasAnySearchCriteria = _hasAnySearchCriteria || TradingAccountId.HasValue;
            _hasAnySearchCriteria = _hasAnySearchCriteria || SymbolId.HasValue;
            _hasAnySearchCriteria = _hasAnySearchCriteria || TradeDirection.HasValue;
            _hasAnySearchCriteria = _hasAnySearchCriteria || EntryTimeMin.HasValue || EntryTimeMax.HasValue;
            _hasAnySearchCriteria = _hasAnySearchCriteria || PlannedPositionValueMin.HasValue || PlannedPositionValueMax.HasValue;
            _hasAnySearchCriteria = _hasAnySearchCriteria || ExecutedPositionValueMin.HasValue || ExecutedPositionValueMax.HasValue;
            _hasAnySearchCriteria = _hasAnySearchCriteria || PlannedProfitLossMin.HasValue || PlannedProfitLossMax.HasValue;
            _hasAnySearchCriteria = _hasAnySearchCriteria || RealizedProfitLossMin.HasValue || RealizedProfitLossMax.HasValue;
            _hasAnySearchCriteria = _hasAnySearchCriteria || PlannedRiskAmountMin.HasValue || PlannedRiskAmountMax.HasValue;
            _hasAnySearchCriteria = _hasAnySearchCriteria || UpdatedAtMin.HasValue || UpdatedAtMax.HasValue;

            OnHasAnySearchCriteria();
            return _hasAnySearchCriteria;
        }

        /// <summary>
        /// Called when determining if there are any search criteria, can be used in a partial class to extend the logic.
        /// Setting _hasAnySearchCriteria to true in this method will indicate that there are search criteria.
        /// </summary>
        partial void OnHasAnySearchCriteria();
        bool _hasAnySearchCriteria;
    }
}
