//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using TD.Models;

namespace TD.Helpers
{
    /// <summary>
    /// Represents the query parameters for the Trade entity.
    /// </summary>
    public partial class TradeQueryParameters : QueryParameters
    {
        public TradeQueryParameters() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="TradeQueryParameters"/> class based on the specified query parameters.
        /// </summary>
        /// <param name="queryParameters">The query parameters to copy values from.</param>
        public TradeQueryParameters(TradeQueryParameters queryParameters) : base(queryParameters)
        {
            if (queryParameters != null && queryParameters is TradeQueryParameters tradeQueryParams)
            {
                TradingAccountId = tradeQueryParams.TradingAccountId;
                SymbolId = tradeQueryParams.SymbolId;
                TradeDirection = tradeQueryParams.TradeDirection;
                EntryTimeMin = tradeQueryParams.EntryTimeMin;
                EntryTimeMax = tradeQueryParams.EntryTimeMax;
                UpdatedAtMin = tradeQueryParams.UpdatedAtMin;
                UpdatedAtMax = tradeQueryParams.UpdatedAtMax;
            }
        }

        public int? TradingAccountId { get; set; }
        public int? SymbolId { get; set; }
        public TradeDirection? TradeDirection { get; set; }
        public DateTime? EntryTimeMin { get; set; }
        public DateTime? EntryTimeMax { get; set; }
        public DateTime? UpdatedAtMin { get; set; }
        public DateTime? UpdatedAtMax { get; set; }
    }
}
