using TD.Models;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.AppInfra.Services
{
    public partial interface ICurrencyLookupService
    {
        Task<IReadOnlyList<Currency>> GetCurrenciesAsync(bool isActive);
    }
}
