using System.Collections.ObjectModel;
using TD.AppInfra.Services;
using TD.AppInfra.ViewModels;
using TD.Models;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.ViewModels.Maintenance
{
    public partial class ExchangeCreateVM : AbstractCreateEditVM
    {
        private readonly ICurrencyLookupService _currencyLookupService;
        private Exchange _exchange;
        public Exchange Exchange => _exchange;

        public ExchangeCreateVM(ICurrencyLookupService currencyLookupService)
        {
            _currencyLookupService = currencyLookupService;
            Currencies = new ObservableCollection<Currency>();

            _exchange = new Exchange();
            DisplayOrder = 1000;
            IsActive = true;
        }
           
        public ObservableCollection<Currency> Currencies { get; }

        public async Task LoadCurrenciesAsync()
        {
            var items = await _currencyLookupService.GetCurrenciesAsync(isActive: true);
            Currencies.Clear();
            foreach (var item in items)
            {
                Currencies.Add(item);
            }
        }


        public string ExchangeName
        {
            get { return _exchange.ExchangeName; }
            set
            {
                if (_exchange.ExchangeName != value)
                {
                    _exchange.ExchangeName = value;
                    RaisePropertyChanged(nameof(ExchangeName));
                    ValidateProperty(_exchange, nameof(ExchangeName));
                }
            }
        }

        public string ExchangeCode
        {
            get { return _exchange.ExchangeCode; }
            set
            {
                if (_exchange.ExchangeCode != value)
                {
                    _exchange.ExchangeCode = value.ToUpperInvariant();
                    RaisePropertyChanged(nameof(ExchangeCode));
                    ValidateProperty(_exchange, nameof(ExchangeCode));
                }
            }
        }

        public int DefaultCurrencyId
        {
            get { return _exchange.DefaultCurrencyId; }
            set
            {
                if (_exchange.DefaultCurrencyId != value)
                {
                    _exchange.DefaultCurrencyId = value;
                    RaisePropertyChanged(nameof(DefaultCurrencyId));
                    ValidateProperty(_exchange, nameof(DefaultCurrencyId));
                }
            }
        }

        public Currency DefaultCurrency
        {
            get { return _exchange.DefaultCurrency; }
            set
            {
                if (_exchange.DefaultCurrency != value)
                {
                    _exchange.DefaultCurrency = value;
                    RaisePropertyChanged(nameof(DefaultCurrency));
                    ValidateProperty(_exchange, nameof(DefaultCurrency));
                }
            }
        }

        public int DisplayOrder
        {
            get { return _exchange.DisplayOrder; }
            set
            {
                if (_exchange.DisplayOrder != value)
                {
                    _exchange.DisplayOrder = value;
                    RaisePropertyChanged(nameof(DisplayOrder));
                    ValidateProperty(_exchange, nameof(DisplayOrder));
                }
            }
        }

        public bool IsActive
        {
            get { return _exchange.IsActive; }
            set
            {
                if (_exchange.IsActive != value)
                {
                    _exchange.IsActive = value;
                    RaisePropertyChanged(nameof(IsActive));
                    ValidateProperty(_exchange, nameof(IsActive));
                }
            }
        }

        public bool ValidateModel()
        {
            return ValidateModel(_exchange);
        }
    }
}
