using TD.AppInfra.ViewModels;
using TD.Models;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.ViewModels.Maintenance
{
    public partial class TradingAccountEditVM : AbstractCreateEditVM
    {
        private TradingAccount _tradingAccount;
        public TradingAccount TradingAccount => _tradingAccount;

        public TradingAccountEditVM(TradingAccount tradingAccount)
        {
            _tradingAccount = tradingAccount;
            OnInitialized();
        }
        partial void OnInitialized();

        public string Title => _tradingAccount.Title;

        public int ExchangeId => _tradingAccount.ExchangeId;

        public Exchange Exchange => _tradingAccount.Exchange;

        public string? Notes
        {
            get { return _tradingAccount.Notes; }
            set
            {
                if (!string.IsNullOrWhiteSpace(value) && _tradingAccount.Notes != value)
                {
                    _tradingAccount.Notes = value;
                    RaisePropertyChanged(nameof(Notes));
                    ValidateProperty(_tradingAccount, nameof(Notes));
                }
                else if (string.IsNullOrWhiteSpace(value))
                {
                    _tradingAccount.Notes = null;
                    RaisePropertyChanged(nameof(Notes));
                    ValidateProperty(_tradingAccount, nameof(Notes));
                }
            }
        }

        public decimal? MakerFeeRate
        {
            get { return _tradingAccount.MakerFeeRate; }
            set
            {
                if (_tradingAccount.MakerFeeRate != value)
                {
                    _tradingAccount.MakerFeeRate = value;
                    RaisePropertyChanged(nameof(MakerFeeRate));
                    ValidateProperty(_tradingAccount, nameof(MakerFeeRate));
                }
            }
        }

        public decimal? TakerFeeRate
        {
            get { return _tradingAccount.TakerFeeRate; }
            set
            {
                if (_tradingAccount.TakerFeeRate != value)
                {
                    _tradingAccount.TakerFeeRate = value;
                    RaisePropertyChanged(nameof(TakerFeeRate));
                    ValidateProperty(_tradingAccount, nameof(TakerFeeRate));
                }
            }
        }

        public int DisplayOrder
        {
            get { return _tradingAccount.DisplayOrder; }
            set
            {
                if (_tradingAccount.DisplayOrder != value)
                {
                    _tradingAccount.DisplayOrder = value;
                    RaisePropertyChanged(nameof(DisplayOrder));
                    ValidateProperty(_tradingAccount, nameof(DisplayOrder));
                }
            }
        }

        public bool IsActive
        {
            get { return _tradingAccount.IsActive; }
            set
            {
                if (_tradingAccount.IsActive != value)
                {
                    _tradingAccount.IsActive = value;
                    RaisePropertyChanged(nameof(IsActive));
                    ValidateProperty(_tradingAccount, nameof(IsActive));
                }
            }
        }

        public bool ValidateModel()
        {
            return ValidateModel(_tradingAccount);
        }
    }
}
