using TD.Helpers;
using TD.Models;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.AppInfra.ViewModels.Trades
{
    public partial class TradeQueryParametersVM : QueryParametersVM
    {
        public TradeQueryParametersVM() : this(new TradeQueryParameters()) { }
        public TradeQueryParametersVM(TradeQueryParameters queryParam) : base(queryParam)
        {
            Parameters = queryParam;
        }

        public TradeQueryParameters Parameters { get; }
        
        public int? ByTradingAccountId
        {
            get => Parameters.TradingAccountId;
            set
            {
                Parameters.TradingAccountId = value;
                RaisePropertyChanged(nameof(ByTradingAccountId));
            }
        }
        
        public int? BySymbolId
        {
            get => Parameters.SymbolId;
            set
            {
                Parameters.SymbolId = value;
                RaisePropertyChanged(nameof(BySymbolId));
            }
        }
        
        public EntryMethod? ByEntryMethod
        {
            get => Parameters.EntryMethod;
            set
            {
                Parameters.EntryMethod = value;
                RaisePropertyChanged(nameof(ByEntryMethod));
            }
        }
        
        public TradeDirection? ByTradeDirection
        {
            get => Parameters.TradeDirection;
            set
            {
                Parameters.TradeDirection = value;
                RaisePropertyChanged(nameof(ByTradeDirection));
            }
        }
        
        public bool? IsFullyClosed
        {
            get => Parameters.IsFullyClosed;
            set
            {
                Parameters.IsFullyClosed = value;
                RaisePropertyChanged(nameof(IsFullyClosed));
            }
        }
        
        public DateTime? EntryTimeMin
        {
            get => Parameters.EntryTimeMin;
            set
            {
                Parameters.EntryTimeMin = value;
                RaisePropertyChanged(nameof(EntryTimeMin));
            }
        }

        public DateTime? EntryTimeMax
        {
            get => Parameters.EntryTimeMax;
            set
            {
                Parameters.EntryTimeMax = value;
                RaisePropertyChanged(nameof(EntryTimeMax));
            }
        }
        
        public decimal? PlannedPositionValueMin
        {
            get => Parameters.PlannedPositionValueMin;
            set
            {
                Parameters.PlannedPositionValueMin = value;
                RaisePropertyChanged(nameof(PlannedPositionValueMin));
            }
        }

        public decimal? PlannedPositionValueMax
        {
            get => Parameters.PlannedPositionValueMax;
            set
            {
                Parameters.PlannedPositionValueMax = value;
                RaisePropertyChanged(nameof(PlannedPositionValueMax));
            }
        }
        
        public decimal? ExecutedPositionValueMin
        {
            get => Parameters.ExecutedPositionValueMin;
            set
            {
                Parameters.ExecutedPositionValueMin = value;
                RaisePropertyChanged(nameof(ExecutedPositionValueMin));
            }
        }

        public decimal? ExecutedPositionValueMax
        {
            get => Parameters.ExecutedPositionValueMax;
            set
            {
                Parameters.ExecutedPositionValueMax = value;
                RaisePropertyChanged(nameof(ExecutedPositionValueMax));
            }
        }
        
        public decimal? RemainingPositionValueMin
        {
            get => Parameters.RemainingPositionValueMin;
            set
            {
                Parameters.RemainingPositionValueMin = value;
                RaisePropertyChanged(nameof(RemainingPositionValueMin));
            }
        }

        public decimal? RemainingPositionValueMax
        {
            get => Parameters.RemainingPositionValueMax;
            set
            {
                Parameters.RemainingPositionValueMax = value;
                RaisePropertyChanged(nameof(RemainingPositionValueMax));
            }
        }
        
        public decimal? PlannedProfitMin
        {
            get => Parameters.PlannedProfitMin;
            set
            {
                Parameters.PlannedProfitMin = value;
                RaisePropertyChanged(nameof(PlannedProfitMin));
            }
        }

        public decimal? PlannedProfitMax
        {
            get => Parameters.PlannedProfitMax;
            set
            {
                Parameters.PlannedProfitMax = value;
                RaisePropertyChanged(nameof(PlannedProfitMax));
            }
        }
        
        public decimal? RealizedProfitLossMin
        {
            get => Parameters.RealizedProfitLossMin;
            set
            {
                Parameters.RealizedProfitLossMin = value;
                RaisePropertyChanged(nameof(RealizedProfitLossMin));
            }
        }

        public decimal? RealizedProfitLossMax
        {
            get => Parameters.RealizedProfitLossMax;
            set
            {
                Parameters.RealizedProfitLossMax = value;
                RaisePropertyChanged(nameof(RealizedProfitLossMax));
            }
        }
        
        public decimal? PlannedRiskAmountMin
        {
            get => Parameters.PlannedRiskAmountMin;
            set
            {
                Parameters.PlannedRiskAmountMin = value;
                RaisePropertyChanged(nameof(PlannedRiskAmountMin));
            }
        }

        public decimal? PlannedRiskAmountMax
        {
            get => Parameters.PlannedRiskAmountMax;
            set
            {
                Parameters.PlannedRiskAmountMax = value;
                RaisePropertyChanged(nameof(PlannedRiskAmountMax));
            }
        }
        
        public DateTime? UpdatedAtMin
        {
            get => Parameters.UpdatedAtMin;
            set
            {
                Parameters.UpdatedAtMin = value;
                RaisePropertyChanged(nameof(UpdatedAtMin));
            }
        }

        public DateTime? UpdatedAtMax
        {
            get => Parameters.UpdatedAtMax;
            set
            {
                Parameters.UpdatedAtMax = value;
                RaisePropertyChanged(nameof(UpdatedAtMax));
            }
        }

        public void Reset()
        {
            ByTradingAccountId = null;
            BySymbolId = null;
            ByEntryMethod = null;
            ByTradeDirection = null;
            IsFullyClosed = null;
            EntryTimeMin = null;
            EntryTimeMax = null;
            PlannedPositionValueMin = null;
            PlannedPositionValueMax = null;
            ExecutedPositionValueMin = null;
            ExecutedPositionValueMax = null;
            RemainingPositionValueMin = null;
            RemainingPositionValueMax = null;
            PlannedProfitMin = null;
            PlannedProfitMax = null;
            RealizedProfitLossMin = null;
            RealizedProfitLossMax = null;
            PlannedRiskAmountMin = null;
            PlannedRiskAmountMax = null;
            UpdatedAtMin = null;
            UpdatedAtMax = null;
        }
    }
}