using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using TD.i18n;
//------------------------------------------------------------------------------
//
//     This code was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//------------------------------------------------------------------------------

namespace TD.Models
{
    public partial class Exchange
    {
        public Exchange()
        {
            this.ExchangeName = string.Empty;
            this.ExchangeCode = string.Empty;

            OnInitilazed();
        }
        /// <summary>
        /// PrimaryKey field
        /// </summary>
        [Key]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Id")]
        public int Id { get; set; }

        [StringLength(48, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExchangeName")]
        public string ExchangeName { get; set; }

        [StringLength(8, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExchangeCode")]
        public string ExchangeCode { get; set; }

        /// <summary>
        /// Ticker of default curreny of the exchange.
        /// </summary>
        [StringLength(8, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "DefaultCurrency")]
        public string? DefaultCurrency { get; set; }

        /// <summary>
        /// Determine if the exchange has any symbol.
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "HasAnySymbol")]
        public bool HasAnySymbol { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "DisplayOrder")]
        public int DisplayOrder { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "IsActive")]
        public bool IsActive { get; set; }


        /// <summary>
        /// Clones all properties in a new Exchange instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New Exchange instance</returns>
        public Exchange Clone()
        {
            var clone = new Exchange();
            clone.ExchangeName = this.ExchangeName;
            clone.ExchangeCode = this.ExchangeCode;
            clone.DefaultCurrency = this.DefaultCurrency;
            clone.HasAnySymbol = this.HasAnySymbol;
            clone.DisplayOrder = this.DisplayOrder;
            clone.IsActive = this.IsActive;

            Cloning(clone);
            return clone;
        }

        // Use below method in a partial class file (eg. Exchange.part.cs)
        // to add more detailed data to clone
        partial void Cloning(Exchange clone);


        // Use below method in a partial class file (eg. Exchange.part.cs)
        // to add some functionality after the constructor
        partial void OnInitilazed();
    }
}
