using System.ComponentModel.DataAnnotations;
using TD.i18n;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.Models
{
    public partial class StopLossOrder
    {
        public StopLossOrder()
        {
            this.Trade = new Trade();

            OnInitilazed();
        }
        /// <summary>
        /// PrimaryKey field
        /// </summary>
        [Key]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Id")]
        public int Id { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName ="ValueMin")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "TradeId")]
        public int TradeId { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "Trade")]
        public Trade Trade { get; set; }

        /// <summary>
        /// Indicates that all remaining quantity of the trade was or will be closed
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "StopAll")]
        public bool StopAll { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "OrderType")]
        public OrderType OrderType { get; set; }

        [Range(typeof(DateTime), "1/1/2000", "12/31/2220", ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName ="RangeDateTime")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExecuteTime")]
        public DateTime? ExecuteTime { get; set; }

        /// <summary>
        /// Planned Entry Price
        /// </summary>
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Range(0.00000001, double.MaxValue, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName ="ValueMin")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "OrderPrice")]
        public decimal OrderPrice { get; set; }

        /// <summary>
        /// Executed Entry Price
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "FilledPrice")]
        public decimal? FilledPrice { get; set; }

        /// <summary>
        /// Planned contract quantity of order
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "OrderQuantity")]
        public decimal? OrderQuantity { get; set; }

        /// <summary>
        /// Realized contract quantity of order
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "FilledQuantity")]
        public decimal? FilledQuantity { get; set; }

        /// <summary>
        /// Planned amount in currency, like $100
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "OrderAmount")]
        public decimal? OrderAmount { get; set; }

        /// <summary>
        /// Filled contract amount in currency, like $100
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "FilledAmount")]
        public decimal? FilledAmount { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "DisplayOrder")]
        public int DisplayOrder { get; set; }


        /// <summary>
        /// Clones all properties in a new StopLossOrder instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New StopLossOrder instance</returns>
        public StopLossOrder Clone()
        {
            var clone = new StopLossOrder();
            clone.TradeId = this.TradeId;
            clone.StopAll = this.StopAll;
            clone.OrderType = this.OrderType;
            clone.ExecuteTime = this.ExecuteTime;
            clone.OrderPrice = this.OrderPrice;
            clone.FilledPrice = this.FilledPrice;
            clone.OrderQuantity = this.OrderQuantity;
            clone.FilledQuantity = this.FilledQuantity;
            clone.OrderAmount = this.OrderAmount;
            clone.FilledAmount = this.FilledAmount;
            clone.DisplayOrder = this.DisplayOrder;

            Cloning(clone);
            return clone;
        }

        // Use below method in a partial class file (eg. StopLossOrder.part.cs)
        // to add more detailed data to clone
        partial void Cloning(StopLossOrder clone);


        // Use below method in a partial class file (eg. StopLossOrder.part.cs)
        // to add some functionality after the constructor
        partial void OnInitilazed();
    }
}
