using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using TD.i18n;
//----------------------------------------------------------------------------------
//
//     This code was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//----------------------------------------------------------------------------------

namespace TD.Models
{
    public partial class Symbol
    {
        public Symbol()
        {
            this.Exchange = new Exchange();
            this.Ticker = string.Empty;
            this.TickerFull = string.Empty;
            this.PriceCurrency = string.Empty;

            OnInitilazed();
        }
        /// <summary>
        /// PrimaryKey field
        /// </summary>
        [Key]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Id")]
        public int Id { get; set; }

        /// <summary>
        /// Symbol name without exchange prefix, e.g. 'BTCUSDT'
        /// </summary>
        [StringLength(48, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Ticker")]
        public string Ticker { get; set; }

        /// <summary>
        /// Symbol name with exchange prefix, e.g. 'BYBIT:BTCUSD.P'
        /// </summary>
        [StringLength(64, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "TickerFull")]
        public string TickerFull { get; set; }

        /// <summary>
        /// Contains a string (CurrencyTicker) that representing the symbol's base currency if the instrument is a Crypto pair or a Forex pair or a derivative based on such a pair. Otherwise, it contains empty string. For example, this property holds "GBP" for "GBPJPY", "BTC" for "BTCUSDT" and "" for "NASDAQ:MSFT".
        /// </summary>
        [StringLength(8, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "BaseCurrency")]
        public string? BaseCurrency { get; set; }

        /// <summary>
        /// Contains a string (CurrencyTicker) that representing currency of the symbol's price. For example, this property holds "JPY" for "GBPJPY", "USDT" for "BTCUSDT" and "USD" for "NASDAQ:MSFT".
        /// </summary>
        [StringLength(8, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "PriceCurrency")]
        public string PriceCurrency { get; set; }

        /// <summary>
        /// Description of the symbol.
        /// </summary>
        [StringLength(255, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [DataType(DataType.MultilineText)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Description")]
        public string? Description { get; set; }

        /// <summary>
        /// The Id value of exchange record that related to the symbol.
        /// </summary>
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName ="ValueMin")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExchangeId")]
        public int ExchangeId { get; set; }

        /// <summary>
        /// Exchange of the symbol.
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Exchange")]
        public Exchange Exchange { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "MarketType")]
        public MarketType MarketType { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "DisplayOrder")]
        public int DisplayOrder { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "IsActive")]
        public bool IsActive { get; set; }


        /// <summary>
        /// Clones all properties in a new Symbol instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New Symbol instance</returns>
        public Symbol Clone()
        {
            var clone = new Symbol();
            clone.Ticker = this.Ticker;
            clone.TickerFull = this.TickerFull;
            clone.BaseCurrency = this.BaseCurrency;
            clone.PriceCurrency = this.PriceCurrency;
            clone.Description = this.Description;
            clone.ExchangeId = this.ExchangeId;
            clone.MarketType = this.MarketType;
            clone.DisplayOrder = this.DisplayOrder;
            clone.IsActive = this.IsActive;

            Cloning(clone);
            return clone;
        }

        // Use below method in a partial class file (eg. Symbol.part.cs)
        // to add more detailed data to clone
        partial void Cloning(Symbol clone);


        // Use below method in a partial class file (eg. Symbol.part.cs)
        // to add some functionality after the constructor
        partial void OnInitilazed();
    }
}
