using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using TD.i18n;
//------------------------------------------------------------------------------
//
//     This code was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//------------------------------------------------------------------------------

namespace TD.Models
{
    public partial class Trade
    {
        public Trade()
        {
            this.EntryOrders = new HashSet<EntryOrder>();
            this.TakeProfitOrders = new HashSet<TakeProfitOrder>();
            this.StopLossOrders = new HashSet<StopLossOrder>();
            this.TradeImages = new HashSet<TradeImage>();
            this.TradingAccount = new TradingAccount();
            this.Symbol = new Symbol();

            OnInitilazed();
        }
        /// <summary>
        /// PrimaryKey field
        /// </summary>
        [Key]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Id")]
        public int Id { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName ="ValueMin")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "TradingAccountId")]
        public int TradingAccountId { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "TradingAccount")]
        public TradingAccount TradingAccount { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName ="ValueMin")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "SymbolId")]
        public int SymbolId { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "Symbol")]
        public Symbol Symbol { get; set; }

        [Range(typeof(DateTime), "1/1/2000", "12/31/2220", ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName ="RangeDateTime")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "EntryTime")]
        public DateTime? EntryTime { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "EntryMethod")]
        public EntryMethod EntryMethod { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "TradeDirection")]
        public TradeDirection TradeDirection { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "EntryOrders")]
        public ICollection<EntryOrder> EntryOrders { get; set; }

        /// <summary>
        /// Planned Entry Price, calculated from EntryOrders
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "PlannedEntry")]
        public decimal? PlannedEntry { get; set; }

        /// <summary>
        /// Executed Entry Price, calculated from EntryOrders
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExecutedEntry")]
        public decimal? ExecutedEntry { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "TakeProfitOrders")]
        public ICollection<TakeProfitOrder> TakeProfitOrders { get; set; }

        /// <summary>
        /// Planned Take Profit Price, calculated from TakeProfitOrders
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "PlannedTP")]
        public decimal? PlannedTP { get; set; }

        /// <summary>
        /// Executed Take Profit Price, calculated from TakeProfitOrders
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExecutedTP")]
        public decimal? ExecutedTP { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "StopLossOrders")]
        public ICollection<StopLossOrder> StopLossOrders { get; set; }

        /// <summary>
        /// Planned Stop Loss Price, calculated from StopLossOrders
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "PlannedSL")]
        public decimal? PlannedSL { get; set; }

        /// <summary>
        /// Executed Stop Loss Price, calculated from StopLossOrders
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExecutedSL")]
        public decimal? ExecutedSL { get; set; }

        /// <summary>
        /// Keeps Web URL or local file path of the images associated with the trade, along with optional notes. This collection allows for multiple images to be linked to a single trade, providing visual documentation or evidence of the trade setup, execution, or outcome. Each TradeImage instance contains details about the image and its relation to the trade, facilitating better organization and reference within the trading diary.
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "TradeImages")]
        public ICollection<TradeImage> TradeImages { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [DataType(DataType.Date)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ModifyDate")]
        public DateTime ModifyDate { get; set; }


        /// <summary>
        /// Clones all properties in a new Trade instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New Trade instance</returns>
        public Trade Clone()
        {
            var clone = new Trade();
            clone.TradingAccountId = this.TradingAccountId;
            clone.SymbolId = this.SymbolId;
            clone.EntryTime = this.EntryTime;
            clone.EntryMethod = this.EntryMethod;
            clone.TradeDirection = this.TradeDirection;
            clone.PlannedEntry = this.PlannedEntry;
            clone.ExecutedEntry = this.ExecutedEntry;
            clone.PlannedTP = this.PlannedTP;
            clone.ExecutedTP = this.ExecutedTP;
            clone.PlannedSL = this.PlannedSL;
            clone.ExecutedSL = this.ExecutedSL;
            clone.ModifyDate = this.ModifyDate;

            Cloning(clone);
            return clone;
        }

        // Use below method in a partial class file (eg. Trade.part.cs)
        // to add more detailed data to clone
        partial void Cloning(Trade clone);


        // Use below method in a partial class file (eg. Trade.part.cs)
        // to add some functionality after the constructor
        partial void OnInitilazed();
    }
}
