using System.Windows;
using TD.AppInfra.Commands;
using TD.i18n;
using TD.WPF.ViewModels.Trades;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.Commands.Trades
{
    public partial class TakeProfitOrderDeleteCommand : AbstractCommand
    {
        protected readonly TradeHistoryVM _viewModel;
        
        public TakeProfitOrderDeleteCommand(TradeHistoryVM viewModel)
        {
            _viewModel = viewModel;
        }

        public override bool CanExecute(object? parameter)
        {
            var takeProfitOrder = _viewModel.SelectedTakeProfitOrder;
            if (takeProfitOrder is null)
                return false;

            if (takeProfitOrder.Id < 1)
                return false;


            var result = _viewModel.TakeProfitOrderRepository
                                   .CanDeleteAsync(takeProfitOrder.Id)
                                   .GetAwaiter()
                                   .GetResult();
            return result;
        }

        public override async void Execute(object? parameter)
        {
            var takeProfitOrder = _viewModel.SelectedTakeProfitOrder;
            if (takeProfitOrder is null)
                return;

            if (takeProfitOrder.Id < 1)
                return;

            var result = MessageBox.Show(
                MessageStrings.AreYouSureToDelete,
                CommonStrings.AppTitle,
                MessageBoxButton.YesNo,
                MessageBoxImage.Question);

            if (result != MessageBoxResult.Yes)
                return;

            bool deleted = await _viewModel.TakeProfitOrderRepository.DeleteAsync(takeProfitOrder.Id);
            if (!deleted)
                return;

            _viewModel.SelectedTakeProfitOrder = null;
            _viewModel.TakeProfitOrders.Remove(takeProfitOrder);
            await _viewModel.LoadTakeProfitOrdersAsync();
        }
    }
}