//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using TD.Models;
using TD.SQLite.Extensions;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for EntryOrder CRUD operations.
    /// </summary>
    public partial class EntryOrderRepository : AbstractDatabaseRepository<EntryOrder>, IEntryOrderRepository
    {
        public EntryOrderRepository(string databasePath) : base(databasePath, "EntryOrders")
        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            InitializeDatabase();
            OnInitialized();
        }
        private readonly string _selectStatement;

        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "EntryOrder.sql");
        }

        partial void OnInitialized();

        public async Task<IReadOnlyList<EntryOrder>> GetAllAsync()
        {
            var result = new List<EntryOrder>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " ORDER BY DisplayOrder, Id";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var entryOrder = MapEntryOrder(reader);
                result.Add(entryOrder);
            }

            return result;
        }

        public async Task<IReadOnlyList<EntryOrder>> GetByTradeIdAsync(int tradeId)
        {
            var result = new List<EntryOrder>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE TradeId = @tradeId";
            command.Parameters.AddWithValue("@tradeId", tradeId);
            command.CommandText += " ORDER BY DisplayOrder, Id";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var entryOrder = MapEntryOrder(reader);
                result.Add(entryOrder);
            }

            return result;
        }
        

        public async Task<EntryOrder?> GetByIdAsync(int? id)
        {
            if (!id.HasValue || id.Value < 1)
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var entryOrder = MapEntryOrder(reader);
            
            OnLoaded(entryOrder);
            return entryOrder;
        }
        partial void OnLoaded(EntryOrder entryOrder);

        public async Task<int> CreateAsync(EntryOrder entryOrder)
        {
            ArgumentNullException.ThrowIfNull(entryOrder);
            ValidateOrThrow(entryOrder);

            await using var connection = await GetOpenConnectionAsync();

            await using var command = connection.CreateCommand();
            command.CommandText = @$"INSERT INTO {_tableName} ({string.Join(", ", ColumnNames[1..])})
            VALUES (@tradeId, @orderType, @executeTime, @orderPrice, @filledPrice, @orderQuantity, @filledQuantity, @orderValue, @filledValue, @displayOrder);
            SELECT last_insert_rowid();";
            
            command.Parameters.AddWithValue("@tradeId", entryOrder.TradeId);
            command.Parameters.AddWithValue("@orderType", (int)entryOrder.OrderType);
            command.Parameters.AddWithValue("@executeTime", entryOrder.ExecuteTime);
            command.Parameters.AddWithValue("@orderPrice", entryOrder.OrderPrice);
            command.Parameters.AddWithValue("@filledPrice", entryOrder.FilledPrice);
            command.Parameters.AddWithValue("@orderQuantity", entryOrder.OrderQuantity);
            command.Parameters.AddWithValue("@filledQuantity", entryOrder.FilledQuantity);
            command.Parameters.AddWithValue("@orderValue", entryOrder.OrderValue);
            command.Parameters.AddWithValue("@filledValue", entryOrder.FilledValue);
            command.Parameters.AddWithValue("@displayOrder", entryOrder.DisplayOrder);

            var id = Convert.ToInt32((long)(await command.ExecuteScalarAsync() ?? 0));
            
            await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            ClearRecordCountCache();
            entryOrder.Id = id;
            OnCreated(entryOrder);

            return id;
        }
        partial void OnCreated(EntryOrder entryOrder);

        public async Task<bool> DeleteAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"DELETE FROM {_tableName} WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                ClearRecordCountCache();
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateAsync(EntryOrder entryOrder)
        {
            ArgumentNullException.ThrowIfNull(entryOrder);
            ValidateOrThrow(entryOrder);

            await using var connection = await GetOpenConnectionAsync();
            var existingEntryOrder = await GetByIdAsync(entryOrder.Id);
            bool noChanges = existingEntryOrder != null
                          && existingEntryOrder.OrderType == entryOrder.OrderType 
                          && existingEntryOrder.ExecuteTime == entryOrder.ExecuteTime 
                          && existingEntryOrder.OrderPrice == entryOrder.OrderPrice 
                          && existingEntryOrder.FilledPrice == entryOrder.FilledPrice 
                          && existingEntryOrder.OrderQuantity == entryOrder.OrderQuantity 
                          && existingEntryOrder.FilledQuantity == entryOrder.FilledQuantity 
                          && existingEntryOrder.OrderValue == entryOrder.OrderValue 
                          && existingEntryOrder.FilledValue == entryOrder.FilledValue 
                          && existingEntryOrder.DisplayOrder == entryOrder.DisplayOrder; 

            if (noChanges)
                return false;

            await using var command = connection.CreateCommand();
            // TradeId is not updated to avoid complications with existing references,
            // so only OrderType, ExecuteTime, OrderPrice, FilledPrice, OrderQuantity, FilledQuantity, OrderValue, FilledValue, DisplayOrder are updated
            command.CommandText = @$"UPDATE {_tableName} SET
                OrderType = @orderType, 
                ExecuteTime = @executeTime, 
                OrderPrice = @orderPrice, 
                FilledPrice = @filledPrice, 
                OrderQuantity = @orderQuantity, 
                FilledQuantity = @filledQuantity, 
                OrderValue = @orderValue, 
                FilledValue = @filledValue, 
                DisplayOrder = @displayOrder 
            WHERE Id = @id";

            command.Parameters.AddWithValue("@id", entryOrder.Id);
            command.Parameters.AddWithValue("@orderType", (int)entryOrder.OrderType);
            command.Parameters.AddWithValue("@executeTime", entryOrder.ExecuteTime);
            command.Parameters.AddWithValue("@orderPrice", entryOrder.OrderPrice);
            command.Parameters.AddWithValue("@filledPrice", entryOrder.FilledPrice);
            command.Parameters.AddWithValue("@orderQuantity", entryOrder.OrderQuantity);
            command.Parameters.AddWithValue("@filledQuantity", entryOrder.FilledQuantity);
            command.Parameters.AddWithValue("@orderValue", entryOrder.OrderValue);
            command.Parameters.AddWithValue("@filledValue", entryOrder.FilledValue);
            command.Parameters.AddWithValue("@displayOrder", entryOrder.DisplayOrder);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(entryOrder);
            }
            
            return affectedRows > 0;
        }
        partial void OnUpdated(EntryOrder entryOrder);

        private static EntryOrder MapEntryOrder(SqliteDataReader reader)
        {
            var entryOrder = new EntryOrder
            {
                Id = reader.GetInt32(ColNrs.Id), 
                TradeId = reader.GetInt32(ColNrs.TradeId), 
                OrderType = (OrderType)reader.GetInt32(ColNrs.OrderType), 
                ExecuteTime = reader.IsDBNull(ColNrs.ExecuteTime) ? null : ToLocalDateTime(reader.GetString(ColNrs.ExecuteTime)), 
                OrderPrice = reader.GetDecimal(ColNrs.OrderPrice), 
                FilledPrice = reader.IsDBNull(ColNrs.FilledPrice) ? null : reader.GetDecimal(ColNrs.FilledPrice), 
                OrderQuantity = reader.IsDBNull(ColNrs.OrderQuantity) ? null : reader.GetDecimal(ColNrs.OrderQuantity), 
                FilledQuantity = reader.IsDBNull(ColNrs.FilledQuantity) ? null : reader.GetDecimal(ColNrs.FilledQuantity), 
                OrderValue = reader.IsDBNull(ColNrs.OrderValue) ? null : reader.GetDecimal(ColNrs.OrderValue), 
                FilledValue = reader.IsDBNull(ColNrs.FilledValue) ? null : reader.GetDecimal(ColNrs.FilledValue), 
                DisplayOrder = reader.GetInt32(ColNrs.DisplayOrder) 

            };

            return entryOrder;
        }

        /// <summary>
        /// Contains the column numbers for each property in the SQLiteDataReader.
        /// </summary>
        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int TradeId = 1;
            public readonly static int OrderType = 2;
            public readonly static int ExecuteTime = 3;
            public readonly static int OrderPrice = 4;
            public readonly static int FilledPrice = 5;
            public readonly static int OrderQuantity = 6;
            public readonly static int FilledQuantity = 7;
            public readonly static int OrderValue = 8;
            public readonly static int FilledValue = 9;
            public readonly static int DisplayOrder = 10;
        }

        /// <summary>
        /// Contains the names of all columns in the SQLiteDataReader.
        /// </summary>
        public readonly string[] ColumnNames = new[] {
            "Id", 
            "TradeId", 
            "OrderType", 
            "ExecuteTime", 
            "OrderPrice", 
            "FilledPrice", 
            "OrderQuantity", 
            "FilledQuantity", 
            "OrderValue", 
            "FilledValue", 
            "DisplayOrder" 
        };

        /// <summary>
        /// Contains the scale values used for converting decimal properties to integer storage.
        /// </summary>
        public readonly struct DecimalToIntegerScale
        {
            public readonly static int OrderPrice = 0;
            public readonly static int FilledPrice = 0;
            public readonly static int OrderQuantity = 0;
            public readonly static int FilledQuantity = 0;
            public readonly static int OrderValue = 4;
            public readonly static int FilledValue = 4;
        }
    }

    public partial interface IEntryOrderRepository
    {
        Task<IReadOnlyList<EntryOrder>> GetAllAsync();
        Task<IReadOnlyList<EntryOrder>> GetByTradeIdAsync(int tradeId);
        Task<EntryOrder?> GetByIdAsync(int? id);
        Task<int> CreateAsync(EntryOrder entryOrder);
        Task<bool> DeleteAsync(int id);
        Task<bool> UpdateAsync(EntryOrder entryOrder);
    }
}
