//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using TD.Models;
using TD.RepositoryContracts;
using TD.SQLite.Extensions;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for Exchange CRUD operations.
    /// </summary>
    public partial class ExchangeRepository : AbstractDatabaseRepository<Exchange>, IExchangeRepository
    {
        public ExchangeRepository(string databasePath, ICurrencyRepository? currencyRepository = null,
                                  ISymbolRepository? symbolRepository = null, ITradingAccountRepository? tradingAccountRepository = null) : base(databasePath, "Exchanges")

        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            _currencyRepository = currencyRepository ?? new CurrencyRepository(databasePath);
            _symbolRepository = symbolRepository ?? new SymbolRepository(databasePath, exchangeRepository: this);
            _tradingAccountRepository = tradingAccountRepository ?? new TradingAccountRepository(databasePath, exchangeRepository: this);
            InitializeDatabase();
            OnInitialized(currencyRepository == null, symbolRepository == null, tradingAccountRepository == null);
        }
        private readonly string _selectStatement;
        private readonly ICurrencyRepository _currencyRepository;
        private readonly ISymbolRepository _symbolRepository;
        private readonly ITradingAccountRepository _tradingAccountRepository;

        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "Exchange.sql");
            SeedIfEmpty(connection, "Exchanges-Data.sql");
        }

        /// <summary>
        /// Initialization hook for additional setup after the repository is constructed.
        /// The parameters indicate whether the corresponding repository was created by this repository (true) or provided externally (false),
        /// which can be useful to determine if any additional initialization or event wiring is needed.
        /// </summary>
        partial void OnInitialized(bool isCurrencyRepository, bool isSymbolRepository, bool isTradingAccountRepository);

        public async Task<IReadOnlyList<Exchange>> GetAllAsync(bool? isActive = null)
        {
            var result = new List<Exchange>();
            var currenciesById = (await _currencyRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            if (isActive.HasValue)
            {
                command.CommandText += " WHERE IsActive = @isActive";
                command.AddParameter("@isActive", isActive.Value);
            }

            command.CommandText += " ORDER BY DisplayOrder, ExchangeName";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var exchange = MapExchange(reader);
                if (currenciesById.TryGetValue(exchange.DefaultCurrencyId, out var defaultCurrency))
                    exchange.DefaultCurrency = defaultCurrency;

                result.Add(exchange);
            }

            return result;
        }
        public async Task<bool> AnyByDefaultCurrencyIdAsync(int defaultCurrencyId)
        {
            if (defaultCurrencyId < 1)
                throw new ArgumentOutOfRangeException(nameof(defaultCurrencyId), defaultCurrencyId, "Must be a valid positive id.");

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"SELECT COUNT(1) FROM {_tableName} WHERE DefaultCurrencyId = @defaultCurrencyId";
            command.Parameters.AddWithValue("@defaultCurrencyId", defaultCurrencyId);
            var result = await command.ExecuteScalarAsync();
            return Convert.ToInt64(result) > 0;
        }


        public async Task<IReadOnlyList<Exchange>> GetByDefaultCurrencyIdAsync(int defaultCurrencyId, bool? isActive = null)
        {
            var result = new List<Exchange>();
            var currenciesById = (await _currencyRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE DefaultCurrencyId = @defaultCurrencyId";
            command.AddParameter("@defaultCurrencyId", defaultCurrencyId);
            if (isActive.HasValue)
            {
                command.CommandText += " AND IsActive = @isActive";
                command.AddParameter("@isActive", isActive.Value);
            }

            command.CommandText += " ORDER BY DisplayOrder, ExchangeName";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var exchange = MapExchange(reader);
                if (currenciesById.TryGetValue(exchange.DefaultCurrencyId, out var defaultCurrency))
                    exchange.DefaultCurrency = defaultCurrency;

                result.Add(exchange);
            }

            return result;
        }


        public async Task<Exchange?> GetByIdAsync(int? id)
        {
            if (!id.HasValue || id.Value < 1)
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var exchange = MapExchange(reader);
            await LoadCurrencyAsync(exchange);

            OnLoaded(exchange);
            return exchange;
        }

        public async Task<Exchange?> GetByExchangeCodeAsync(string? exchangeCode)
        {
            if (string.IsNullOrWhiteSpace(exchangeCode))
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE ExchangeCode = @exchangeCode";
            command.Parameters.AddWithValue("@exchangeCode", exchangeCode);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var exchange = MapExchange(reader);
            await LoadCurrencyAsync(exchange);

            OnLoaded(exchange);
            return exchange;
        }
        partial void OnLoaded(Exchange exchange);

        public async Task<int> CreateAsync(Exchange exchange)
        {
            ArgumentNullException.ThrowIfNull(exchange);
            ValidateOrThrow(exchange);

            await using var connection = await GetOpenConnectionAsync();
            var existingExchange = await GetByExchangeCodeAsync(exchange.ExchangeCode);
            if (existingExchange != null)
            {
                exchange.Id = existingExchange.Id;
                await UpdateAsync(exchange);
                return existingExchange.Id;
            }

            await using var command = connection.CreateCommand();
            command.CommandText = @$"INSERT INTO {_tableName} ({string.Join(", ", ColumnNames[1..])})
            VALUES (@exchangeName, @exchangeCode, @defaultCurrencyId, @hasAnySymbol, @displayOrder, @isActive);
            SELECT last_insert_rowid();";

            command.AddParameter("@exchangeName", exchange.ExchangeName);
            command.AddParameter("@exchangeCode", exchange.ExchangeCode);
            command.AddParameter("@defaultCurrencyId", exchange.DefaultCurrencyId);
            command.AddParameter("@hasAnySymbol", exchange.HasAnySymbol);
            command.AddParameter("@displayOrder", exchange.DisplayOrder);
            command.AddParameter("@isActive", exchange.IsActive);

            var id = Convert.ToInt32((long)(await command.ExecuteScalarAsync() ?? 0));

            await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            ClearRecordCountCache();
            exchange.Id = id;
            OnCreated(exchange);

            return id;
        }
        partial void OnCreated(Exchange exchange);

        public async Task<bool> DeleteAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"DELETE FROM {_tableName} WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                ClearRecordCountCache();
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateAsync(Exchange exchange)
        {
            ArgumentNullException.ThrowIfNull(exchange);
            ValidateOrThrow(exchange);

            await using var connection = await GetOpenConnectionAsync();
            var existingExchange = await GetByExchangeCodeAsync(exchange.ExchangeCode);
            if (existingExchange != null && existingExchange.Id != exchange.Id)
            {
                throw new InvalidOperationException($"A different Exchange with the same ExchangeCode already exists: {exchange.ExchangeCode}");
            }

            existingExchange = await GetByIdAsync(exchange.Id);
            bool noChanges = existingExchange != null
                          && existingExchange.ExchangeName == exchange.ExchangeName                          && existingExchange.DisplayOrder == exchange.DisplayOrder                          && existingExchange.IsActive == exchange.IsActive;
            if (noChanges)
                return false;

            await using var command = connection.CreateCommand();
            // ExchangeCode, DefaultCurrencyId, HasAnySymbol are not updated to avoid complications with existing references,
            // so only ExchangeName, DisplayOrder, IsActive are updated
            command.CommandText = @$"UPDATE {_tableName} SET
                ExchangeName = @exchangeName,                DisplayOrder = @displayOrder,                IsActive = @isActive            WHERE Id = @id";

            command.AddParameter("@id", exchange.Id);
            command.AddParameter("@exchangeName", exchange.ExchangeName);
            command.AddParameter("@displayOrder", exchange.DisplayOrder);
            command.AddParameter("@isActive", exchange.IsActive);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(exchange);
            }

            return affectedRows > 0;
        }
        partial void OnUpdated(Exchange exchange);
        partial void OnUpdated(int exchangeId);

        public async Task<bool> UpdateHasAnySymbolAsync(int id, bool hasAnySymbol)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = @$"UPDATE {_tableName} SET
                HasAnySymbol = @hasAnySymbol            WHERE Id = @id";

            command.AddParameter("@id", id);
            command.AddParameter("@hasAnySymbol", hasAnySymbol);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(id);
            }

            return affectedRows > 0;
        }

        private async Task LoadCurrencyAsync(Exchange exchange)
        {
            exchange.DefaultCurrency = await _currencyRepository.GetByIdAsync(exchange.DefaultCurrencyId)
                            ?? new Currency { Id = exchange.DefaultCurrencyId };
        }


        private static Exchange MapExchange(SqliteDataReader reader)
        {
            var exchange = new Exchange
            {
                Id = reader.GetInt32(ColNrs.Id),
                ExchangeName = reader.GetString(ColNrs.ExchangeName),
                ExchangeCode = reader.GetString(ColNrs.ExchangeCode),
                DefaultCurrencyId = reader.GetInt32(ColNrs.DefaultCurrencyId),
                HasAnySymbol = reader.GetInt64(ColNrs.HasAnySymbol) == 1,
                DisplayOrder = reader.GetInt32(ColNrs.DisplayOrder),
                IsActive = reader.GetInt64(ColNrs.IsActive) == 1
            };

            return exchange;
        }

        /// <summary>
        /// Contains the column numbers for each property in the SQLiteDataReader.
        /// </summary>
        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int ExchangeName = 1;
            public readonly static int ExchangeCode = 2;
            public readonly static int DefaultCurrencyId = 3;
            public readonly static int HasAnySymbol = 4;
            public readonly static int DisplayOrder = 5;
            public readonly static int IsActive = 6;
        }

        /// <summary>
        /// Contains the names of all columns in the SQLiteDataReader.
        /// </summary>
        public readonly string[] ColumnNames = new[] {
            "Id",            "ExchangeName",            "ExchangeCode",            "DefaultCurrencyId",            "HasAnySymbol",            "DisplayOrder",            "IsActive"        };
    }
}
