//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using System;
using System.Collections.Generic;
using TD.Models;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for Exchange CRUD operations.
    /// </summary>
    public partial class ExchangeRepository : AbstractDatabaseRepository<Exchange>, IDbExchangeRepository
    {
        public ExchangeRepository(string databasePath) : base(databasePath, "Exchanges")
        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            InitializeDatabase();
        }
        private readonly string _selectStatement;

        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "Exchange.sql");
            SeedIfEmpty(connection, "Exchanges-Data.sql");
        }

        public async Task<IReadOnlyList<Exchange>> GetAllAsync(bool? isActive = null)
        {
            var result = new List<Exchange>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;

            if (isActive.HasValue)
            {
                command.CommandText += " WHERE IsActive = @isActive";
                command.Parameters.AddWithValue("@isActive", isActive.Value ? 1 : 0);
            }

            command.CommandText += " ORDER BY DisplayOrder, ExchangeName";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                result.Add(MapExchange(reader));
            }

            return result;
        }

        public async Task<Exchange?> GetByIdAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            return MapExchange(reader);
        }

        public async Task<Exchange?> GetByExchangeCodeAsync(string exchangeCode)
        {
            if (string.IsNullOrWhiteSpace(exchangeCode))
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE ExchangeCode = @exchangeCode";
            command.Parameters.AddWithValue("@exchangeCode", exchangeCode);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            return MapExchange(reader);
        }

        public async Task<int> CreateAsync(Exchange exchange)
        {
            ArgumentNullException.ThrowIfNull(exchange);
            ValidateOrThrow(exchange);

            await using var connection = await GetOpenConnectionAsync();
            var existingExchange = await GetByExchangeCodeAsync(exchange.ExchangeCode);
            if (existingExchange != null)
            {
                exchange.Id = existingExchange.Id;
                await UpdateAsync(exchange);
                return existingExchange.Id;
            }

            await using var command = connection.CreateCommand();
            command.CommandText = @$"INSERT INTO {_tableName} ({string.Join(", ", ColumnNames[1..])})
            VALUES (@exchangeName, @exchangeCode, @defaultCurrency, @hasAnySymbol, @displayOrder, @isActive);
            SELECT last_insert_rowid();";

            command.Parameters.AddWithValue("@exchangeName", exchange.ExchangeName);
            command.Parameters.AddWithValue("@exchangeCode", exchange.ExchangeCode);
            AddNullableTextParameter(command, "@defaultCurrency", exchange.DefaultCurrency);
            command.Parameters.AddWithValue("@hasAnySymbol", exchange.HasAnySymbol ? 1 : 0);
            command.Parameters.AddWithValue("@displayOrder", exchange.DisplayOrder);
            command.Parameters.AddWithValue("@isActive", exchange.IsActive ? 1 : 0);

            var id = Convert.ToInt32((long)(await command.ExecuteScalarAsync() ?? 0));

            await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            ClearRecordCountCache();

            return id;
        }

        public async Task<bool> UpdateAsync(Exchange exchange)
        {
            ArgumentNullException.ThrowIfNull(exchange);
            ValidateOrThrow(exchange);

            await using var connection = await GetOpenConnectionAsync();
            var existingExchange = await GetByExchangeCodeAsync(exchange.ExchangeCode);
            if (existingExchange != null && existingExchange.Id != exchange.Id)
                throw new InvalidOperationException($"A different exchange with the same code already exists: {exchange.ExchangeCode}");

            bool noChanges = existingExchange != null
                          && existingExchange.ExchangeName.Equals(exchange.ExchangeName)
                          && existingExchange.DefaultCurrency == exchange.DefaultCurrency
                          && existingExchange.DisplayOrder == exchange.DisplayOrder
                          && existingExchange.IsActive == exchange.IsActive;

            if (noChanges)
                return false;

            await using var command = connection.CreateCommand();
            // ExchangeCode is not updated to avoid complications with existing references,
            // so only ExchangeName, DisplayOrder and IsActive are updated
            command.CommandText = @"
            UPDATE Exchanges
            SET ExchangeName = @exchangeName,
                DefaultCurrency = @defaultCurrency,
                DisplayOrder = @displayOrder,
                IsActive = @isActive
            WHERE Id = @id";

            command.Parameters.AddWithValue("@id", exchange.Id);
            command.Parameters.AddWithValue("@exchangeName", exchange.ExchangeName);
            AddNullableTextParameter(command, "@defaultCurrency", exchange.DefaultCurrency);
            command.Parameters.AddWithValue("@displayOrder", exchange.DisplayOrder);
            command.Parameters.AddWithValue("@isActive", exchange.IsActive ? 1 : 0);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);

            return affectedRows > 0;
        }


        public async Task<bool> SetHasAnySymbol(int exchangeId, bool hasAnySymbol)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = @"
            UPDATE Exchanges
            SET HasAnySymbol = @hasAnySymbol
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", exchangeId);
            command.Parameters.AddWithValue("@hasAnySymbol", hasAnySymbol ? 1 : 0);
            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            return affectedRows > 0;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = "DELETE FROM Exchanges WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                ClearRecordCountCache();
            }

            return affectedRows > 0;
        }

        private static Exchange MapExchange(SqliteDataReader reader)
        {
            var exchange = new Exchange
            {
                Id = reader.GetInt32(ColNrs.Id),
                ExchangeName = reader.GetString(ColNrs.ExchangeName),
                ExchangeCode = reader.GetString(ColNrs.ExchangeCode),
                DefaultCurrency = reader.IsDBNull(ColNrs.DefaultCurrency) ? null : reader.GetString(ColNrs.DefaultCurrency),
                HasAnySymbol = reader.GetInt64(ColNrs.HasAnySymbol) == 1,
                DisplayOrder = reader.GetInt32(ColNrs.DisplayOrder),
                IsActive = reader.GetInt64(ColNrs.IsActive) == 1

            };

            return exchange;
        }

        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int ExchangeName = 1;
            public readonly static int ExchangeCode = 2;
            public readonly static int DefaultCurrency = 3;
            public readonly static int HasAnySymbol = 4;
            public readonly static int DisplayOrder = 5;
            public readonly static int IsActive = 6;
        }

        public readonly string[] ColumnNames = new[] {
            "Id",
            "ExchangeName",
            "ExchangeCode",
            "DefaultCurrency",
            "HasAnySymbol",
            "DisplayOrder",
            "IsActive"
        };
    }
}
