//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using TD.Models;
using TD.SQLite.Extensions;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for StopLossOrder CRUD operations.
    /// </summary>
    public partial class StopLossOrderRepository : AbstractDatabaseRepository<StopLossOrder>, IStopLossOrderRepository
    {
        public StopLossOrderRepository(string databasePath) : base(databasePath, "StopLossOrders")
        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            InitializeDatabase();
            OnInitialized();
        }
        private readonly string _selectStatement;

        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "StopLossOrder.sql");
        }

        partial void OnInitialized();

        public async Task<IReadOnlyList<StopLossOrder>> GetAllAsync()
        {
            var result = new List<StopLossOrder>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " ORDER BY DisplayOrder, Id";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var stopLossOrder = MapStopLossOrder(reader);
                result.Add(stopLossOrder);
            }

            return result;
        }

        public async Task<IReadOnlyList<StopLossOrder>> GetByTradeIdAsync(int tradeId)
        {
            var result = new List<StopLossOrder>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE TradeId = @tradeId";
            command.AddParameter("@tradeId", tradeId);
            command.CommandText += " ORDER BY DisplayOrder, Id";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var stopLossOrder = MapStopLossOrder(reader);
                result.Add(stopLossOrder);
            }

            return result;
        }
        

        public async Task<StopLossOrder?> GetByIdAsync(int? id)
        {
            if (!id.HasValue || id.Value < 1)
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var stopLossOrder = MapStopLossOrder(reader);
            
            OnLoaded(stopLossOrder);
            return stopLossOrder;
        }
        partial void OnLoaded(StopLossOrder stopLossOrder);
        
        public async Task<int> CreateAsync(StopLossOrder stopLossOrder)
        {
            ArgumentNullException.ThrowIfNull(stopLossOrder);
            ValidateOrThrow(stopLossOrder);

            await using var connection = await GetOpenConnectionAsync();

            await using var command = connection.CreateCommand();
            command.CommandText = @$"INSERT INTO {_tableName} ({string.Join(", ", ColumnNames[1..])})
            VALUES (@tradeId, @stopAll, @orderType, @executeTime, @orderPrice, @filledPrice, @orderQuantity, @filledQuantity, @orderValue, @filledValue, @displayOrder);
            SELECT last_insert_rowid();";
            
            command.AddParameter("@tradeId", stopLossOrder.TradeId);
            command.AddParameter("@stopAll", stopLossOrder.StopAll);
            command.AddParameter("@orderType", (int)stopLossOrder.OrderType);
            command.AddDateTimeToTextParameter("@executeTime", stopLossOrder.ExecuteTime);
            command.AddDecimalToTextParameter("@orderPrice", stopLossOrder.OrderPrice);
            command.AddDecimalToTextParameter("@filledPrice", stopLossOrder.FilledPrice);
            command.AddDecimalToTextParameter("@orderQuantity", stopLossOrder.OrderQuantity);
            command.AddDecimalToTextParameter("@filledQuantity", stopLossOrder.FilledQuantity);
            command.AddDecimalToIntegerParameter("@orderValue",
                                                stopLossOrder.OrderValue,
                                                DecimalToIntegerScale.OrderValue);
            command.AddDecimalToIntegerParameter("@filledValue",
                                                stopLossOrder.FilledValue,
                                                DecimalToIntegerScale.FilledValue);
            command.AddParameter("@displayOrder", stopLossOrder.DisplayOrder);

            var id = Convert.ToInt32((long)(await command.ExecuteScalarAsync() ?? 0));
            
            await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            ClearRecordCountCache();
            stopLossOrder.Id = id;
            OnCreated(stopLossOrder);

            return id;
        }
        partial void OnCreated(StopLossOrder stopLossOrder);

        public async Task<bool> DeleteAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"DELETE FROM {_tableName} WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                ClearRecordCountCache();
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateAsync(StopLossOrder stopLossOrder)
        {
            ArgumentNullException.ThrowIfNull(stopLossOrder);
            ValidateOrThrow(stopLossOrder);

            await using var connection = await GetOpenConnectionAsync();
            var existingStopLossOrder = await GetByIdAsync(stopLossOrder.Id);
            bool noChanges = existingStopLossOrder != null
                          && existingStopLossOrder.StopAll == stopLossOrder.StopAll 
                          && existingStopLossOrder.OrderType == stopLossOrder.OrderType 
                          && existingStopLossOrder.ExecuteTime == stopLossOrder.ExecuteTime 
                          && existingStopLossOrder.OrderPrice == stopLossOrder.OrderPrice 
                          && existingStopLossOrder.FilledPrice == stopLossOrder.FilledPrice 
                          && existingStopLossOrder.OrderQuantity == stopLossOrder.OrderQuantity 
                          && existingStopLossOrder.FilledQuantity == stopLossOrder.FilledQuantity 
                          && existingStopLossOrder.OrderValue == stopLossOrder.OrderValue 
                          && existingStopLossOrder.FilledValue == stopLossOrder.FilledValue 
                          && existingStopLossOrder.DisplayOrder == stopLossOrder.DisplayOrder; 

            if (noChanges)
                return false;

            await using var command = connection.CreateCommand();
            // TradeId is not updated to avoid complications with existing references,
            // so only StopAll, OrderType, ExecuteTime, OrderPrice, FilledPrice, OrderQuantity, FilledQuantity, OrderValue, FilledValue, DisplayOrder are updated
            command.CommandText = @$"UPDATE {_tableName} SET
                StopAll = @stopAll, 
                OrderType = @orderType, 
                ExecuteTime = @executeTime, 
                OrderPrice = @orderPrice, 
                FilledPrice = @filledPrice, 
                OrderQuantity = @orderQuantity, 
                FilledQuantity = @filledQuantity, 
                OrderValue = @orderValue, 
                FilledValue = @filledValue, 
                DisplayOrder = @displayOrder 
            WHERE Id = @id";

            command.AddParameter("@id", stopLossOrder.Id);
            command.AddParameter("@stopAll", stopLossOrder.StopAll);
            command.AddParameter("@orderType", (int)stopLossOrder.OrderType);
            command.AddDateTimeToTextParameter("@executeTime", stopLossOrder.ExecuteTime);
            command.AddDecimalToTextParameter("@orderPrice", stopLossOrder.OrderPrice);
            command.AddDecimalToTextParameter("@filledPrice", stopLossOrder.FilledPrice);
            command.AddDecimalToTextParameter("@orderQuantity", stopLossOrder.OrderQuantity);
            command.AddDecimalToTextParameter("@filledQuantity", stopLossOrder.FilledQuantity);
            command.AddDecimalToIntegerParameter("@orderValue",
                                                stopLossOrder.OrderValue,
                                                DecimalToIntegerScale.OrderValue);
            command.AddDecimalToIntegerParameter("@filledValue",
                                                stopLossOrder.FilledValue,
                                                DecimalToIntegerScale.FilledValue);
            command.AddParameter("@displayOrder", stopLossOrder.DisplayOrder);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(stopLossOrder);
            }
            
            return affectedRows > 0;
        }
        partial void OnUpdated(StopLossOrder stopLossOrder);

        private static StopLossOrder MapStopLossOrder(SqliteDataReader reader)
        {
            var stopLossOrder = new StopLossOrder
            {
                Id = reader.GetInt32(ColNrs.Id),
                TradeId = reader.GetInt32(ColNrs.TradeId),
                StopAll = reader.GetInt64(ColNrs.StopAll) == 1,
                OrderType = (OrderType)reader.GetInt32(ColNrs.OrderType),
                ExecuteTime = reader.IsDBNull(ColNrs.ExecuteTime) ? null
                            : ToLocalDateTime(reader.GetString(ColNrs.ExecuteTime)),
                OrderPrice = reader.GetDecimalFromText(ColNrs.OrderPrice) ?? 0m,
                FilledPrice = reader.IsDBNull(ColNrs.FilledPrice) ? null
                            : reader.GetDecimalFromText(ColNrs.FilledPrice),
                OrderQuantity = reader.IsDBNull(ColNrs.OrderQuantity) ? null
                              : reader.GetDecimalFromText(ColNrs.OrderQuantity),
                FilledQuantity = reader.IsDBNull(ColNrs.FilledQuantity) ? null
                               : reader.GetDecimalFromText(ColNrs.FilledQuantity),
                OrderValue = reader.IsDBNull(ColNrs.OrderValue) ? null
                           : reader.GetDecimalFromInteger(ColNrs.OrderValue,
                                           DecimalToIntegerScale.OrderValue),
                FilledValue = reader.IsDBNull(ColNrs.FilledValue) ? null
                            : reader.GetDecimalFromInteger(ColNrs.FilledValue,
                                            DecimalToIntegerScale.FilledValue),
                DisplayOrder = reader.GetInt32(ColNrs.DisplayOrder)
            };

            return stopLossOrder;
        }

        /// <summary>
        /// Contains the column numbers for each property in the SQLiteDataReader.
        /// </summary>
        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int TradeId = 1;
            public readonly static int StopAll = 2;
            public readonly static int OrderType = 3;
            public readonly static int ExecuteTime = 4;
            public readonly static int OrderPrice = 5;
            public readonly static int FilledPrice = 6;
            public readonly static int OrderQuantity = 7;
            public readonly static int FilledQuantity = 8;
            public readonly static int OrderValue = 9;
            public readonly static int FilledValue = 10;
            public readonly static int DisplayOrder = 11;
        }

        /// <summary>
        /// Contains the names of all columns in the SQLiteDataReader.
        /// </summary>
        public readonly string[] ColumnNames = new[] {
            "Id", 
            "TradeId", 
            "StopAll", 
            "OrderType", 
            "ExecuteTime", 
            "OrderPrice", 
            "FilledPrice", 
            "OrderQuantity", 
            "FilledQuantity", 
            "OrderValue", 
            "FilledValue", 
            "DisplayOrder" 
        };

        /// <summary>
        /// Contains the scale values used for converting decimal properties to integer storage.
        /// </summary>
        public readonly struct DecimalToIntegerScale
        {
            public readonly static int OrderPrice = 0;
            public readonly static int FilledPrice = 0;
            public readonly static int OrderQuantity = 0;
            public readonly static int FilledQuantity = 0;
            public readonly static int OrderValue = 4;
            public readonly static int FilledValue = 4;
        }
    }

    public partial interface IStopLossOrderRepository
    {
        Task<IReadOnlyList<StopLossOrder>> GetAllAsync();
        Task<IReadOnlyList<StopLossOrder>> GetByTradeIdAsync(int tradeId);
        Task<StopLossOrder?> GetByIdAsync(int? id);
        Task<int> CreateAsync(StopLossOrder stopLossOrder);
        Task<bool> DeleteAsync(int id);
        Task<bool> UpdateAsync(StopLossOrder stopLossOrder);
    }
}
