//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using System;
using System.Collections.Generic;
using TD.Models;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for Symbol CRUD operations.
    /// </summary>
    public partial class SymbolRepository : AbstractDatabaseRepository<Symbol>, ISymbolRepository
    {
        public SymbolRepository(string databasePath
                               , IExchangeRepository? exchangeRepository = null) : base(databasePath, "Symbols") 
        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            _exchangeRepository = exchangeRepository ?? new ExchangeRepository(databasePath);
            InitializeDatabase();
        }
        private readonly string _selectStatement;
        private readonly IExchangeRepository _exchangeRepository;

        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "Symbol.sql");
            SeedIfEmpty(connection, "Symbols-Data.sql");
        }

        public async Task<IReadOnlyList<Symbol>> GetAllAsync(bool? isActive = null)
        {
            var result = new List<Symbol>();
            var exchangesById = (await _exchangeRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            if (isActive.HasValue)
            {
                command.CommandText += " WHERE IsActive = @isActive";
                command.Parameters.AddWithValue("@isActive", isActive.Value ? 1 : 0);
            }

            command.CommandText += " ORDER BY DisplayOrder, TickerFull";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var symbol = MapSymbol(reader);
                if (exchangesById.TryGetValue(symbol.ExchangeId, out var exchange))
                    symbol.Exchange = exchange;

                result.Add(symbol);
            }

            return result;
        }

        public async Task<IReadOnlyList<Symbol>> GetByExchangeIdAsync(int exchangeId, bool? isActive = null)
        {
            var result = new List<Symbol>();
            var exchangesById = (await _exchangeRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE ExchangeId = @exchangeId";
            command.Parameters.AddWithValue("@exchangeId", exchangeId);
            if (isActive.HasValue)
            {
                command.CommandText += " AND IsActive = @isActive";
                command.Parameters.AddWithValue("@isActive", isActive.Value ? 1 : 0);
            }

            command.CommandText += " ORDER BY DisplayOrder, TickerFull";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var symbol = MapSymbol(reader);
                if (exchangesById.TryGetValue(symbol.ExchangeId, out var exchange))
                    symbol.Exchange = exchange;

                result.Add(symbol);
            }

            return result;
        }
        

        public async Task<Symbol?> GetByIdAsync(int? id)
        {
            if (!id.HasValue || id.Value < 1)
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var symbol = MapSymbol(reader);
            await LoadExchangeAsync(symbol);
            
            OnLoaded(symbol);
            return symbol;
        }

        public async Task<Symbol?> GetByTickerFullAsync(string? tickerFull)
        {
            if (string.IsNullOrWhiteSpace(tickerFull))
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE TickerFull = @tickerFull";
            command.Parameters.AddWithValue("@tickerFull", tickerFull);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var symbol = MapSymbol(reader);
            await LoadExchangeAsync(symbol);
            
            OnLoaded(symbol);
            return symbol;
        }
        partial void OnLoaded(Symbol symbol);

        public async Task<int> CreateAsync(Symbol symbol)
        {
            ArgumentNullException.ThrowIfNull(symbol);
            ValidateOrThrow(symbol);

            await using var connection = await GetOpenConnectionAsync();
            var existingSymbol = await GetByTickerFullAsync(symbol.TickerFull);
            if (existingSymbol != null)
            {
                symbol.Id = existingSymbol.Id;
                await UpdateAsync(symbol);
                return existingSymbol.Id;
            }

            await using var command = connection.CreateCommand();
            command.CommandText = @$"INSERT INTO {_tableName} ({string.Join(", ", ColumnNames[1..])})
            VALUES (@ticker, @tickerFull, @baseCurrency, @priceCurrency, @description, @exchangeId, @marketType, @displayOrder, @isActive);
            SELECT last_insert_rowid();";
            
            command.Parameters.AddWithValue("@ticker", symbol.Ticker);
            command.Parameters.AddWithValue("@tickerFull", symbol.TickerFull);
            AddNullableTextParameter(command, "@baseCurrency", symbol.BaseCurrency);
            command.Parameters.AddWithValue("@priceCurrency", symbol.PriceCurrency);
            AddNullableTextParameter(command, "@description", symbol.Description);
            command.Parameters.AddWithValue("@exchangeId", symbol.ExchangeId);
            command.Parameters.AddWithValue("@marketType", (int)symbol.MarketType);
            command.Parameters.AddWithValue("@displayOrder", symbol.DisplayOrder);
            command.Parameters.AddWithValue("@isActive", symbol.IsActive ? 1 : 0);

            var id = Convert.ToInt32((long)(await command.ExecuteScalarAsync() ?? 0));
            
            await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            ClearRecordCountCache();
            symbol.Id = id;
            OnCreated(symbol);

            return id;
        }
        partial void OnCreated(Symbol symbol);

        public async Task<bool> DeleteAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"DELETE FROM {_tableName} WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                ClearRecordCountCache();
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateAsync(Symbol symbol)
        {
            ArgumentNullException.ThrowIfNull(symbol);
            ValidateOrThrow(symbol);

            await using var connection = await GetOpenConnectionAsync();
            var existingSymbol = await GetByTickerFullAsync(symbol.TickerFull);
            if (existingSymbol != null && existingSymbol.Id != symbol.Id)
            {
                throw new InvalidOperationException($"A different Symbol with the same TickerFull already exists: {symbol.TickerFull}");
            }

            existingSymbol = await GetByIdAsync(symbol.Id);
            bool noChanges = existingSymbol != null
                          && existingSymbol.Description == symbol.Description 
                          && existingSymbol.MarketType == symbol.MarketType 
                          && existingSymbol.DisplayOrder == symbol.DisplayOrder 
                          && existingSymbol.IsActive == symbol.IsActive; 

            if (noChanges)
                return false;

            await using var command = connection.CreateCommand();
            // Ticker, TickerFull, BaseCurrency, PriceCurrency, ExchangeId are not updated to avoid complications with existing references,
            // so only Description, MarketType, DisplayOrder, IsActive are updated
            command.CommandText = @$"UPDATE {_tableName} SET
                Description = @description, 
                MarketType = @marketType, 
                DisplayOrder = @displayOrder, 
                IsActive = @isActive 
            WHERE Id = @id";

            command.Parameters.AddWithValue("@id", symbol.Id);
            AddNullableTextParameter(command, "@description", symbol.Description);
            command.Parameters.AddWithValue("@marketType", (int)symbol.MarketType);
            command.Parameters.AddWithValue("@displayOrder", symbol.DisplayOrder);
            command.Parameters.AddWithValue("@isActive", symbol.IsActive ? 1 : 0);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(symbol);
            }
            
            return affectedRows > 0;
        }
        partial void OnUpdated(Symbol symbol);

        private async Task LoadExchangeAsync(Symbol symbol)
        {
            symbol.Exchange = await _exchangeRepository.GetByIdAsync(symbol.ExchangeId)
                            ?? new Exchange { Id = symbol.ExchangeId };
        }


        private static Symbol MapSymbol(SqliteDataReader reader)
        {
            var symbol = new Symbol
            {
                Id = reader.GetInt32(ColNrs.Id), 
                Ticker = reader.GetString(ColNrs.Ticker), 
                TickerFull = reader.GetString(ColNrs.TickerFull), 
                BaseCurrency = reader.IsDBNull(ColNrs.BaseCurrency) ? null : reader.GetString(ColNrs.BaseCurrency), 
                PriceCurrency = reader.GetString(ColNrs.PriceCurrency), 
                Description = reader.IsDBNull(ColNrs.Description) ? null : reader.GetString(ColNrs.Description), 
                ExchangeId = reader.GetInt32(ColNrs.ExchangeId), 
                MarketType = (MarketType)reader.GetInt32(ColNrs.MarketType), 
                DisplayOrder = reader.GetInt32(ColNrs.DisplayOrder), 
                IsActive = reader.GetInt64(ColNrs.IsActive) == 1 

            };

            return symbol;
        }

        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int Ticker = 1;
            public readonly static int TickerFull = 2;
            public readonly static int BaseCurrency = 3;
            public readonly static int PriceCurrency = 4;
            public readonly static int Description = 5;
            public readonly static int ExchangeId = 6;
            public readonly static int MarketType = 7;
            public readonly static int DisplayOrder = 8;
            public readonly static int IsActive = 9;
        }

        public readonly string[] ColumnNames = new[] {
            "Id", 
            "Ticker", 
            "TickerFull", 
            "BaseCurrency", 
            "PriceCurrency", 
            "Description", 
            "ExchangeId", 
            "MarketType", 
            "DisplayOrder", 
            "IsActive" 
        };
    }

    public partial interface ISymbolRepository
    {
        Task<IReadOnlyList<Symbol>> GetAllAsync(bool? isActive = null);
        Task<IReadOnlyList<Symbol>> GetByExchangeIdAsync(int exchangeId, bool? isActive = null);
        Task<Symbol?> GetByIdAsync(int? id);
        Task<Symbol?> GetByTickerFullAsync(string? tickerFull);
        Task<int> CreateAsync(Symbol symbol);
        Task<bool> DeleteAsync(int id);
        Task<bool> UpdateAsync(Symbol symbol);
    }
}
