//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using TD.Models;
using TD.SQLite.Extensions;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for TakeProfitOrder CRUD operations.
    /// </summary>
    public partial class TakeProfitOrderRepository : AbstractDatabaseRepository<TakeProfitOrder>, ITakeProfitOrderRepository
    {
        public TakeProfitOrderRepository(string databasePath) : base(databasePath, "TakeProfitOrders")
        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            InitializeDatabase();
            OnInitialized();
        }
        private readonly string _selectStatement;

        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "TakeProfitOrder.sql");
        }

        partial void OnInitialized();

        public async Task<IReadOnlyList<TakeProfitOrder>> GetAllAsync()
        {
            var result = new List<TakeProfitOrder>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " ORDER BY DisplayOrder, Id";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var takeProfitOrder = MapTakeProfitOrder(reader);
                result.Add(takeProfitOrder);
            }

            return result;
        }

        public async Task<IReadOnlyList<TakeProfitOrder>> GetByTradeIdAsync(int tradeId)
        {
            var result = new List<TakeProfitOrder>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE TradeId = @tradeId";
            command.AddParameter("@tradeId", tradeId);
            command.CommandText += " ORDER BY DisplayOrder, Id";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var takeProfitOrder = MapTakeProfitOrder(reader);
                result.Add(takeProfitOrder);
            }

            return result;
        }
        

        public async Task<TakeProfitOrder?> GetByIdAsync(int? id)
        {
            if (!id.HasValue || id.Value < 1)
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var takeProfitOrder = MapTakeProfitOrder(reader);
            
            OnLoaded(takeProfitOrder);
            return takeProfitOrder;
        }
        partial void OnLoaded(TakeProfitOrder takeProfitOrder);
        
        public async Task<int> CreateAsync(TakeProfitOrder takeProfitOrder)
        {
            ArgumentNullException.ThrowIfNull(takeProfitOrder);
            ValidateOrThrow(takeProfitOrder);

            await using var connection = await GetOpenConnectionAsync();

            await using var command = connection.CreateCommand();
            command.CommandText = @$"INSERT INTO {_tableName} ({string.Join(", ", ColumnNames[1..])})
            VALUES (@tradeId, @orderType, @executeTime, @orderPrice, @filledPrice, @orderQuantity, @filledQuantity, @orderValue, @filledValue, @displayOrder);
            SELECT last_insert_rowid();";
            
            command.AddParameter("@tradeId", takeProfitOrder.TradeId);
            command.AddParameter("@orderType", (int)takeProfitOrder.OrderType);
            command.AddDateTimeToTextParameter("@executeTime", takeProfitOrder.ExecuteTime);
            command.AddDecimalToTextParameter("@orderPrice", takeProfitOrder.OrderPrice);
            command.AddDecimalToTextParameter("@filledPrice", takeProfitOrder.FilledPrice);
            command.AddDecimalToTextParameter("@orderQuantity", takeProfitOrder.OrderQuantity);
            command.AddDecimalToTextParameter("@filledQuantity", takeProfitOrder.FilledQuantity);
            command.AddDecimalToIntegerParameter("@orderValue",
                                                takeProfitOrder.OrderValue,
                                                DecimalToIntegerScale.OrderValue);
            command.AddDecimalToIntegerParameter("@filledValue",
                                                takeProfitOrder.FilledValue,
                                                DecimalToIntegerScale.FilledValue);
            command.AddParameter("@displayOrder", takeProfitOrder.DisplayOrder);

            var id = Convert.ToInt32((long)(await command.ExecuteScalarAsync() ?? 0));
            
            await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            ClearRecordCountCache();
            takeProfitOrder.Id = id;
            OnCreated(takeProfitOrder);

            return id;
        }
        partial void OnCreated(TakeProfitOrder takeProfitOrder);

        public async Task<bool> DeleteAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"DELETE FROM {_tableName} WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                ClearRecordCountCache();
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateAsync(TakeProfitOrder takeProfitOrder)
        {
            ArgumentNullException.ThrowIfNull(takeProfitOrder);
            ValidateOrThrow(takeProfitOrder);

            await using var connection = await GetOpenConnectionAsync();
            var existingTakeProfitOrder = await GetByIdAsync(takeProfitOrder.Id);
            bool noChanges = existingTakeProfitOrder != null
                          && existingTakeProfitOrder.OrderType == takeProfitOrder.OrderType 
                          && existingTakeProfitOrder.ExecuteTime == takeProfitOrder.ExecuteTime 
                          && existingTakeProfitOrder.OrderPrice == takeProfitOrder.OrderPrice 
                          && existingTakeProfitOrder.FilledPrice == takeProfitOrder.FilledPrice 
                          && existingTakeProfitOrder.OrderQuantity == takeProfitOrder.OrderQuantity 
                          && existingTakeProfitOrder.FilledQuantity == takeProfitOrder.FilledQuantity 
                          && existingTakeProfitOrder.OrderValue == takeProfitOrder.OrderValue 
                          && existingTakeProfitOrder.FilledValue == takeProfitOrder.FilledValue 
                          && existingTakeProfitOrder.DisplayOrder == takeProfitOrder.DisplayOrder; 

            if (noChanges)
                return false;

            await using var command = connection.CreateCommand();
            // TradeId is not updated to avoid complications with existing references,
            // so only OrderType, ExecuteTime, OrderPrice, FilledPrice, OrderQuantity, FilledQuantity, OrderValue, FilledValue, DisplayOrder are updated
            command.CommandText = @$"UPDATE {_tableName} SET
                OrderType = @orderType, 
                ExecuteTime = @executeTime, 
                OrderPrice = @orderPrice, 
                FilledPrice = @filledPrice, 
                OrderQuantity = @orderQuantity, 
                FilledQuantity = @filledQuantity, 
                OrderValue = @orderValue, 
                FilledValue = @filledValue, 
                DisplayOrder = @displayOrder 
            WHERE Id = @id";

            command.AddParameter("@id", takeProfitOrder.Id);
            command.AddParameter("@orderType", (int)takeProfitOrder.OrderType);
            command.AddDateTimeToTextParameter("@executeTime", takeProfitOrder.ExecuteTime);
            command.AddDecimalToTextParameter("@orderPrice", takeProfitOrder.OrderPrice);
            command.AddDecimalToTextParameter("@filledPrice", takeProfitOrder.FilledPrice);
            command.AddDecimalToTextParameter("@orderQuantity", takeProfitOrder.OrderQuantity);
            command.AddDecimalToTextParameter("@filledQuantity", takeProfitOrder.FilledQuantity);
            command.AddDecimalToIntegerParameter("@orderValue",
                                                takeProfitOrder.OrderValue,
                                                DecimalToIntegerScale.OrderValue);
            command.AddDecimalToIntegerParameter("@filledValue",
                                                takeProfitOrder.FilledValue,
                                                DecimalToIntegerScale.FilledValue);
            command.AddParameter("@displayOrder", takeProfitOrder.DisplayOrder);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(takeProfitOrder);
            }
            
            return affectedRows > 0;
        }
        partial void OnUpdated(TakeProfitOrder takeProfitOrder);

        private static TakeProfitOrder MapTakeProfitOrder(SqliteDataReader reader)
        {
            var takeProfitOrder = new TakeProfitOrder
            {
                Id = reader.GetInt32(ColNrs.Id),
                TradeId = reader.GetInt32(ColNrs.TradeId),
                OrderType = (OrderType)reader.GetInt32(ColNrs.OrderType),
                ExecuteTime = reader.IsDBNull(ColNrs.ExecuteTime) ? null
                            : ToLocalDateTime(reader.GetString(ColNrs.ExecuteTime)),
                OrderPrice = reader.GetDecimalFromText(ColNrs.OrderPrice) ?? 0m,
                FilledPrice = reader.IsDBNull(ColNrs.FilledPrice) ? null
                            : reader.GetDecimalFromText(ColNrs.FilledPrice),
                OrderQuantity = reader.IsDBNull(ColNrs.OrderQuantity) ? null
                              : reader.GetDecimalFromText(ColNrs.OrderQuantity),
                FilledQuantity = reader.IsDBNull(ColNrs.FilledQuantity) ? null
                               : reader.GetDecimalFromText(ColNrs.FilledQuantity),
                OrderValue = reader.IsDBNull(ColNrs.OrderValue) ? null
                           : reader.GetDecimalFromInteger(ColNrs.OrderValue,
                                           DecimalToIntegerScale.OrderValue),
                FilledValue = reader.IsDBNull(ColNrs.FilledValue) ? null
                            : reader.GetDecimalFromInteger(ColNrs.FilledValue,
                                            DecimalToIntegerScale.FilledValue),
                DisplayOrder = reader.GetInt32(ColNrs.DisplayOrder)
            };

            return takeProfitOrder;
        }

        /// <summary>
        /// Contains the column numbers for each property in the SQLiteDataReader.
        /// </summary>
        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int TradeId = 1;
            public readonly static int OrderType = 2;
            public readonly static int ExecuteTime = 3;
            public readonly static int OrderPrice = 4;
            public readonly static int FilledPrice = 5;
            public readonly static int OrderQuantity = 6;
            public readonly static int FilledQuantity = 7;
            public readonly static int OrderValue = 8;
            public readonly static int FilledValue = 9;
            public readonly static int DisplayOrder = 10;
        }

        /// <summary>
        /// Contains the names of all columns in the SQLiteDataReader.
        /// </summary>
        public readonly string[] ColumnNames = new[] {
            "Id", 
            "TradeId", 
            "OrderType", 
            "ExecuteTime", 
            "OrderPrice", 
            "FilledPrice", 
            "OrderQuantity", 
            "FilledQuantity", 
            "OrderValue", 
            "FilledValue", 
            "DisplayOrder" 
        };

        /// <summary>
        /// Contains the scale values used for converting decimal properties to integer storage.
        /// </summary>
        public readonly struct DecimalToIntegerScale
        {
            public readonly static int OrderPrice = 0;
            public readonly static int FilledPrice = 0;
            public readonly static int OrderQuantity = 0;
            public readonly static int FilledQuantity = 0;
            public readonly static int OrderValue = 4;
            public readonly static int FilledValue = 4;
        }
    }

    public partial interface ITakeProfitOrderRepository
    {
        Task<IReadOnlyList<TakeProfitOrder>> GetAllAsync();
        Task<IReadOnlyList<TakeProfitOrder>> GetByTradeIdAsync(int tradeId);
        Task<TakeProfitOrder?> GetByIdAsync(int? id);
        Task<int> CreateAsync(TakeProfitOrder takeProfitOrder);
        Task<bool> DeleteAsync(int id);
        Task<bool> UpdateAsync(TakeProfitOrder takeProfitOrder);
    }
}
