//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using TD.Models;
using TD.SQLite.Extensions;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for TradeImage CRUD operations.
    /// </summary>
    public partial class TradeImageRepository : AbstractDatabaseRepository<TradeImage>, ITradeImageRepository
    {
        public TradeImageRepository(string databasePath) : base(databasePath, "TradeImages")
        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            InitializeDatabase();
            OnInitialized();
        }
        private readonly string _selectStatement;

        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "TradeImage.sql");
        }

        partial void OnInitialized();

        public async Task<IReadOnlyList<TradeImage>> GetAllAsync()
        {
            var result = new List<TradeImage>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " ORDER BY TradeId DESC, Id DESC";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var tradeImage = MapTradeImage(reader);
                result.Add(tradeImage);
            }

            return result;
        }

        public async Task<IReadOnlyList<TradeImage>> GetByTradeIdAsync(int? tradeId)
        {
            var result = new List<TradeImage>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE TradeId = @tradeId";
            command.Parameters.AddWithValue("@tradeId", tradeId);
            command.CommandText += " ORDER BY TradeId DESC, Id DESC";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var tradeImage = MapTradeImage(reader);
                result.Add(tradeImage);
            }

            return result;
        }
        

        public async Task<TradeImage?> GetByIdAsync(int? id)
        {
            if (!id.HasValue || id.Value < 1)
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var tradeImage = MapTradeImage(reader);
            
            OnLoaded(tradeImage);
            return tradeImage;
        }
        partial void OnLoaded(TradeImage tradeImage);

        public async Task<int> CreateAsync(TradeImage tradeImage)
        {
            ArgumentNullException.ThrowIfNull(tradeImage);
            ValidateOrThrow(tradeImage);

            await using var connection = await GetOpenConnectionAsync();

            await using var command = connection.CreateCommand();
            command.CommandText = @$"INSERT INTO {_tableName} ({string.Join(", ", ColumnNames[1..])})
            VALUES (@tradeId, @imageURL, @notes, @updatedAt);
            SELECT last_insert_rowid();";
            
            var nowUtc = DateTime.UtcNow;
            command.Parameters.AddWithValue("@tradeId", tradeImage.TradeId);
            command.Parameters.AddWithValue("@imageURL", tradeImage.ImageURL);
            command.AddNullableParameter("@notes", tradeImage.Notes);
            command.Parameters.AddWithValue("@updatedAt", nowUtc.ToString("O"));

            var id = Convert.ToInt32((long)(await command.ExecuteScalarAsync() ?? 0));
            
            await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            ClearRecordCountCache();
            tradeImage.Id = id;
            OnCreated(tradeImage);

            return id;
        }
        partial void OnCreated(TradeImage tradeImage);

        public async Task<bool> DeleteAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"DELETE FROM {_tableName} WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                ClearRecordCountCache();
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateAsync(TradeImage tradeImage)
        {
            ArgumentNullException.ThrowIfNull(tradeImage);
            ValidateOrThrow(tradeImage);

            await using var connection = await GetOpenConnectionAsync();
            var existingTradeImage = await GetByIdAsync(tradeImage.Id);
            bool noChanges = existingTradeImage != null
                          && existingTradeImage.ImageURL == tradeImage.ImageURL 
                          && existingTradeImage.Notes == tradeImage.Notes 
                          && existingTradeImage.UpdatedAt == tradeImage.UpdatedAt; 

            if (noChanges)
                return false;

            await using var command = connection.CreateCommand();
            // TradeId is not updated to avoid complications with existing references,
            // so only ImageURL, Notes, UpdatedAt are updated
            command.CommandText = @$"UPDATE {_tableName} SET
                ImageURL = @imageURL, 
                Notes = @notes, 
                UpdatedAt = @updatedAt 
            WHERE Id = @id";

            var nowUtc = DateTime.UtcNow;
            command.Parameters.AddWithValue("@id", tradeImage.Id);
            command.Parameters.AddWithValue("@imageURL", tradeImage.ImageURL);
            command.AddNullableParameter("@notes", tradeImage.Notes);
            command.Parameters.AddWithValue("@updatedAt", nowUtc.ToString("O"));

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(tradeImage);
            }
            
            return affectedRows > 0;
        }
        partial void OnUpdated(TradeImage tradeImage);

        private static TradeImage MapTradeImage(SqliteDataReader reader)
        {
            var tradeImage = new TradeImage
            {
                Id = reader.GetInt32(ColNrs.Id), 
                TradeId = reader.IsDBNull(ColNrs.TradeId) ? null : reader.GetInt32(ColNrs.TradeId), 
                ImageURL = reader.GetString(ColNrs.ImageURL), 
                Notes = reader.IsDBNull(ColNrs.Notes) ? null : reader.GetString(ColNrs.Notes), 
                UpdatedAt = ToLocalDateTime(reader.GetString(ColNrs.UpdatedAt)) ?? DateTime.MinValue 

            };

            return tradeImage;
        }

        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int TradeId = 1;
            public readonly static int ImageURL = 2;
            public readonly static int Notes = 3;
            public readonly static int UpdatedAt = 4;
        }

        public readonly string[] ColumnNames = new[] {
            "Id", 
            "TradeId", 
            "ImageURL", 
            "Notes", 
            "UpdatedAt" 
        };
    }

    public partial interface ITradeImageRepository
    {
        Task<IReadOnlyList<TradeImage>> GetAllAsync();
        Task<IReadOnlyList<TradeImage>> GetByTradeIdAsync(int? tradeId);
        Task<TradeImage?> GetByIdAsync(int? id);
        Task<int> CreateAsync(TradeImage tradeImage);
        Task<bool> DeleteAsync(int id);
        Task<bool> UpdateAsync(TradeImage tradeImage);
    }
}
