//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using System;
using System.Collections.Generic;
using TD.Models;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for TradeImage CRUD operations.
    /// </summary>
    public partial class TradeImageRepository : AbstractDatabaseRepository<TradeImage>
    {
        public TradeImageRepository(string databasePath) : base(databasePath, "TradeImages")
        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            InitializeDatabase();
        }
        private readonly string _selectStatement;

        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "TradeImage.sql");
        }

        public async Task<IReadOnlyList<TradeImage>> GetAllAsync()
        {
            var result = new List<TradeImage>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;

            command.CommandText += " ORDER BY TradeId DESC, Id DESC";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                result.Add(MapTradeImage(reader));
            }

            return result;
        }

        

        private static TradeImage MapTradeImage(SqliteDataReader reader)
        {
            var tradeImage = new TradeImage
            {
                Id = reader.GetInt32(ColNrs.Id), 
                TradeId = reader.IsDBNull(ColNrs.TradeId) ? null : reader.GetInt32(ColNrs.TradeId), 
                ImageURL = reader.GetString(ColNrs.ImageURL), 
                Notes = reader.IsDBNull(ColNrs.Notes) ? null : reader.GetString(ColNrs.Notes), 
                ModifyDate = ToLocalDateTime(reader.GetString(ColNrs.ModifyDate)) ?? DateTime.MinValue 

            };

            return tradeImage;
        }

        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int TradeId = 1;
            public readonly static int ImageURL = 2;
            public readonly static int Notes = 3;
            public readonly static int ModifyDate = 4;
        }

        public readonly string[] ColumnNames = new[] {
            "Id", 
            "TradeId", 
            "ImageURL", 
            "Notes", 
            "ModifyDate" 
        };
    }
}
