//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using TD.Helpers;
using TD.Models;
using TD.RepositoryContracts;
using TD.SQLite.Extensions;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for Trade CRUD operations.
    /// </summary>
    public partial class TradeRepository : AbstractDatabaseRepository<Trade>, ITradeRepository
    {
        public TradeRepository(string databasePath, IEntryOrderRepository? entryOrderRepository = null,
                               IStopLossOrderRepository? stopLossOrderRepository = null, ISymbolRepository? symbolRepository = null,
                               ITakeProfitOrderRepository? takeProfitOrderRepository = null, ITradeImageRepository? tradeImageRepository = null,
                               ITradingAccountRepository? tradingAccountRepository = null) : base(databasePath, "Trades")

        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            _databasePath = databasePath;
            if (entryOrderRepository != null)
                _entryOrderRepository = entryOrderRepository;
            if (stopLossOrderRepository != null)
                _stopLossOrderRepository = stopLossOrderRepository;
            if (symbolRepository != null)
                _symbolRepository = symbolRepository;
            if (takeProfitOrderRepository != null)
                _takeProfitOrderRepository = takeProfitOrderRepository;
            if (tradeImageRepository != null)
                _tradeImageRepository = tradeImageRepository;
            if (tradingAccountRepository != null)
                _tradingAccountRepository = tradingAccountRepository;

            InitializeDatabase();
            OnInitialized(entryOrderRepository == null, stopLossOrderRepository == null, symbolRepository == null,
                          takeProfitOrderRepository == null, tradeImageRepository == null, tradingAccountRepository == null);
        }
        private readonly string _databasePath;
        private readonly string _selectStatement;

        protected IEntryOrderRepository EntryOrderRepository
        {
            get
            {
                if (_entryOrderRepository == null)
                {
                    _entryOrderRepository = new EntryOrderRepository(_databasePath);
                }
                return _entryOrderRepository;
            }
        }
        private IEntryOrderRepository? _entryOrderRepository;

        protected IStopLossOrderRepository StopLossOrderRepository
        {
            get
            {
                if (_stopLossOrderRepository == null)
                {
                    _stopLossOrderRepository = new StopLossOrderRepository(_databasePath);
                }
                return _stopLossOrderRepository;
            }
        }
        private IStopLossOrderRepository? _stopLossOrderRepository;

        protected ISymbolRepository SymbolRepository
        {
            get
            {
                if (_symbolRepository == null)
                {
                    _symbolRepository = new SymbolRepository(_databasePath);
                }
                return _symbolRepository;
            }
        }
        private ISymbolRepository? _symbolRepository;

        protected ITakeProfitOrderRepository TakeProfitOrderRepository
        {
            get
            {
                if (_takeProfitOrderRepository == null)
                {
                    _takeProfitOrderRepository = new TakeProfitOrderRepository(_databasePath);
                }
                return _takeProfitOrderRepository;
            }
        }
        private ITakeProfitOrderRepository? _takeProfitOrderRepository;

        protected ITradeImageRepository TradeImageRepository
        {
            get
            {
                if (_tradeImageRepository == null)
                {
                    _tradeImageRepository = new TradeImageRepository(_databasePath);
                }
                return _tradeImageRepository;
            }
        }
        private ITradeImageRepository? _tradeImageRepository;

        protected ITradingAccountRepository TradingAccountRepository
        {
            get
            {
                if (_tradingAccountRepository == null)
                {
                    _tradingAccountRepository = new TradingAccountRepository(_databasePath);
                }
                return _tradingAccountRepository;
            }
        }
        private ITradingAccountRepository? _tradingAccountRepository;


        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "Trade.sql");
        }

        /// <summary>
        /// Initialization hook for additional setup after the repository is constructed.
        /// The parameters indicate whether the corresponding repository was created by this repository (true) or provided externally (false),
        /// which can be useful to determine if any additional initialization or event wiring is needed.
        /// </summary>
        partial void OnInitialized(bool isEntryOrderRepository, bool isStopLossOrderRepository, bool isSymbolRepository,
                                   bool isTakeProfitOrderRepository, bool isTradeImageRepository, bool isTradingAccountRepository);

        public async Task<IReadOnlyList<Trade>> GetAllAsync()
        {
            var result = new List<Trade>();
            var symbolsById = (await SymbolRepository.GetAllAsync()).ToDictionary(item => item.Id);
            var tradingAccountsById = (await TradingAccountRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " ORDER BY UpdatedAt DESC, EntryTime DESC";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var trade = MapTrade(reader);
                if (symbolsById.TryGetValue(trade.SymbolId, out var symbol))
                    trade.Symbol = symbol;

                if (tradingAccountsById.TryGetValue(trade.TradingAccountId, out var tradingAccount))
                    trade.TradingAccount = tradingAccount;

                result.Add(trade);
            }

            return result;
        }

        public async Task<bool> AnyBySymbolIdAsync(int symbolId)
        {
            if (symbolId < 1)
                return false;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"SELECT COUNT(1) FROM {_tableName} WHERE SymbolId = @symbolId";
            command.Parameters.AddWithValue("@symbolId", symbolId);
            var result = await command.ExecuteScalarAsync();
            return Convert.ToInt64(result) > 0;
        }


        public async Task<IReadOnlyList<Trade>> GetBySymbolIdAsync(int symbolId)
        {
            var result = new List<Trade>();
            var symbolsById = (await SymbolRepository.GetAllAsync()).ToDictionary(item => item.Id);
            var tradingAccountsById = (await TradingAccountRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE SymbolId = @symbolId";
            command.AddParameter("@symbolId", symbolId);
            command.CommandText += " ORDER BY UpdatedAt DESC, EntryTime DESC";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var trade = MapTrade(reader);
                if (symbolsById.TryGetValue(trade.SymbolId, out var symbol))
                    trade.Symbol = symbol;

                if (tradingAccountsById.TryGetValue(trade.TradingAccountId, out var tradingAccount))
                    trade.TradingAccount = tradingAccount;

                result.Add(trade);
            }

            return result;
        }


        public async Task<bool> AnyByTradingAccountIdAsync(int tradingAccountId)
        {
            if (tradingAccountId < 1)
                return false;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"SELECT COUNT(1) FROM {_tableName} WHERE TradingAccountId = @tradingAccountId";
            command.Parameters.AddWithValue("@tradingAccountId", tradingAccountId);
            var result = await command.ExecuteScalarAsync();
            return Convert.ToInt64(result) > 0;
        }


        public async Task<IReadOnlyList<Trade>> GetByTradingAccountIdAsync(int tradingAccountId)
        {
            var result = new List<Trade>();
            var symbolsById = (await SymbolRepository.GetAllAsync()).ToDictionary(item => item.Id);
            var tradingAccountsById = (await TradingAccountRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE TradingAccountId = @tradingAccountId";
            command.AddParameter("@tradingAccountId", tradingAccountId);
            command.CommandText += " ORDER BY UpdatedAt DESC, EntryTime DESC";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var trade = MapTrade(reader);
                if (symbolsById.TryGetValue(trade.SymbolId, out var symbol))
                    trade.Symbol = symbol;

                if (tradingAccountsById.TryGetValue(trade.TradingAccountId, out var tradingAccount))
                    trade.TradingAccount = tradingAccount;

                result.Add(trade);
            }

            return result;
        }


        public async Task<Trade?> GetByIdAsync(int? id)
        {
            if (!id.HasValue || id.Value < 1)
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var trade = MapTrade(reader);
            await LoadSymbolAsync(trade);
            await LoadTradingAccountAsync(trade);

            OnLoaded(trade);
            return trade;
        }
        partial void OnLoaded(Trade trade);

        public async Task<IReadOnlyList<Trade>> GetPagedAsync(TradeQueryParameters queryParameters)
        {
            ArgumentNullException.ThrowIfNull(queryParameters);

            var result = new List<Trade>();
            var symbolsById = (await SymbolRepository.GetAllAsync()).ToDictionary(item => item.Id);
            var tradingAccountsById = (await TradingAccountRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            AppendWhere(queryParameters, command);

            command.CommandText += " ORDER BY UpdatedAt DESC, EntryTime DESC";
            command.CommandText += " LIMIT @pageSize OFFSET @skip";
            command.Parameters.AddWithValue("@pageSize", queryParameters.PageSize);
            command.Parameters.AddWithValue("@skip", queryParameters.Skip);

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var trade = MapTrade(reader);
                if (symbolsById.TryGetValue(trade.SymbolId, out var symbol))
                    trade.Symbol = symbol;

                if (tradingAccountsById.TryGetValue(trade.TradingAccountId, out var tradingAccount))
                    trade.TradingAccount = tradingAccount;

                result.Add(trade);
            }
            
            await using var countCommand = connection.CreateCommand();
            countCommand.CommandText = $"SELECT COUNT(1) FROM {_tableName}";
            AppendWhere(queryParameters, countCommand);
            queryParameters.TotalCount = Convert.ToInt64(await countCommand.ExecuteScalarAsync());

            return result;
        }

        private static void AppendWhere(TradeQueryParameters queryParameters, SqliteCommand command)
        {
            var whereClauses = new List<string>();

            if (queryParameters.TradingAccountId.HasValue)
            {
                whereClauses.Add("TradingAccountId = @tradingAccountId");
                command.AddParameter("@tradingAccountId", queryParameters.TradingAccountId.Value);
            }
            if (queryParameters.SymbolId.HasValue)
            {
                whereClauses.Add("SymbolId = @symbolId");
                command.AddParameter("@symbolId", queryParameters.SymbolId.Value);
            }
            if (queryParameters.TradeDirection.HasValue)
            {
                whereClauses.Add("TradeDirection = @tradeDirection");
                command.AddParameter("@tradeDirection", (int)queryParameters.TradeDirection.Value);
            }
            if (queryParameters.EntryMethod.HasValue)
            {
                whereClauses.Add("EntryMethod = @entryMethod");
                command.AddParameter("@entryMethod", (int)queryParameters.EntryMethod.Value);
            }
            if (queryParameters.IsFullyClosed.HasValue)
            {
                whereClauses.Add("IsFullyClosed = @isFullyClosed");
                command.AddParameter("@isFullyClosed", queryParameters.IsFullyClosed.Value);
            }
            if (queryParameters.EntryTimeMin.HasValue)
            {
                whereClauses.Add("EntryTime >= @entryTimeMin");
                command.AddDateTimeToTextParameter("@entryTimeMin", queryParameters.EntryTimeMin.Value);
            }
            if (queryParameters.EntryTimeMax.HasValue)
            {
                whereClauses.Add("EntryTime <= @entryTimeMax");
                command.AddDateTimeToTextParameter("@entryTimeMax", queryParameters.EntryTimeMax.Value);
            }
            if (queryParameters.PlannedPositionValueMin.HasValue)
            {
                whereClauses.Add("PlannedPositionValue >= @plannedPositionValueMin");
                command.AddDecimalToIntegerParameter("@plannedPositionValueMin",
                                                    queryParameters.PlannedPositionValueMin.Value,
                                                    DecimalToIntegerScale.PlannedPositionValue);
            }
            if (queryParameters.PlannedPositionValueMax.HasValue)
            {
                whereClauses.Add("PlannedPositionValue <= @plannedPositionValueMax");
                command.AddDecimalToIntegerParameter("@plannedPositionValueMax",
                                                    queryParameters.PlannedPositionValueMax.Value,
                                                    DecimalToIntegerScale.PlannedPositionValue);
            }
            if (queryParameters.ExecutedPositionValueMin.HasValue)
            {
                whereClauses.Add("ExecutedPositionValue >= @executedPositionValueMin");
                command.AddDecimalToIntegerParameter("@executedPositionValueMin",
                                                    queryParameters.ExecutedPositionValueMin.Value,
                                                    DecimalToIntegerScale.ExecutedPositionValue);
            }
            if (queryParameters.ExecutedPositionValueMax.HasValue)
            {
                whereClauses.Add("ExecutedPositionValue <= @executedPositionValueMax");
                command.AddDecimalToIntegerParameter("@executedPositionValueMax",
                                                    queryParameters.ExecutedPositionValueMax.Value,
                                                    DecimalToIntegerScale.ExecutedPositionValue);
            }
            if (queryParameters.RemainingPositionValueMin.HasValue)
            {
                whereClauses.Add("RemainingPositionValue >= @remainingPositionValueMin");
                command.AddDecimalToIntegerParameter("@remainingPositionValueMin",
                                                    queryParameters.RemainingPositionValueMin.Value,
                                                    DecimalToIntegerScale.RemainingPositionValue);
            }
            if (queryParameters.RemainingPositionValueMax.HasValue)
            {
                whereClauses.Add("RemainingPositionValue <= @remainingPositionValueMax");
                command.AddDecimalToIntegerParameter("@remainingPositionValueMax",
                                                    queryParameters.RemainingPositionValueMax.Value,
                                                    DecimalToIntegerScale.RemainingPositionValue);
            }
            if (queryParameters.PlannedProfitMin.HasValue)
            {
                whereClauses.Add("PlannedProfit >= @plannedProfitMin");
                command.AddDecimalToIntegerParameter("@plannedProfitMin",
                                                    queryParameters.PlannedProfitMin.Value,
                                                    DecimalToIntegerScale.PlannedProfit);
            }
            if (queryParameters.PlannedProfitMax.HasValue)
            {
                whereClauses.Add("PlannedProfit <= @plannedProfitMax");
                command.AddDecimalToIntegerParameter("@plannedProfitMax",
                                                    queryParameters.PlannedProfitMax.Value,
                                                    DecimalToIntegerScale.PlannedProfit);
            }
            if (queryParameters.PlannedRiskAmountMin.HasValue)
            {
                whereClauses.Add("PlannedRiskAmount >= @plannedRiskAmountMin");
                command.AddDecimalToIntegerParameter("@plannedRiskAmountMin",
                                                    queryParameters.PlannedRiskAmountMin.Value,
                                                    DecimalToIntegerScale.PlannedRiskAmount);
            }
            if (queryParameters.PlannedRiskAmountMax.HasValue)
            {
                whereClauses.Add("PlannedRiskAmount <= @plannedRiskAmountMax");
                command.AddDecimalToIntegerParameter("@plannedRiskAmountMax",
                                                    queryParameters.PlannedRiskAmountMax.Value,
                                                    DecimalToIntegerScale.PlannedRiskAmount);
            }
            if (queryParameters.RealizedProfitLossMin.HasValue)
            {
                whereClauses.Add("RealizedProfitLoss >= @realizedProfitLossMin");
                command.AddDecimalToIntegerParameter("@realizedProfitLossMin",
                                                    queryParameters.RealizedProfitLossMin.Value,
                                                    DecimalToIntegerScale.RealizedProfitLoss);
            }
            if (queryParameters.RealizedProfitLossMax.HasValue)
            {
                whereClauses.Add("RealizedProfitLoss <= @realizedProfitLossMax");
                command.AddDecimalToIntegerParameter("@realizedProfitLossMax",
                                                    queryParameters.RealizedProfitLossMax.Value,
                                                    DecimalToIntegerScale.RealizedProfitLoss);
            }
            if (queryParameters.UpdatedAtMin.HasValue)
            {
                whereClauses.Add("UpdatedAt >= @updatedAtMin");
                command.AddDateTimeToTextParameter("@updatedAtMin", queryParameters.UpdatedAtMin.Value);
            }
            if (queryParameters.UpdatedAtMax.HasValue)
            {
                whereClauses.Add("UpdatedAt <= @updatedAtMax");
                command.AddDateTimeToTextParameter("@updatedAtMax", queryParameters.UpdatedAtMax.Value);
            }

            if (whereClauses.Count > 0)
            {
                var whereClause = string.Join(" AND ", whereClauses);
                command.CommandText += " WHERE ";
                command.CommandText += whereClause;
            }
        }

        public async Task<int> CreateAsync(Trade trade)
        {
            ArgumentNullException.ThrowIfNull(trade);
            ValidateOrThrow(trade);

            await using var connection = await GetOpenConnectionAsync();

            await using var command = connection.CreateCommand();
            command.CommandText = @$"INSERT INTO {_tableName} ({string.Join(", ", ColumnNames[1..])})
            VALUES (@tradingAccountId, @symbolId, @tradeDirection, @entryMethod, @tags, @marketType,
                    @entryTime, @exitTime, @plannedPositionValue, @executedPositionValue, @isFullyClosed, @plannedEntryPrice,
                    @executedEntryPrice, @orderQuantity, @filledQuantity, @remainingPositionValue, @plannedProfit, @plannedTP,
                    @executedTP, @plannedSL, @executedSL, @plannedRiskAmount, @plannedRiskRewardRatio, @realizedProfitLoss,
                    @realizedRiskAmount, @setupNotes, @reviewNotes, @updatedAt);
            SELECT last_insert_rowid();";

            command.AddParameter("@tradingAccountId", trade.TradingAccountId);
            command.AddParameter("@symbolId", trade.SymbolId);
            command.AddParameter("@tradeDirection", (int)trade.TradeDirection);
            command.AddParameter("@entryMethod", (int)trade.EntryMethod);
            command.AddNullableParameter("@tags", trade.Tags);
            command.AddParameter("@marketType", (int)trade.MarketType);
            command.AddDateTimeToTextParameter("@entryTime", trade.EntryTime);
            command.AddDateTimeToTextParameter("@exitTime", trade.ExitTime);
            command.AddDecimalToIntegerParameter("@plannedPositionValue",
                                                trade.PlannedPositionValue,
                                                DecimalToIntegerScale.PlannedPositionValue);
            command.AddDecimalToIntegerParameter("@executedPositionValue",
                                                trade.ExecutedPositionValue,
                                                DecimalToIntegerScale.ExecutedPositionValue);
            command.AddParameter("@isFullyClosed", trade.IsFullyClosed);
            command.AddDecimalToTextParameter("@plannedEntryPrice", trade.PlannedEntryPrice);
            command.AddDecimalToTextParameter("@executedEntryPrice", trade.ExecutedEntryPrice);
            command.AddDecimalToTextParameter("@orderQuantity", trade.OrderQuantity);
            command.AddDecimalToTextParameter("@filledQuantity", trade.FilledQuantity);
            command.AddDecimalToIntegerParameter("@remainingPositionValue",
                                                trade.RemainingPositionValue,
                                                DecimalToIntegerScale.RemainingPositionValue);
            command.AddDecimalToIntegerParameter("@plannedProfit",
                                                trade.PlannedProfit,
                                                DecimalToIntegerScale.PlannedProfit);
            command.AddDecimalToTextParameter("@plannedTP", trade.PlannedTP);
            command.AddDecimalToTextParameter("@executedTP", trade.ExecutedTP);
            command.AddDecimalToTextParameter("@plannedSL", trade.PlannedSL);
            command.AddDecimalToTextParameter("@executedSL", trade.ExecutedSL);
            command.AddDecimalToIntegerParameter("@plannedRiskAmount",
                                                trade.PlannedRiskAmount,
                                                DecimalToIntegerScale.PlannedRiskAmount);
            command.AddDecimalToTextParameter("@plannedRiskRewardRatio", trade.PlannedRiskRewardRatio);
            command.AddDecimalToIntegerParameter("@realizedProfitLoss",
                                                trade.RealizedProfitLoss,
                                                DecimalToIntegerScale.RealizedProfitLoss);
            command.AddDecimalToIntegerParameter("@realizedRiskAmount",
                                                trade.RealizedRiskAmount,
                                                DecimalToIntegerScale.RealizedRiskAmount);
            command.AddNullableParameter("@setupNotes", trade.SetupNotes);
            command.AddNullableParameter("@reviewNotes", trade.ReviewNotes);
            command.AddDateTimeToTextParameter("@updatedAt", DateTime.Now);

            var id = Convert.ToInt32((long)(await command.ExecuteScalarAsync() ?? 0));

            await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            ClearRecordCountCache();
            trade.Id = id;
            OnCreated(trade);

            return id;
        }
        partial void OnCreated(Trade trade);

        /// <summary>
        /// Determines whether a trade can be safely deleted based on the absence of related records.
        /// </summary>
        /// <remarks>A trade can be deleted only if there are no associated records. Use this method
        /// before attempting to delete a trade to avoid violating referential integrity.</remarks>
        /// <param name="id">The identifier of the trade record to check for deletability.</param>
        /// <returns>A task that represents the asynchronous operation. The task result is <see langword="true"/> if the trade
        /// can be deleted; otherwise, <see langword="false"/>.</returns>
        public async Task<bool> CanDeleteAsync(int id)
        {
            if (id < 1)
                return false;

            bool result = true;

            // Checking any entryOrder record exists through EntryOrder.TradeId reference
            result = result && !(await EntryOrderRepository.AnyByTradeIdAsync(id));

            // Checking any takeProfitOrder record exists through TakeProfitOrder.TradeId reference
            result = result && !(await TakeProfitOrderRepository.AnyByTradeIdAsync(id));

            // Checking any stopLossOrder record exists through StopLossOrder.TradeId reference
            result = result && !(await StopLossOrderRepository.AnyByTradeIdAsync(id));

            // Checking any tradeImage record exists through TradeImage.TradeId reference
            result = result && !(await TradeImageRepository.AnyByTradeIdAsync(id));

            return result;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"DELETE FROM {_tableName} WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                ClearRecordCountCache();
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateAsync(Trade trade)
        {
            ArgumentNullException.ThrowIfNull(trade);
            ValidateOrThrow(trade);

            await using var connection = await GetOpenConnectionAsync();
            var existingTrade = await GetByIdAsync(trade.Id);
            bool noChanges = existingTrade != null
                          && existingTrade.EntryMethod == trade.EntryMethod
                          && existingTrade.Tags == trade.Tags
                          && existingTrade.MarketType == trade.MarketType
                          && existingTrade.PlannedPositionValue == trade.PlannedPositionValue
                          && existingTrade.ExecutedPositionValue == trade.ExecutedPositionValue
                          && existingTrade.IsFullyClosed == trade.IsFullyClosed
                          && existingTrade.PlannedEntryPrice == trade.PlannedEntryPrice
                          && existingTrade.ExecutedEntryPrice == trade.ExecutedEntryPrice
                          && existingTrade.OrderQuantity == trade.OrderQuantity
                          && existingTrade.FilledQuantity == trade.FilledQuantity
                          && existingTrade.RemainingPositionValue == trade.RemainingPositionValue
                          && existingTrade.PlannedProfit == trade.PlannedProfit
                          && existingTrade.PlannedTP == trade.PlannedTP
                          && existingTrade.ExecutedTP == trade.ExecutedTP
                          && existingTrade.PlannedSL == trade.PlannedSL
                          && existingTrade.ExecutedSL == trade.ExecutedSL
                          && existingTrade.PlannedRiskAmount == trade.PlannedRiskAmount
                          && existingTrade.PlannedRiskRewardRatio == trade.PlannedRiskRewardRatio
                          && existingTrade.RealizedProfitLoss == trade.RealizedProfitLoss
                          && existingTrade.RealizedRiskAmount == trade.RealizedRiskAmount
                          && existingTrade.UpdatedAt == trade.UpdatedAt;

            if (noChanges)
                return false;

            await using var command = connection.CreateCommand();
            // TradingAccountId, SymbolId, TradeDirection, EntryTime, ExitTime, SetupNotes, ReviewNotes are not updated to avoid complications with existing references,
            // so only EntryMethod, Tags, MarketType, PlannedPositionValue, ExecutedPositionValue, IsFullyClosed, PlannedEntryPrice, ExecutedEntryPrice, OrderQuantity, FilledQuantity, RemainingPositionValue, PlannedProfit, PlannedTP, ExecutedTP, PlannedSL, ExecutedSL, PlannedRiskAmount, PlannedRiskRewardRatio, RealizedProfitLoss, RealizedRiskAmount, UpdatedAt are updated
            command.CommandText = @$"UPDATE {_tableName} SET
                EntryMethod = @entryMethod,
                Tags = @tags,
                MarketType = @marketType,
                PlannedPositionValue = @plannedPositionValue,
                ExecutedPositionValue = @executedPositionValue,
                IsFullyClosed = @isFullyClosed,
                PlannedEntryPrice = @plannedEntryPrice,
                ExecutedEntryPrice = @executedEntryPrice,
                OrderQuantity = @orderQuantity,
                FilledQuantity = @filledQuantity,
                RemainingPositionValue = @remainingPositionValue,
                PlannedProfit = @plannedProfit,
                PlannedTP = @plannedTP,
                ExecutedTP = @executedTP,
                PlannedSL = @plannedSL,
                ExecutedSL = @executedSL,
                PlannedRiskAmount = @plannedRiskAmount,
                PlannedRiskRewardRatio = @plannedRiskRewardRatio,
                RealizedProfitLoss = @realizedProfitLoss,
                RealizedRiskAmount = @realizedRiskAmount,
                UpdatedAt = @updatedAt
            WHERE Id = @id";

            command.AddParameter("@id", trade.Id);
            command.AddParameter("@entryMethod", (int)trade.EntryMethod);
            command.AddNullableParameter("@tags", trade.Tags);
            command.AddParameter("@marketType", (int)trade.MarketType);
            command.AddDecimalToIntegerParameter("@plannedPositionValue",
                                                trade.PlannedPositionValue,
                                                DecimalToIntegerScale.PlannedPositionValue);
            command.AddDecimalToIntegerParameter("@executedPositionValue",
                                                trade.ExecutedPositionValue,
                                                DecimalToIntegerScale.ExecutedPositionValue);
            command.AddParameter("@isFullyClosed", trade.IsFullyClosed);
            command.AddDecimalToTextParameter("@plannedEntryPrice", trade.PlannedEntryPrice);
            command.AddDecimalToTextParameter("@executedEntryPrice", trade.ExecutedEntryPrice);
            command.AddDecimalToTextParameter("@orderQuantity", trade.OrderQuantity);
            command.AddDecimalToTextParameter("@filledQuantity", trade.FilledQuantity);
            command.AddDecimalToIntegerParameter("@remainingPositionValue",
                                                trade.RemainingPositionValue,
                                                DecimalToIntegerScale.RemainingPositionValue);
            command.AddDecimalToIntegerParameter("@plannedProfit",
                                                trade.PlannedProfit,
                                                DecimalToIntegerScale.PlannedProfit);
            command.AddDecimalToTextParameter("@plannedTP", trade.PlannedTP);
            command.AddDecimalToTextParameter("@executedTP", trade.ExecutedTP);
            command.AddDecimalToTextParameter("@plannedSL", trade.PlannedSL);
            command.AddDecimalToTextParameter("@executedSL", trade.ExecutedSL);
            command.AddDecimalToIntegerParameter("@plannedRiskAmount",
                                                trade.PlannedRiskAmount,
                                                DecimalToIntegerScale.PlannedRiskAmount);
            command.AddDecimalToTextParameter("@plannedRiskRewardRatio", trade.PlannedRiskRewardRatio);
            command.AddDecimalToIntegerParameter("@realizedProfitLoss",
                                                trade.RealizedProfitLoss,
                                                DecimalToIntegerScale.RealizedProfitLoss);
            command.AddDecimalToIntegerParameter("@realizedRiskAmount",
                                                trade.RealizedRiskAmount,
                                                DecimalToIntegerScale.RealizedRiskAmount);
            command.AddDateTimeToTextParameter("@updatedAt", DateTime.Now);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(trade);
            }

            return affectedRows > 0;
        }
        partial void OnUpdated(Trade trade);
        partial void OnUpdated(int tradeId);

        public async Task<bool> UpdateEntryTimeAsync(int id, DateTime entryTime)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = @$"UPDATE {_tableName} SET
                EntryTime = @entryTime,                UpdatedAt = @updatedAt            WHERE Id = @id";

            command.AddParameter("@id", id);
            command.AddDateTimeToTextParameter("@entryTime", entryTime);
            command.AddDateTimeToTextParameter("@updatedAt", DateTime.Now);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(id);
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateExitTimeAsync(int id, DateTime exitTime)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = @$"UPDATE {_tableName} SET
                ExitTime = @exitTime,                UpdatedAt = @updatedAt            WHERE Id = @id";

            command.AddParameter("@id", id);
            command.AddDateTimeToTextParameter("@exitTime", exitTime);
            command.AddDateTimeToTextParameter("@updatedAt", DateTime.Now);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(id);
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateReviewNotesAsync(int id, string reviewNotes)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = @$"UPDATE {_tableName} SET
                ReviewNotes = @reviewNotes,                UpdatedAt = @updatedAt            WHERE Id = @id";

            command.AddParameter("@id", id);
            command.AddNullableParameter("@reviewNotes", reviewNotes);
            command.AddDateTimeToTextParameter("@updatedAt", DateTime.Now);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(id);
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateSetupNotesAsync(int id, string setupNotes)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = @$"UPDATE {_tableName} SET
                SetupNotes = @setupNotes,                UpdatedAt = @updatedAt            WHERE Id = @id";

            command.AddParameter("@id", id);
            command.AddNullableParameter("@setupNotes", setupNotes);
            command.AddDateTimeToTextParameter("@updatedAt", DateTime.Now);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(id);
            }

            return affectedRows > 0;
        }

        private async Task LoadSymbolAsync(Trade trade)
        {
            trade.Symbol = await SymbolRepository.GetByIdAsync(trade.SymbolId)
                            ?? new Symbol { Id = trade.SymbolId };
        }


        private async Task LoadTradingAccountAsync(Trade trade)
        {
            trade.TradingAccount = await TradingAccountRepository.GetByIdAsync(trade.TradingAccountId)
                            ?? new TradingAccount { Id = trade.TradingAccountId };
        }


        private static Trade MapTrade(SqliteDataReader reader)
        {
            var trade = new Trade
            {
                Id = reader.GetInt32(ColNrs.Id),
                TradingAccountId = reader.GetInt32(ColNrs.TradingAccountId),
                SymbolId = reader.GetInt32(ColNrs.SymbolId),
                TradeDirection = (TradeDirection)reader.GetInt32(ColNrs.TradeDirection),
                EntryMethod = (EntryMethod)reader.GetInt32(ColNrs.EntryMethod),
                Tags = reader.IsDBNull(ColNrs.Tags) ? null
                     : reader.GetString(ColNrs.Tags),
                MarketType = (MarketType)reader.GetInt32(ColNrs.MarketType),
                EntryTime = reader.IsDBNull(ColNrs.EntryTime) ? null
                          : ToLocalDateTime(reader.GetString(ColNrs.EntryTime)),
                ExitTime = reader.IsDBNull(ColNrs.ExitTime) ? null
                         : ToLocalDateTime(reader.GetString(ColNrs.ExitTime)),
                PlannedPositionValue = reader.IsDBNull(ColNrs.PlannedPositionValue) ? null
                                     : reader.GetDecimalFromInteger(ColNrs.PlannedPositionValue,
                                                     DecimalToIntegerScale.PlannedPositionValue),
                ExecutedPositionValue = reader.IsDBNull(ColNrs.ExecutedPositionValue) ? null
                                      : reader.GetDecimalFromInteger(ColNrs.ExecutedPositionValue,
                                                      DecimalToIntegerScale.ExecutedPositionValue),
                IsFullyClosed = reader.GetInt64(ColNrs.IsFullyClosed) == 1,
                PlannedEntryPrice = reader.IsDBNull(ColNrs.PlannedEntryPrice) ? null
                                  : reader.GetDecimalFromText(ColNrs.PlannedEntryPrice),
                ExecutedEntryPrice = reader.IsDBNull(ColNrs.ExecutedEntryPrice) ? null
                                   : reader.GetDecimalFromText(ColNrs.ExecutedEntryPrice),
                OrderQuantity = reader.IsDBNull(ColNrs.OrderQuantity) ? null
                              : reader.GetDecimalFromText(ColNrs.OrderQuantity),
                FilledQuantity = reader.IsDBNull(ColNrs.FilledQuantity) ? null
                               : reader.GetDecimalFromText(ColNrs.FilledQuantity),
                RemainingPositionValue = reader.IsDBNull(ColNrs.RemainingPositionValue) ? null
                                       : reader.GetDecimalFromInteger(ColNrs.RemainingPositionValue,
                                                       DecimalToIntegerScale.RemainingPositionValue),
                PlannedProfit = reader.IsDBNull(ColNrs.PlannedProfit) ? null
                              : reader.GetDecimalFromInteger(ColNrs.PlannedProfit,
                                              DecimalToIntegerScale.PlannedProfit),
                PlannedTP = reader.IsDBNull(ColNrs.PlannedTP) ? null
                          : reader.GetDecimalFromText(ColNrs.PlannedTP),
                ExecutedTP = reader.IsDBNull(ColNrs.ExecutedTP) ? null
                           : reader.GetDecimalFromText(ColNrs.ExecutedTP),
                PlannedSL = reader.IsDBNull(ColNrs.PlannedSL) ? null
                          : reader.GetDecimalFromText(ColNrs.PlannedSL),
                ExecutedSL = reader.IsDBNull(ColNrs.ExecutedSL) ? null
                           : reader.GetDecimalFromText(ColNrs.ExecutedSL),
                PlannedRiskAmount = reader.IsDBNull(ColNrs.PlannedRiskAmount) ? null
                                  : reader.GetDecimalFromInteger(ColNrs.PlannedRiskAmount,
                                                  DecimalToIntegerScale.PlannedRiskAmount),
                PlannedRiskRewardRatio = reader.IsDBNull(ColNrs.PlannedRiskRewardRatio) ? null
                                       : reader.GetDecimalFromText(ColNrs.PlannedRiskRewardRatio),
                RealizedProfitLoss = reader.IsDBNull(ColNrs.RealizedProfitLoss) ? null
                                   : reader.GetDecimalFromInteger(ColNrs.RealizedProfitLoss,
                                                   DecimalToIntegerScale.RealizedProfitLoss),
                RealizedRiskAmount = reader.IsDBNull(ColNrs.RealizedRiskAmount) ? null
                                   : reader.GetDecimalFromInteger(ColNrs.RealizedRiskAmount,
                                                   DecimalToIntegerScale.RealizedRiskAmount),
                SetupNotes = reader.IsDBNull(ColNrs.SetupNotes) ? null
                           : reader.GetString(ColNrs.SetupNotes),
                ReviewNotes = reader.IsDBNull(ColNrs.ReviewNotes) ? null
                            : reader.GetString(ColNrs.ReviewNotes),
                UpdatedAt = ToLocalDateTime(reader.GetString(ColNrs.UpdatedAt)) ?? DateTime.MinValue
            };

            return trade;
        }

        /// <summary>
        /// Contains the column numbers for each property in the SQLiteDataReader.
        /// </summary>
        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int TradingAccountId = 1;
            public readonly static int SymbolId = 2;
            public readonly static int TradeDirection = 3;
            public readonly static int EntryMethod = 4;
            public readonly static int Tags = 5;
            public readonly static int MarketType = 6;
            public readonly static int EntryTime = 7;
            public readonly static int ExitTime = 8;
            public readonly static int PlannedPositionValue = 9;
            public readonly static int ExecutedPositionValue = 10;
            public readonly static int IsFullyClosed = 11;
            public readonly static int PlannedEntryPrice = 12;
            public readonly static int ExecutedEntryPrice = 13;
            public readonly static int OrderQuantity = 14;
            public readonly static int FilledQuantity = 15;
            public readonly static int RemainingPositionValue = 16;
            public readonly static int PlannedProfit = 17;
            public readonly static int PlannedTP = 18;
            public readonly static int ExecutedTP = 19;
            public readonly static int PlannedSL = 20;
            public readonly static int ExecutedSL = 21;
            public readonly static int PlannedRiskAmount = 22;
            public readonly static int PlannedRiskRewardRatio = 23;
            public readonly static int RealizedProfitLoss = 24;
            public readonly static int RealizedRiskAmount = 25;
            public readonly static int SetupNotes = 26;
            public readonly static int ReviewNotes = 27;
            public readonly static int UpdatedAt = 28;
        }

        /// <summary>
        /// Contains the names of all columns in the SQLiteDataReader.
        /// </summary>
        public readonly string[] ColumnNames = new[] {
            "Id",
            "TradingAccountId",
            "SymbolId",
            "TradeDirection",
            "EntryMethod",
            "Tags",
            "MarketType",
            "EntryTime",
            "ExitTime",
            "PlannedPositionValue",
            "ExecutedPositionValue",
            "IsFullyClosed",
            "PlannedEntryPrice",
            "ExecutedEntryPrice",
            "OrderQuantity",
            "FilledQuantity",
            "RemainingPositionValue",
            "PlannedProfit",
            "PlannedTP",
            "ExecutedTP",
            "PlannedSL",
            "ExecutedSL",
            "PlannedRiskAmount",
            "PlannedRiskRewardRatio",
            "RealizedProfitLoss",
            "RealizedRiskAmount",
            "SetupNotes",
            "ReviewNotes",
            "UpdatedAt"
        };

        /// <summary>
        /// Contains the scale values used for converting decimal properties to integer storage.
        /// </summary>
        public readonly struct DecimalToIntegerScale
        {
            public readonly static int PlannedPositionValue = 4;
            public readonly static int ExecutedPositionValue = 4;
            public readonly static int PlannedEntryPrice = 0;
            public readonly static int ExecutedEntryPrice = 0;
            public readonly static int OrderQuantity = 0;
            public readonly static int FilledQuantity = 0;
            public readonly static int RemainingPositionValue = 4;
            public readonly static int PlannedProfit = 4;
            public readonly static int PlannedTP = 0;
            public readonly static int ExecutedTP = 0;
            public readonly static int PlannedSL = 0;
            public readonly static int ExecutedSL = 0;
            public readonly static int PlannedRiskAmount = 4;
            public readonly static int PlannedRiskRewardRatio = 0;
            public readonly static int RealizedProfitLoss = 4;
            public readonly static int RealizedRiskAmount = 4;
        }
    }
}
