//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using System;
using System.Collections.Generic;
using TD.Models;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for Trade CRUD operations.
    /// </summary>
    public partial class TradeRepository : AbstractDatabaseRepository<Trade>, ITradeRepository
    {
        public TradeRepository(string databasePath
                               ,ITradingAccountRepository? tradingAccountRepository = null 
                               ,ISymbolRepository? symbolRepository = null 
                               ,IEntryOrderRepository? entryOrderRepository = null 
                               ,ITakeProfitOrderRepository? takeProfitOrderRepository = null 
                               ,IStopLossOrderRepository? stopLossOrderRepository = null 
                               ,ITradeImageRepository? tradeImageRepository = null) : base(databasePath, "Trades") 
        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            _tradingAccountRepository = tradingAccountRepository ?? new TradingAccountRepository(databasePath);
            _symbolRepository = symbolRepository ?? new SymbolRepository(databasePath);
            _entryOrderRepository = entryOrderRepository ?? new EntryOrderRepository(databasePath);
            _takeProfitOrderRepository = takeProfitOrderRepository ?? new TakeProfitOrderRepository(databasePath);
            _stopLossOrderRepository = stopLossOrderRepository ?? new StopLossOrderRepository(databasePath);
            _tradeImageRepository = tradeImageRepository ?? new TradeImageRepository(databasePath);
            InitializeDatabase();
        }
        private readonly string _selectStatement;
        private readonly ITradingAccountRepository _tradingAccountRepository;
        private readonly ISymbolRepository _symbolRepository;
        private readonly IEntryOrderRepository _entryOrderRepository;
        private readonly ITakeProfitOrderRepository _takeProfitOrderRepository;
        private readonly IStopLossOrderRepository _stopLossOrderRepository;
        private readonly ITradeImageRepository _tradeImageRepository;

        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "Trade.sql");
        }

        public async Task<IReadOnlyList<Trade>> GetAllAsync()
        {
            var result = new List<Trade>();
            var tradingAccountsById = (await _tradingAccountRepository.GetAllAsync()).ToDictionary(item => item.Id);
            var symbolsById = (await _symbolRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " ORDER BY Id";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var trade = MapTrade(reader);
                if (tradingAccountsById.TryGetValue(trade.TradingAccountId, out var tradingAccount))
                    trade.TradingAccount = tradingAccount;

                if (symbolsById.TryGetValue(trade.SymbolId, out var symbol))
                    trade.Symbol = symbol;

                result.Add(trade);
            }

            return result;
        }

        public async Task<IReadOnlyList<Trade>> GetByTradingAccountIdAsync(int tradingAccountId)
        {
            var result = new List<Trade>();
            var tradingAccountsById = (await _tradingAccountRepository.GetAllAsync()).ToDictionary(item => item.Id);
            var symbolsById = (await _symbolRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE TradingAccountId = @tradingAccountId";
            command.Parameters.AddWithValue("@tradingAccountId", tradingAccountId);
            command.CommandText += " ORDER BY Id";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var trade = MapTrade(reader);
                if (tradingAccountsById.TryGetValue(trade.TradingAccountId, out var tradingAccount))
                    trade.TradingAccount = tradingAccount;

                if (symbolsById.TryGetValue(trade.SymbolId, out var symbol))
                    trade.Symbol = symbol;

                result.Add(trade);
            }

            return result;
        }
        

        public async Task<IReadOnlyList<Trade>> GetBySymbolIdAsync(int symbolId)
        {
            var result = new List<Trade>();
            var tradingAccountsById = (await _tradingAccountRepository.GetAllAsync()).ToDictionary(item => item.Id);
            var symbolsById = (await _symbolRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE SymbolId = @symbolId";
            command.Parameters.AddWithValue("@symbolId", symbolId);
            command.CommandText += " ORDER BY Id";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var trade = MapTrade(reader);
                if (tradingAccountsById.TryGetValue(trade.TradingAccountId, out var tradingAccount))
                    trade.TradingAccount = tradingAccount;

                if (symbolsById.TryGetValue(trade.SymbolId, out var symbol))
                    trade.Symbol = symbol;

                result.Add(trade);
            }

            return result;
        }
        

        public async Task<Trade?> GetByIdAsync(int? id)
        {
            if (!id.HasValue || id.Value < 1)
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var trade = MapTrade(reader);
            await LoadTradingAccountAsync(trade);
            await LoadSymbolAsync(trade);
            
            OnLoaded(trade);
            return trade;
        }
        partial void OnLoaded(Trade trade);

        public async Task<int> CreateAsync(Trade trade)
        {
            ArgumentNullException.ThrowIfNull(trade);
            ValidateOrThrow(trade);

            await using var connection = await GetOpenConnectionAsync();

            await using var command = connection.CreateCommand();
            command.CommandText = @$"INSERT INTO {_tableName} ({string.Join(", ", ColumnNames[1..])})
            VALUES (@tradingAccountId, @symbolId, @entryTime, @entryMethod, @tradeDirection, @plannedEntry, @executedEntry, @orderQuantity, @filledQuantity, @plannedTP, @executedTP, @plannedSL, @executedSL, @updatedAt);
            SELECT last_insert_rowid();";
            
            var nowUtc = DateTime.UtcNow;
            command.Parameters.AddWithValue("@tradingAccountId", trade.TradingAccountId);
            command.Parameters.AddWithValue("@symbolId", trade.SymbolId);
            command.Parameters.AddWithValue("@entryTime", trade.EntryTime);
            command.Parameters.AddWithValue("@entryMethod", (int)trade.EntryMethod);
            command.Parameters.AddWithValue("@tradeDirection", (int)trade.TradeDirection);
            command.Parameters.AddWithValue("@plannedEntry", trade.PlannedEntry);
            command.Parameters.AddWithValue("@executedEntry", trade.ExecutedEntry);
            command.Parameters.AddWithValue("@orderQuantity", trade.OrderQuantity);
            command.Parameters.AddWithValue("@filledQuantity", trade.FilledQuantity);
            command.Parameters.AddWithValue("@plannedTP", trade.PlannedTP);
            command.Parameters.AddWithValue("@executedTP", trade.ExecutedTP);
            command.Parameters.AddWithValue("@plannedSL", trade.PlannedSL);
            command.Parameters.AddWithValue("@executedSL", trade.ExecutedSL);
            command.Parameters.AddWithValue("@updatedAt", nowUtc.ToString("O"));

            var id = Convert.ToInt32((long)(await command.ExecuteScalarAsync() ?? 0));
            
            await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            ClearRecordCountCache();
            trade.Id = id;
            OnCreated(trade);

            return id;
        }
        partial void OnCreated(Trade trade);

        public async Task<bool> DeleteAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"DELETE FROM {_tableName} WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                ClearRecordCountCache();
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateAsync(Trade trade)
        {
            ArgumentNullException.ThrowIfNull(trade);
            ValidateOrThrow(trade);

            await using var connection = await GetOpenConnectionAsync();
            var existingTrade = await GetByIdAsync(trade.Id);
            bool noChanges = existingTrade != null
                          && existingTrade.EntryTime == trade.EntryTime 
                          && existingTrade.EntryMethod == trade.EntryMethod 
                          && existingTrade.TradeDirection == trade.TradeDirection 
                          && existingTrade.PlannedEntry == trade.PlannedEntry 
                          && existingTrade.ExecutedEntry == trade.ExecutedEntry 
                          && existingTrade.OrderQuantity == trade.OrderQuantity 
                          && existingTrade.FilledQuantity == trade.FilledQuantity 
                          && existingTrade.PlannedTP == trade.PlannedTP 
                          && existingTrade.ExecutedTP == trade.ExecutedTP 
                          && existingTrade.PlannedSL == trade.PlannedSL 
                          && existingTrade.ExecutedSL == trade.ExecutedSL 
                          && existingTrade.UpdatedAt == trade.UpdatedAt; 

            if (noChanges)
                return false;

            await using var command = connection.CreateCommand();
            // TradingAccountId, SymbolId are not updated to avoid complications with existing references,
            // so only EntryTime, EntryMethod, TradeDirection, PlannedEntry, ExecutedEntry, OrderQuantity, FilledQuantity, PlannedTP, ExecutedTP, PlannedSL, ExecutedSL, UpdatedAt are updated
            command.CommandText = @$"UPDATE {_tableName} SET
                EntryTime = @entryTime, 
                EntryMethod = @entryMethod, 
                TradeDirection = @tradeDirection, 
                PlannedEntry = @plannedEntry, 
                ExecutedEntry = @executedEntry, 
                OrderQuantity = @orderQuantity, 
                FilledQuantity = @filledQuantity, 
                PlannedTP = @plannedTP, 
                ExecutedTP = @executedTP, 
                PlannedSL = @plannedSL, 
                ExecutedSL = @executedSL, 
                UpdatedAt = @updatedAt 
            WHERE Id = @id";

            var nowUtc = DateTime.UtcNow;
            command.Parameters.AddWithValue("@id", trade.Id);
            command.Parameters.AddWithValue("@entryTime", trade.EntryTime);
            command.Parameters.AddWithValue("@entryMethod", (int)trade.EntryMethod);
            command.Parameters.AddWithValue("@tradeDirection", (int)trade.TradeDirection);
            command.Parameters.AddWithValue("@plannedEntry", trade.PlannedEntry);
            command.Parameters.AddWithValue("@executedEntry", trade.ExecutedEntry);
            command.Parameters.AddWithValue("@orderQuantity", trade.OrderQuantity);
            command.Parameters.AddWithValue("@filledQuantity", trade.FilledQuantity);
            command.Parameters.AddWithValue("@plannedTP", trade.PlannedTP);
            command.Parameters.AddWithValue("@executedTP", trade.ExecutedTP);
            command.Parameters.AddWithValue("@plannedSL", trade.PlannedSL);
            command.Parameters.AddWithValue("@executedSL", trade.ExecutedSL);
            command.Parameters.AddWithValue("@updatedAt", nowUtc.ToString("O"));

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(trade);
            }
            
            return affectedRows > 0;
        }
        partial void OnUpdated(Trade trade);

        private async Task LoadTradingAccountAsync(Trade trade)
        {
            trade.TradingAccount = await _tradingAccountRepository.GetByIdAsync(trade.TradingAccountId)
                            ?? new TradingAccount { Id = trade.TradingAccountId };
        }


        private async Task LoadSymbolAsync(Trade trade)
        {
            trade.Symbol = await _symbolRepository.GetByIdAsync(trade.SymbolId)
                            ?? new Symbol { Id = trade.SymbolId };
        }


        private static Trade MapTrade(SqliteDataReader reader)
        {
            var trade = new Trade
            {
                Id = reader.GetInt32(ColNrs.Id), 
                TradingAccountId = reader.GetInt32(ColNrs.TradingAccountId), 
                SymbolId = reader.GetInt32(ColNrs.SymbolId), 
                EntryTime = reader.IsDBNull(ColNrs.EntryTime) ? null : ToLocalDateTime(reader.GetString(ColNrs.EntryTime)), 
                EntryMethod = (EntryMethod)reader.GetInt32(ColNrs.EntryMethod), 
                TradeDirection = (TradeDirection)reader.GetInt32(ColNrs.TradeDirection), 
                PlannedEntry = reader.IsDBNull(ColNrs.PlannedEntry) ? null : reader.GetDecimal(ColNrs.PlannedEntry), 
                ExecutedEntry = reader.IsDBNull(ColNrs.ExecutedEntry) ? null : reader.GetDecimal(ColNrs.ExecutedEntry), 
                OrderQuantity = reader.IsDBNull(ColNrs.OrderQuantity) ? null : reader.GetDecimal(ColNrs.OrderQuantity), 
                FilledQuantity = reader.IsDBNull(ColNrs.FilledQuantity) ? null : reader.GetDecimal(ColNrs.FilledQuantity), 
                PlannedTP = reader.IsDBNull(ColNrs.PlannedTP) ? null : reader.GetDecimal(ColNrs.PlannedTP), 
                ExecutedTP = reader.IsDBNull(ColNrs.ExecutedTP) ? null : reader.GetDecimal(ColNrs.ExecutedTP), 
                PlannedSL = reader.IsDBNull(ColNrs.PlannedSL) ? null : reader.GetDecimal(ColNrs.PlannedSL), 
                ExecutedSL = reader.IsDBNull(ColNrs.ExecutedSL) ? null : reader.GetDecimal(ColNrs.ExecutedSL), 
                UpdatedAt = ToLocalDateTime(reader.GetString(ColNrs.UpdatedAt)) ?? DateTime.MinValue 

            };

            return trade;
        }

        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int TradingAccountId = 1;
            public readonly static int SymbolId = 2;
            public readonly static int EntryTime = 3;
            public readonly static int EntryMethod = 4;
            public readonly static int TradeDirection = 5;
            public readonly static int PlannedEntry = 6;
            public readonly static int ExecutedEntry = 7;
            public readonly static int OrderQuantity = 8;
            public readonly static int FilledQuantity = 9;
            public readonly static int PlannedTP = 10;
            public readonly static int ExecutedTP = 11;
            public readonly static int PlannedSL = 12;
            public readonly static int ExecutedSL = 13;
            public readonly static int UpdatedAt = 14;
        }

        public readonly string[] ColumnNames = new[] {
            "Id", 
            "TradingAccountId", 
            "SymbolId", 
            "EntryTime", 
            "EntryMethod", 
            "TradeDirection", 
            "PlannedEntry", 
            "ExecutedEntry", 
            "OrderQuantity", 
            "FilledQuantity", 
            "PlannedTP", 
            "ExecutedTP", 
            "PlannedSL", 
            "ExecutedSL", 
            "UpdatedAt" 
        };
    }

    public interface ITradeRepository
    {
        Task<IReadOnlyList<Trade>> GetAllAsync();
        Task<IReadOnlyList<Trade>> GetByTradingAccountIdAsync(int tradingAccountId);
        Task<IReadOnlyList<Trade>> GetBySymbolIdAsync(int symbolId);
        Task<Trade?> GetByIdAsync(int? id);
        Task<int> CreateAsync(Trade trade);
        Task<bool> DeleteAsync(int id);
        Task<bool> UpdateAsync(Trade trade);
    }
}
