using System.Windows;
using TD.AppInfra.Services;
using TD.AppInfra.ViewModels;
using TD.Models;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.WPF.Services
{
    internal partial interface IWindowDialogService
    {
        /// <summary>
        /// Displays the Currency creation dialog and returns the result indicating whether the user confirmed the dialog
        /// and the created Currency, if any.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This determines the dialog's parent window for modality and positioning.</param>
        /// <returns>A tuple containing a Boolean value that is <see langword="true"/> if the user confirmed the dialog; otherwise, <see
        /// langword="false"/>. The second item is the created Currency if confirmed; otherwise, <see langword="null"/>.</returns>
        (bool IsConfirmed, Currency? Currency) ShowCurrencyCreateDialog(Window owner);

        /// <summary>
        /// Displays a modal dialog for editing the specified Currency and returns the result indicating whether the dialog
        /// was confirmed and if any changes were made.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="currency">The Currency entity to edit. The dialog will display and allow editing of this currency's properties.</param>
        /// <returns>A tuple containing two values: IsConfirmed is <see langword="true"/> if the user confirmed the dialog;
        /// otherwise, <see langword="false"/>. IsDirty is <see langword="true"/> if any changes were made to the currency
        /// during editing; otherwise, <see langword="false"/>.</returns>
        (bool IsConfirmed, bool IsDirty) ShowCurrencyEditDialog(Window owner, Currency currency);

        /// <summary>
        /// Displays the Exchange creation dialog and returns the result indicating whether the user confirmed the dialog
        /// and the created Exchange, if any.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This determines the dialog's parent window for modality and positioning.</param>
        /// <param name="currencyLookupService">The currency lookup service used to provide currency selection options within the dialog.</param>
        /// <returns>A tuple containing a Boolean value that is <see langword="true"/> if the user confirmed the dialog; otherwise, <see
        /// langword="false"/>. The second item is the created Exchange if confirmed; otherwise, <see langword="null"/>.</returns>
        (bool IsConfirmed, Exchange? Exchange) ShowExchangeCreateDialog(Window owner, ICurrencyLookupService currencyLookupService);

        /// <summary>
        /// Displays a modal dialog for editing the specified Exchange and returns the result indicating whether the dialog
        /// was confirmed and if any changes were made.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="exchange">The Exchange entity to edit. The dialog will display and allow editing of this exchange's properties.</param>
        /// <returns>A tuple containing two values: IsConfirmed is <see langword="true"/> if the user confirmed the dialog;
        /// otherwise, <see langword="false"/>. IsDirty is <see langword="true"/> if any changes were made to the exchange
        /// during editing; otherwise, <see langword="false"/>.</returns>
        (bool IsConfirmed, bool IsDirty) ShowExchangeEditDialog(Window owner, Exchange exchange);

        /// <summary>
        /// Displays the Symbol creation dialog and returns the result indicating whether the user confirmed the dialog
        /// and the created Symbol, if any.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This determines the dialog's parent window for modality and positioning.</param>
        /// <param name="currencyLookupService">The currency lookup service used to provide currency selection options within the dialog.</param>
        /// <param name="exchangeLookupService">The exchange lookup service used to provide exchange selection options within the dialog.</param>
        /// <param name="preselectedExchange">An optional preselected exchange to initialize the dialog with.</param>
        /// <returns>A tuple containing a Boolean value that is <see langword="true"/> if the user confirmed the dialog; otherwise, <see
        /// langword="false"/>. The second item is the created Symbol if confirmed; otherwise, <see langword="null"/>.</returns>
        (bool IsConfirmed, Symbol? Symbol) ShowSymbolCreateDialog(Window owner, ICurrencyLookupService currencyLookupService, IExchangeLookupService exchangeLookupService, Exchange? preselectedExchange);

        /// <summary>
        /// Displays a modal dialog for editing the specified Symbol and returns the result indicating whether the dialog
        /// was confirmed and if any changes were made.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="symbol">The Symbol entity to edit. The dialog will display and allow editing of this symbol's properties.</param>
        /// <returns>A tuple containing two values: IsConfirmed is <see langword="true"/> if the user confirmed the dialog;
        /// otherwise, <see langword="false"/>. IsDirty is <see langword="true"/> if any changes were made to the symbol
        /// during editing; otherwise, <see langword="false"/>.</returns>
        (bool IsConfirmed, bool IsDirty) ShowSymbolEditDialog(Window owner, Symbol symbol);

        /// <summary>
        /// Displays the Trading Account creation dialog and returns the result indicating whether the user confirmed the dialog
        /// and the created Trading Account, if any.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This determines the dialog's parent window for modality and positioning.</param>
        /// <param name="exchangeLookupService">The exchange lookup service used to provide exchange selection options within the dialog.</param>
        /// <param name="preselectedExchange">An optional preselected exchange to initialize the dialog with.</param>
        /// <returns>A tuple containing a Boolean value that is <see langword="true"/> if the user confirmed the dialog; otherwise, <see
        /// langword="false"/>. The second item is the created Trading Account if confirmed; otherwise, <see langword="null"/>.</returns>
        (bool IsConfirmed, TradingAccount? TradingAccount) ShowTradingAccountCreateDialog(Window owner, IExchangeLookupService exchangeLookupService, Exchange? preselectedExchange);

        /// <summary>
        /// Displays a modal dialog for editing the specified Trading Account and returns the result indicating whether the dialog
        /// was confirmed and if any changes were made.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="tradingAccount">The Trading Account entity to edit. The dialog will display and allow editing of this tradingAccount's properties.</param>
        /// <returns>A tuple containing two values: IsConfirmed is <see langword="true"/> if the user confirmed the dialog;
        /// otherwise, <see langword="false"/>. IsDirty is <see langword="true"/> if any changes were made to the tradingAccount
        /// during editing; otherwise, <see langword="false"/>.</returns>
        (bool IsConfirmed, bool IsDirty) ShowTradingAccountEditDialog(Window owner, TradingAccount tradingAccount);

    }
}