using TD.Models;
using TD.SQLite;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.WPF.Services
{
    public partial class TradingAccountLookupService : ITradingAccountLookupService
    {
        private readonly ITradingAccountRepository _tradingAccountRepository;

        public TradingAccountLookupService(ITradingAccountRepository tradingAccountRepository)
        {
            _tradingAccountRepository = tradingAccountRepository;
        }

        public async Task<IReadOnlyList<TradingAccount>> GetTradingAccountsAsync(bool isActive)
        {
            var tradingAccounts = await _tradingAccountRepository.GetAllAsync(isActive);
            return tradingAccounts.ToList();
        }
    }

    /// <summary>
    /// Provides a no-op implementation of the I interface that returns an empty list of tradingAccounts.
    /// </summary>
    /// <remarks>This implementation can be used in scenarios where tradingAccount lookup functionality is optional or not
    /// required, such as in design time, in testing or when no ITradingAccountRepository are configured.</remarks>
    internal sealed partial class EmptyTradingAccountLookupService : ITradingAccountLookupService
    {
        public Task<IReadOnlyList<TradingAccount>> GetTradingAccountsAsync(bool isActive)
        {
            var tradingAccounts = new List<TradingAccount>();
            FillMockData(tradingAccounts);
            return Task.FromResult<IReadOnlyList<TradingAccount>>(tradingAccounts);
        }

        /// <summary>
        /// Populates the specified list with mock tradingAccount data for testing or demonstration purposes.
        /// </summary>
        /// <remarks>This method is intended for use in test scenarios or when sample data is required.
        /// The implementation should ensure that the provided list is filled with representative tradingAccount objects as
        /// needed by the caller.</remarks>
        /// <param name="tradingAccounts">The list of <see cref="TradingAccount"/> objects to populate with mock data. Must not be null.</param>
        partial void FillMockData(List<TradingAccount> tradingAccounts);
    }
}
